! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : cbm42_strato_SOA_Parameters.f90
! Time                 : Fri Sep 21 17:34:02 2018
! Working directory    : /home/hanniner/tmp/silam_v5_6-test/kpp/cbm42_strato_SOA
! Equation file        : cbm42_strato_SOA.kpp
! Output root filename : cbm42_strato_SOA
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE cbm42_strato_SOA_Parameters

  USE cbm42_strato_SOA_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 78 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 72 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 70 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 6 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 234 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 73 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 613 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 678 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 73 
! NHESS - Length of Sparse Hessian
  INTEGER, PARAMETER :: NHESS = 587 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 78 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 1 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_Br2 = 1 
  INTEGER, PARAMETER :: ind_BrNO2 = 2 
  INTEGER, PARAMETER :: ind_CCl3F = 3 
  INTEGER, PARAMETER :: ind_CCl2F2 = 4 
  INTEGER, PARAMETER :: ind_CCl4 = 5 
  INTEGER, PARAMETER :: ind_AVB0 = 6 
  INTEGER, PARAMETER :: ind_AVB1e0 = 7 
  INTEGER, PARAMETER :: ind_AVB1e1 = 8 
  INTEGER, PARAMETER :: ind_AVB1e2 = 9 
  INTEGER, PARAMETER :: ind_AVB1e3 = 10 
  INTEGER, PARAMETER :: ind_AVB1e4 = 11 
  INTEGER, PARAMETER :: ind_AVB1e5 = 12 
  INTEGER, PARAMETER :: ind_AVB1e6 = 13 
  INTEGER, PARAMETER :: ind_BVB0 = 14 
  INTEGER, PARAMETER :: ind_BVB1e0 = 15 
  INTEGER, PARAMETER :: ind_BVB1e1 = 16 
  INTEGER, PARAMETER :: ind_BVB1e2 = 17 
  INTEGER, PARAMETER :: ind_BVB1e3 = 18 
  INTEGER, PARAMETER :: ind_CH3CCl3 = 19 
  INTEGER, PARAMETER :: ind_CRO = 20 
  INTEGER, PARAMETER :: ind_BrONO2 = 21 
  INTEGER, PARAMETER :: ind_BrCl = 22 
  INTEGER, PARAMETER :: ind_PAN = 23 
  INTEGER, PARAMETER :: ind_TOL = 24 
  INTEGER, PARAMETER :: ind_CH3Cl = 25 
  INTEGER, PARAMETER :: ind_CH3Br = 26 
  INTEGER, PARAMETER :: ind_Cl2O2 = 27 
  INTEGER, PARAMETER :: ind_N2O5 = 28 
  INTEGER, PARAMETER :: ind_XYL = 29 
  INTEGER, PARAMETER :: ind_N = 30 
  INTEGER, PARAMETER :: ind_N2O = 31 
  INTEGER, PARAMETER :: ind_HONO = 32 
  INTEGER, PARAMETER :: ind_XO2N = 33 
  INTEGER, PARAMETER :: ind_TO2 = 34 
  INTEGER, PARAMETER :: ind_ClNO2 = 35 
  INTEGER, PARAMETER :: ind_HOBr = 36 
  INTEGER, PARAMETER :: ind_PNA = 37 
  INTEGER, PARAMETER :: ind_ROR = 38 
  INTEGER, PARAMETER :: ind_MGLY = 39 
  INTEGER, PARAMETER :: ind_H2O2 = 40 
  INTEGER, PARAMETER :: ind_CRES = 41 
  INTEGER, PARAMETER :: ind_HNO3 = 42 
  INTEGER, PARAMETER :: ind_CO = 43 
  INTEGER, PARAMETER :: ind_Cl2 = 44 
  INTEGER, PARAMETER :: ind_ETH = 45 
  INTEGER, PARAMETER :: ind_OPEN = 46 
  INTEGER, PARAMETER :: ind_XO2 = 47 
  INTEGER, PARAMETER :: ind_ClONO2 = 48 
  INTEGER, PARAMETER :: ind_HOCl = 49 
  INTEGER, PARAMETER :: ind_PAR = 50 
  INTEGER, PARAMETER :: ind_C5H8_2 = 51 
  INTEGER, PARAMETER :: ind_HBr = 52 
  INTEGER, PARAMETER :: ind_HCl = 53 
  INTEGER, PARAMETER :: ind_C2O3 = 54 
  INTEGER, PARAMETER :: ind_C5H8 = 55 
  INTEGER, PARAMETER :: ind_OLE = 56 
  INTEGER, PARAMETER :: ind_ALD2 = 57 
  INTEGER, PARAMETER :: ind_H = 58 
  INTEGER, PARAMETER :: ind_OClO = 59 
  INTEGER, PARAMETER :: ind_NO3 = 60 
  INTEGER, PARAMETER :: ind_Br = 61 
  INTEGER, PARAMETER :: ind_O = 62 
  INTEGER, PARAMETER :: ind_OH = 63 
  INTEGER, PARAMETER :: ind_O3 = 64 
  INTEGER, PARAMETER :: ind_HO2 = 65 
  INTEGER, PARAMETER :: ind_O1D = 66 
  INTEGER, PARAMETER :: ind_Cl = 67 
  INTEGER, PARAMETER :: ind_ClO = 68 
  INTEGER, PARAMETER :: ind_BrO = 69 
  INTEGER, PARAMETER :: ind_NO = 70 
  INTEGER, PARAMETER :: ind_NO2 = 71 
  INTEGER, PARAMETER :: ind_HCHO = 72 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_H2O = 73 
  INTEGER, PARAMETER :: ind_H2 = 74 
  INTEGER, PARAMETER :: ind_O2 = 75 
  INTEGER, PARAMETER :: ind_CH4 = 76 
  INTEGER, PARAMETER :: ind_CO2 = 77 
  INTEGER, PARAMETER :: ind_M = 78 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_H2O = 1 
  INTEGER, PARAMETER :: indf_H2 = 2 
  INTEGER, PARAMETER :: indf_O2 = 3 
  INTEGER, PARAMETER :: indf_CH4 = 4 
  INTEGER, PARAMETER :: indf_CO2 = 5 
  INTEGER, PARAMETER :: indf_M = 6 

END MODULE cbm42_strato_SOA_Parameters

