! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : cbm42_strato_Parameters.f90
! Time                 : Fri Apr 23 13:17:36 2021
! Working directory    : /fmi/scratch/project_2001411/risto/silam_v5_7/kpp/cbm42_strato
! Equation file        : cbm42_strato.kpp
! Output root filename : cbm42_strato
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE cbm42_strato_Parameters

  USE cbm42_strato_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 68 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 62 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 61 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 6 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 208 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 63 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 582 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 635 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 63 
! NHESS - Length of Sparse Hessian
  INTEGER, PARAMETER :: NHESS = 572 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 68 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 1 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_BrNO2 = 1 
  INTEGER, PARAMETER :: ind_CCl3F = 2 
  INTEGER, PARAMETER :: ind_CCl2F2 = 3 
  INTEGER, PARAMETER :: ind_CCl4 = 4 
  INTEGER, PARAMETER :: ind_NTR = 5 
  INTEGER, PARAMETER :: ind_Br2 = 6 
  INTEGER, PARAMETER :: ind_CH3CCl3 = 7 
  INTEGER, PARAMETER :: ind_MEOH = 8 
  INTEGER, PARAMETER :: ind_ETOH = 9 
  INTEGER, PARAMETER :: ind_PAN = 10 
  INTEGER, PARAMETER :: ind_CRO = 11 
  INTEGER, PARAMETER :: ind_BrONO2 = 12 
  INTEGER, PARAMETER :: ind_BrCl = 13 
  INTEGER, PARAMETER :: ind_TOL = 14 
  INTEGER, PARAMETER :: ind_CH3Br = 15 
  INTEGER, PARAMETER :: ind_Cl2O2 = 16 
  INTEGER, PARAMETER :: ind_N2O5 = 17 
  INTEGER, PARAMETER :: ind_XYL = 18 
  INTEGER, PARAMETER :: ind_N = 19 
  INTEGER, PARAMETER :: ind_N2O = 20 
  INTEGER, PARAMETER :: ind_HONO = 21 
  INTEGER, PARAMETER :: ind_TO2 = 22 
  INTEGER, PARAMETER :: ind_ClNO2 = 23 
  INTEGER, PARAMETER :: ind_HOBr = 24 
  INTEGER, PARAMETER :: ind_PNA = 25 
  INTEGER, PARAMETER :: ind_CH3Cl = 26 
  INTEGER, PARAMETER :: ind_ROR4 = 27 
  INTEGER, PARAMETER :: ind_MGLY = 28 
  INTEGER, PARAMETER :: ind_H2O2 = 29 
  INTEGER, PARAMETER :: ind_CRES = 30 
  INTEGER, PARAMETER :: ind_HNO3 = 31 
  INTEGER, PARAMETER :: ind_ETH = 32 
  INTEGER, PARAMETER :: ind_CO = 33 
  INTEGER, PARAMETER :: ind_OPEN = 34 
  INTEGER, PARAMETER :: ind_Cl2 = 35 
  INTEGER, PARAMETER :: ind_XO2N = 36 
  INTEGER, PARAMETER :: ind_ClONO2 = 37 
  INTEGER, PARAMETER :: ind_HOCl = 38 
  INTEGER, PARAMETER :: ind_HCl = 39 
  INTEGER, PARAMETER :: ind_HBr = 40 
  INTEGER, PARAMETER :: ind_OLE4 = 41 
  INTEGER, PARAMETER :: ind_XO2 = 42 
  INTEGER, PARAMETER :: ind_PAR4 = 43 
  INTEGER, PARAMETER :: ind_C2O3 = 44 
  INTEGER, PARAMETER :: ind_ISPD = 45 
  INTEGER, PARAMETER :: ind_C5H8 = 46 
  INTEGER, PARAMETER :: ind_ALD2 = 47 
  INTEGER, PARAMETER :: ind_H = 48 
  INTEGER, PARAMETER :: ind_OClO = 49 
  INTEGER, PARAMETER :: ind_NO3 = 50 
  INTEGER, PARAMETER :: ind_HCHO = 51 
  INTEGER, PARAMETER :: ind_ClO = 52 
  INTEGER, PARAMETER :: ind_NO = 53 
  INTEGER, PARAMETER :: ind_NO2 = 54 
  INTEGER, PARAMETER :: ind_Br = 55 
  INTEGER, PARAMETER :: ind_O3 = 56 
  INTEGER, PARAMETER :: ind_OH = 57 
  INTEGER, PARAMETER :: ind_HO2 = 58 
  INTEGER, PARAMETER :: ind_BrO = 59 
  INTEGER, PARAMETER :: ind_O1D = 60 
  INTEGER, PARAMETER :: ind_O = 61 
  INTEGER, PARAMETER :: ind_Cl = 62 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_H2O = 63 
  INTEGER, PARAMETER :: ind_H2 = 64 
  INTEGER, PARAMETER :: ind_O2 = 65 
  INTEGER, PARAMETER :: ind_CH4 = 66 
  INTEGER, PARAMETER :: ind_CO2 = 67 
  INTEGER, PARAMETER :: ind_M = 68 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_H2O = 1 
  INTEGER, PARAMETER :: indf_H2 = 2 
  INTEGER, PARAMETER :: indf_O2 = 3 
  INTEGER, PARAMETER :: indf_CH4 = 4 
  INTEGER, PARAMETER :: indf_CO2 = 5 
  INTEGER, PARAMETER :: indf_M = 6 

END MODULE cbm42_strato_Parameters

