! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : cbm42_strato_Parameters.f90
! Time                 : Fri Sep 21 17:33:58 2018
! Working directory    : /home/hanniner/tmp/silam_v5_6-test/kpp/cbm42_strato
! Equation file        : cbm42_strato.kpp
! Output root filename : cbm42_strato
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE cbm42_strato_Parameters

  USE cbm42_strato_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 64 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 58 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 58 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 6 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 195 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 59 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 531 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 598 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 59 
! NHESS - Length of Sparse Hessian
  INTEGER, PARAMETER :: NHESS = 500 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 64 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 1 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_Br2 = 1 
  INTEGER, PARAMETER :: ind_BrNO2 = 2 
  INTEGER, PARAMETER :: ind_CCl3F = 3 
  INTEGER, PARAMETER :: ind_CCl2F2 = 4 
  INTEGER, PARAMETER :: ind_CCl4 = 5 
  INTEGER, PARAMETER :: ind_CH3CCl3 = 6 
  INTEGER, PARAMETER :: ind_PAN = 7 
  INTEGER, PARAMETER :: ind_CRO = 8 
  INTEGER, PARAMETER :: ind_BrONO2 = 9 
  INTEGER, PARAMETER :: ind_BrCl = 10 
  INTEGER, PARAMETER :: ind_TOL = 11 
  INTEGER, PARAMETER :: ind_CH3Cl = 12 
  INTEGER, PARAMETER :: ind_CH3Br = 13 
  INTEGER, PARAMETER :: ind_Cl2O2 = 14 
  INTEGER, PARAMETER :: ind_N2O5 = 15 
  INTEGER, PARAMETER :: ind_XYL = 16 
  INTEGER, PARAMETER :: ind_XO2N = 17 
  INTEGER, PARAMETER :: ind_N = 18 
  INTEGER, PARAMETER :: ind_N2O = 19 
  INTEGER, PARAMETER :: ind_HONO = 20 
  INTEGER, PARAMETER :: ind_TO2 = 21 
  INTEGER, PARAMETER :: ind_PNA = 22 
  INTEGER, PARAMETER :: ind_ClNO2 = 23 
  INTEGER, PARAMETER :: ind_HOBr = 24 
  INTEGER, PARAMETER :: ind_ROR = 25 
  INTEGER, PARAMETER :: ind_MGLY = 26 
  INTEGER, PARAMETER :: ind_H2O2 = 27 
  INTEGER, PARAMETER :: ind_CRES = 28 
  INTEGER, PARAMETER :: ind_HNO3 = 29 
  INTEGER, PARAMETER :: ind_CO = 30 
  INTEGER, PARAMETER :: ind_Cl2 = 31 
  INTEGER, PARAMETER :: ind_XO2 = 32 
  INTEGER, PARAMETER :: ind_PAR = 33 
  INTEGER, PARAMETER :: ind_OPEN = 34 
  INTEGER, PARAMETER :: ind_ETH = 35 
  INTEGER, PARAMETER :: ind_ClONO2 = 36 
  INTEGER, PARAMETER :: ind_HOCl = 37 
  INTEGER, PARAMETER :: ind_HCl = 38 
  INTEGER, PARAMETER :: ind_HBr = 39 
  INTEGER, PARAMETER :: ind_C2O3 = 40 
  INTEGER, PARAMETER :: ind_C5H8 = 41 
  INTEGER, PARAMETER :: ind_OLE = 42 
  INTEGER, PARAMETER :: ind_ALD2 = 43 
  INTEGER, PARAMETER :: ind_H = 44 
  INTEGER, PARAMETER :: ind_OClO = 45 
  INTEGER, PARAMETER :: ind_NO3 = 46 
  INTEGER, PARAMETER :: ind_NO2 = 47 
  INTEGER, PARAMETER :: ind_O = 48 
  INTEGER, PARAMETER :: ind_OH = 49 
  INTEGER, PARAMETER :: ind_NO = 50 
  INTEGER, PARAMETER :: ind_O3 = 51 
  INTEGER, PARAMETER :: ind_HO2 = 52 
  INTEGER, PARAMETER :: ind_HCHO = 53 
  INTEGER, PARAMETER :: ind_ClO = 54 
  INTEGER, PARAMETER :: ind_O1D = 55 
  INTEGER, PARAMETER :: ind_BrO = 56 
  INTEGER, PARAMETER :: ind_Br = 57 
  INTEGER, PARAMETER :: ind_Cl = 58 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_H2O = 59 
  INTEGER, PARAMETER :: ind_H2 = 60 
  INTEGER, PARAMETER :: ind_O2 = 61 
  INTEGER, PARAMETER :: ind_CH4 = 62 
  INTEGER, PARAMETER :: ind_CO2 = 63 
  INTEGER, PARAMETER :: ind_M = 64 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_H2O = 1 
  INTEGER, PARAMETER :: indf_H2 = 2 
  INTEGER, PARAMETER :: indf_O2 = 3 
  INTEGER, PARAMETER :: indf_CH4 = 4 
  INTEGER, PARAMETER :: indf_CO2 = 5 
  INTEGER, PARAMETER :: indf_M = 6 

END MODULE cbm42_strato_Parameters

