! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Linear Algebra Data and Routines File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : cbm5_strato_SOA_LinearAlgebra.f90
! Time                 : Fri Apr  8 13:32:08 2022
! Working directory    : /home/kouzne/SILAM/silamgit/kpp/cbm5_strato_SOA
! Equation file        : cbm5_strato_SOA.kpp
! Output root filename : cbm5_strato_SOA
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE cbm5_strato_SOA_LinearAlgebra

  USE cbm5_strato_SOA_Parameters
  USE cbm5_strato_SOA_JacobianSP

  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! SPARSE_UTIL - SPARSE utility functions
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppDecomp( JVS, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse LU factorization
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm5_strato_SOA_Parameters
  USE cbm5_strato_SOA_JacobianSP

      INTEGER  :: IER
      REAL(kind=sp) :: JVS(LU_NONZERO), W(NVAR), a
      INTEGER  :: k, kk, j, jj

      a = 0. ! mz_rs_20050606
      IER = 0
      DO k=1,NVAR
        ! mz_rs_20050606: don't check if real value == 0
        ! IF ( JVS( LU_DIAG(k) ) .EQ. 0. ) THEN
        IF ( ABS(JVS(LU_DIAG(k))) < TINY(a) ) THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              W( LU_ICOL(kk) ) = JVS(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            a = -W(j) / JVS( LU_DIAG(j) )
            W(j) = -a
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               W( LU_ICOL(jj) ) = W( LU_ICOL(jj) ) + a*JVS(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVS(kk) = W( LU_ICOL(kk) )
         END DO
      END DO
      
END SUBROUTINE KppDecomp


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppDecompCmplx( JVS, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse LU factorization, complex
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm5_strato_SOA_Parameters
  USE cbm5_strato_SOA_JacobianSP

      INTEGER        :: IER
      DOUBLE COMPLEX :: JVS(LU_NONZERO), W(NVAR), a
      REAL(kind=sp)  :: b = 0.0
      INTEGER        :: k, kk, j, jj

      IER = 0
      DO k=1,NVAR
        IF ( ABS(JVS(LU_DIAG(k))) < TINY(b) ) THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              W( LU_ICOL(kk) ) = JVS(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            a = -W(j) / JVS( LU_DIAG(j) )
            W(j) = -a
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               W( LU_ICOL(jj) ) = W( LU_ICOL(jj) ) + a*JVS(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVS(kk) = W( LU_ICOL(kk) )
         END DO
      END DO
      
END SUBROUTINE KppDecompCmplx


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppDecompCmplxR( JVSR, JVSI, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!    Sparse LU factorization, complex
!   (Real and Imaginary parts are used instead of complex data type)     
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm5_strato_SOA_Parameters
  USE cbm5_strato_SOA_JacobianSP

      INTEGER       :: IER
      REAL(kind=sp) :: JVSR(LU_NONZERO), JVSI(LU_NONZERO) 
      REAL(kind=sp) :: WR(NVAR), WI(NVAR), ar, ai, den
      INTEGER       :: k, kk, j, jj

      IER = 0
      ar  = 0.0
      DO k=1,NVAR
        IF (  ( ABS(JVSR(LU_DIAG(k))) < TINY(ar) ) .AND. &
              ( ABS(JVSI(LU_DIAG(k))) < TINY(ar) ) )  THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              WR( LU_ICOL(kk) ) = JVSR(kk)
              WI( LU_ICOL(kk) ) = JVSI(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            den = JVSR(LU_DIAG(j))**2 + JVSI(LU_DIAG(j))**2
            ar = -(WR(j)*JVSR(LU_DIAG(j)) + WI(j)*JVSI(LU_DIAG(j)))/den
            ai = -(WI(j)*JVSR(LU_DIAG(j)) - WR(j)*JVSI(LU_DIAG(j)))/den
            WR(j) = -ar
            WI(j) = -ai
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               WR( LU_ICOL(jj) ) = WR( LU_ICOL(jj) ) + ar*JVSR(jj) - ai*JVSI(jj)
               WI( LU_ICOL(jj) ) = WI( LU_ICOL(jj) ) + ar*JVSI(jj) + ai*JVSR(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVSR(kk) = WR( LU_ICOL(kk) )
            JVSI(kk) = WI( LU_ICOL(kk) )
         END DO
      END DO

END SUBROUTINE KppDecompCmplxR


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveIndirect( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse solve subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm5_strato_SOA_Parameters
  USE cbm5_strato_SOA_JacobianSP

      INTEGER  :: i, j
      REAL(kind=sp) :: JVS(LU_NONZERO), X(NVAR), sum

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1 
             X(i) = X(i) - JVS(j)*X(LU_ICOL(j));
         END DO  
      END DO

      DO i=NVAR,1,-1
        sum = X(i);
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
          sum = sum - JVS(j)*X(LU_ICOL(j));
        END DO
        X(i) = sum/JVS(LU_DIAG(i));
      END DO
      
END SUBROUTINE KppSolveIndirect


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveTRIndirect( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve transpose subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm5_strato_SOA_Parameters
  USE cbm5_strato_SOA_JacobianSP

      INTEGER       :: i, j
      REAL(kind=sp) :: JVS(LU_NONZERO), X(NVAR)

      DO i=1,NVAR
        X(i) = X(i)/JVS(LU_DIAG(i))
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
	  X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
	END DO
      END DO

      DO i=NVAR, 1, -1
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
	  X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
	END DO
      END DO
      
END SUBROUTINE KppSolveTRIndirect


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveCmplx( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm5_strato_SOA_Parameters
  USE cbm5_strato_SOA_JacobianSP

      INTEGER        :: i, j
      DOUBLE COMPLEX :: JVS(LU_NONZERO), X(NVAR), sum

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1 
             X(i) = X(i) - JVS(j)*X(LU_ICOL(j));
         END DO  
      END DO

      DO i=NVAR,1,-1
        sum = X(i);
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
          sum = sum - JVS(j)*X(LU_ICOL(j));
        END DO
        X(i) = sum/JVS(LU_DIAG(i));
      END DO
      
END SUBROUTINE KppSolveCmplx

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveCmplxR( JVSR, JVSI, XR, XI )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!   Complex sparse solve subroutine using indirect addressing
!   (Real and Imaginary parts are used instead of complex data type)     
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm5_strato_SOA_Parameters
  USE cbm5_strato_SOA_JacobianSP

      INTEGER       ::  i, j
      REAL(kind=sp) ::  JVSR(LU_NONZERO), JVSI(LU_NONZERO), XR(NVAR), XI(NVAR), sumr, sumi, den

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1 
             XR(i) = XR(i) - (JVSR(j)*XR(LU_ICOL(j)) - JVSI(j)*XI(LU_ICOL(j)))
             XI(i) = XI(i) - (JVSR(j)*XI(LU_ICOL(j)) + JVSI(j)*XR(LU_ICOL(j)))
         END DO  
      END DO

      DO i=NVAR,1,-1
        sumr = XR(i); sumi = XI(i)
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
            sumr = sumr - (JVSR(j)*XR(LU_ICOL(j)) - JVSI(j)*XI(LU_ICOL(j)))
            sumi = sumi - (JVSR(j)*XI(LU_ICOL(j)) + JVSI(j)*XR(LU_ICOL(j)))
        END DO
        den   = JVSR(LU_DIAG(i))**2 + JVSI(LU_DIAG(i))**2
        XR(i) = (sumr*JVSR(LU_DIAG(i)) + sumi*JVSI(LU_DIAG(i)))/den
        XI(i) = (sumi*JVSR(LU_DIAG(i)) - sumr*JVSI(LU_DIAG(i)))/den
      END DO
      
END SUBROUTINE KppSolveCmplxR


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveTRCmplx( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve transpose subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm5_strato_SOA_Parameters
  USE cbm5_strato_SOA_JacobianSP

      INTEGER        :: i, j
      DOUBLE COMPLEX :: JVS(LU_NONZERO), X(NVAR)

      DO i=1,NVAR
        X(i) = X(i)/JVS(LU_DIAG(i))
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
	  X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
	END DO
      END DO

      DO i=NVAR, 1, -1
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
	  X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
	END DO
      END DO
      
END SUBROUTINE KppSolveTRCmplx


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveTRCmplxR( JVSR, JVSI, XR, XI )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!   Complex sparse solve transpose subroutine using indirect addressing
!   (Real and Imaginary parts are used instead of complex data type)     
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm5_strato_SOA_Parameters
  USE cbm5_strato_SOA_JacobianSP

      INTEGER       ::  i, j
      REAL(kind=sp) ::  JVSR(LU_NONZERO), JVSI(LU_NONZERO), XR(NVAR), XI(NVAR), den

      DO i=1,NVAR
        den   = JVSR(LU_DIAG(i))**2 + JVSI(LU_DIAG(i))**2
        XR(i) = (XR(i)*JVSR(LU_DIAG(i)) + XI(i)*JVSI(LU_DIAG(i)))/den
        XI(i) = (XI(i)*JVSR(LU_DIAG(i)) - XR(i)*JVSI(LU_DIAG(i)))/den
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
	  XR(LU_ICOL(j)) = XR(LU_ICOL(j))-(JVSR(j)*XR(i) - JVSI(j)*XI(i))
	  XI(LU_ICOL(j)) = XI(LU_ICOL(j))-(JVSI(j)*XR(i) + JVSR(j)*XI(i))
	END DO
      END DO

      DO i=NVAR, 1, -1
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
	  XR(LU_ICOL(j)) = XR(LU_ICOL(j))-(JVSR(j)*XR(i) - JVSI(j)*XI(i))
	  XI(LU_ICOL(j)) = XI(LU_ICOL(j))-(JVSI(j)*XR(i) + JVSR(j)*XI(i))
	END DO
      END DO
      
END SUBROUTINE KppSolveTRCmplxR


!
! Next few commented subroutines perform sparse big linear algebra
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppDecompBig( JVS, IP, IER )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Sparse LU factorization
!!        for the Runge Kutta (3n)x(3n) linear system
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE cbm5_strato_SOA_Parameters
!  USE cbm5_strato_SOA_JacobianSP
!
!      INTEGER  :: IP3(3), IER, IP(3,NVAR)
!      REAL(kind=sp) :: JVS(3,3,LU_NONZERO), W(3,3,NVAR), a(3,3), E(3,3)
!      INTEGER  :: k, kk, j, jj
!
!      a = 0.0d0
!      IER = 0
!      DO k=1,NVAR
!        DO kk = LU_CROW(k), LU_CROW(k+1)-1
!              W( 1:3,1:3,LU_ICOL(kk) ) = JVS(1:3,1:3,kk)
!        END DO
!        DO kk = LU_CROW(k), LU_DIAG(k)-1
!            j = LU_ICOL(kk)
!            E(1:3,1:3) = JVS( 1:3,1:3,LU_DIAG(j) )
!            ! CALL DGETRF(3,3,E,3,IP3,IER) 
!            CALL FAC3(E,IP3,IER)
!            IF ( IER /= 0 )  RETURN
!            ! a = W(j) / JVS( LU_DIAG(j) )
!            a(1:3,1:3) = W( 1:3,1:3,j )
!            ! CALL DGETRS ('N',3,3,E,3,IP3,a,3,IER) 
!            CALL SOL3('N',E,IP3,a(1,1))
!            CALL SOL3('N',E,IP3,a(1,2))
!            CALL SOL3('N',E,IP3,a(1,3))
!            W(1:3,1:3,j) = a(1:3,1:3)
!            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
!               W( 1:3,1:3,LU_ICOL(jj) ) = W( 1:3,1:3,LU_ICOL(jj) ) &
!                        - MATMUL( a(1:3,1:3) , JVS(1:3,1:3,jj) )
!            END DO
!         END DO
!         DO kk = LU_CROW(k), LU_CROW(k+1)-1
!            JVS(1:3,1:3,kk) = W( 1:3,1:3,LU_ICOL(kk) )
!         END DO
!      END DO
!
!      DO k=1,NVAR
!         ! CALL WGEFA(JVS(1,1,LU_DIAG(k)),3,3,IP(1,k),IER)
!         ! CALL DGETRF(3,3,JVS(1,1,LU_DIAG(k)),3,IP(1,k),IER)
!         CALL FAC3(JVS(1,1,LU_DIAG(k)),IP(1,k),IER)
!         IF ( IER /= 0 )  RETURN
!      END DO 
!      
!END SUBROUTINE KppDecompBig
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppSolveBig( JVS, IP, X )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Sparse solve subroutine using indirect addressing
!!        for the Runge Kutta (3n)x(3n) linear system
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE cbm5_strato_SOA_Parameters
!  USE cbm5_strato_SOA_JacobianSP
!
!      INTEGER  :: i, j, k, m, IP3(3), IP(3,NVAR), IER
!      REAL(kind=sp) :: JVS(3,3,LU_NONZERO), X(3,NVAR), sum(3)
!
!      DO i=1,NVAR
!        DO j = LU_CROW(i), LU_DIAG(i)-1 
!          !X(1:3,i) = X(1:3,i) - MATMUL(JVS(1:3,1:3,j),X(1:3,LU_ICOL(j)));
!          DO k=1,3
!            DO m=1,3
!	       X(k,i) = X(k,i) - JVS(k,m,j)*X(m,LU_ICOL(j))
!            END DO
!          END DO
!        END DO  
!      END DO
!
!      DO i=NVAR,1,-1
!        sum(1:3) = X(1:3,i);
!        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
!          !sum(1:3) = sum(1:3) - MATMUL(JVS(1:3,1:3,j),X(1:3,LU_ICOL(j)));
!          DO k=1,3
!            DO m=1,3
!	       sum(k) = sum(k) - JVS(k,m,j)*X(m,LU_ICOL(j))
!            END DO
!          END DO
!        END DO
!        ! X(i) = sum/JVS(LU_DIAG(i));
!        ! CALL DGETRS ('N',3,1,JVS(1:3,1:3,LU_DIAG(i)),3,IP(1,i),sum,3,0) 
!        ! CALL WGESL('N',JVS(1,1,LU_DIAG(i)),3,3,IP(1,i),sum)
!        CALL SOL3('N',JVS(1,1,LU_DIAG(i)),IP(1,i),sum)
!        X(1:3,i) = sum(1:3)
!      END DO
!      
!END SUBROUTINE KppSolveBig
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppSolveBigTR( JVS, IP, X )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Big sparse transpose solve using indirect addressing
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE cbm5_strato_SOA_Parameters
!  USE cbm5_strato_SOA_JacobianSP
!
!      INTEGER       :: i, j, k, m, IP(3,NVAR)
!      REAL(kind=sp) :: JVS(3,3,LU_NONZERO), X(3,NVAR)
!
!      DO i=1,NVAR
!        ! X(i) = X(i)/JVS(LU_DIAG(i))
!        CALL SOL3('T',JVS(1,1,LU_DIAG(i)),IP(1,i),X(1,i))
!        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
!	  !X(1:3,LU_ICOL(j)) = X(1:3,LU_ICOL(j)) &
!          !    - MATMUL( TRANSPOSE(JVS(1:3,1:3,j)), X(1:3,i) )
!          DO k=1,3
!            DO m=1,3
!	       X(k,LU_ICOL(j)) = X(k,LU_ICOL(j)) - JVS(m,k,j)*X(m,i)
!            END DO
!          END DO
!	END DO
!      END DO
!
!      DO i=NVAR, 1, -1
!        DO j=LU_CROW(i),LU_DIAG(i)-1
!	  !X(1:3,LU_ICOL(j)) = X(1:3,LU_ICOL(j)) &
!          !   - MATMUL( TRANSPOSE(JVS(1:3,1:3,j)), X(1:3,i) )
!          DO k=1,3
!            DO m=1,3
!	       X(k,LU_ICOL(j)) = X(k,LU_ICOL(j)) - JVS(m,k,j)*X(m,i)
!            END DO
!          END DO
!	END DO
!      END DO
!      
!END SUBROUTINE KppSolveBigTR
!
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE FAC3(A,IPVT,INFO)
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!     FAC3 FACTORS THE MATRIX A (3,3) BY
!!           GAUSS ELIMINATION WITH PARTIAL PIVOTING
!!     LINPACK - LIKE 
!!
!!     Remove comments to perform pivoting
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!
!      REAL(kind=sp) :: A(3,3)
!      INTEGER       :: IPVT(3),INFO
!!      INTEGER       :: L
!!      REAL(kind=sp) :: t, dmax, da, TMP(3)
!      REAL(kind=sp), PARAMETER :: ZERO = 0.0, ONE = 1.0
!
!      info = 0
!!      t = TINY(da)
!!      
!!      da = ABS(A(1,1)); L = 1
!!      IF ( ABS(A(2,1))>da ) THEN
!!        da = ABS(A(2,1)); L = 2
!!        IF ( ABS(A(3,1))>da ) THEN
!!          L = 3
!!        END IF  
!!      END IF  
!!      IPVT(1)  = L
!!      IF (L /=1 ) THEN
!!         TMP(1:3) = A(L,1:3)
!!         A(L,1:3) = A(1,1:3)
!!         A(1,1:3) = TMP(1:3)
!!      END IF
!!      IF (ABS(A(1,1)) < t) THEN
!!         info = 1
!!         return
!!      END IF   
!!
!      A(2,1) = A(2,1)/A(1,1)
!      A(2,2) = A(2,2) - A(2,1)*A(1,2)
!      A(2,3) = A(2,3) - A(2,1)*A(1,3)
!      A(3,1) = A(3,1)/A(1,1)
!      A(3,2) = A(3,2) - A(3,1)*A(1,2)
!      A(3,3) = A(3,3) - A(3,1)*A(1,3)
!      
!!      IPVT(2)  = 2
!!      IF (ABS(A(3,2))>ABS(A(2,2))) THEN
!!         IPVT(2)  = 3
!!         TMP(2:3) = A(3,2:3)
!!         A(3,2:3) = A(2,2:3)
!!         A(2,2:3) = TMP(2:3)
!!      END IF
!!      IF (ABS(A(2,2)) < t) THEN
!!         info = 1
!!         return
!!      END IF   
!!      
!      A(3,2)   = A(3,2)/A(2,2)
!      A(3,3)   = A(3,3) - A(3,2)*A(2,3)
!      IPVT(3)  = 3
!      
!END SUBROUTINE FAC3
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE SOL3(Trans,A,IPVT,b)
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!     SOL3 solves the system 3x3
!!     A * x = b  or  trans(a) * x = b
!!     using the factors computed by WGEFA.
!!
!!     Trans      = 'N'   to solve  A*x = b ,
!!                = 'T'   to solve  transpose(A)*x = b
!!     LINPACK - LIKE 
!!
!!     Remove comments to use pivoting
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!      CHARACTER     :: Trans
!      REAL(kind=sp) :: a(3,3),b(3)
!      INTEGER       :: IPVT(3)
!!      INTEGER       :: L
!!      REAL(kind=sp) :: TMP
!      
!      SELECT CASE (Trans)
!
!      CASE ('n','N')  !  Solve  A * x = b
!
!!     Solve  L*y = b
!!         L = IPVT(1)
!!         IF (L /= 1) THEN
!!            TMP = B(1); B(1) = B(L); B(L) = TMP
!!         END IF
!         b(2) = b(2)-A(2,1)*b(1)
!         b(3) = b(3)-A(3,1)*b(1)
!         
!!         L = IPVT(2)
!!         IF (L /= 2) THEN
!!            TMP = B(2); B(2) = B(L); B(L) = TMP
!!         END IF
!         b(3) = b(3)-A(3,2)*b(2)
!
!!     Solve  U*x = y
!         b(3) = b(3)/A(3,3)
!         b(2) = (b(2)-A(2,3)*b(3))/A(2,2)
!         b(1) = (b(1)-A(1,3)*b(3)-A(1,2)*b(2))/A(1,1)
!      
!      
!      CASE ('t','T')  !  Solve transpose(A) * x = b
!
!!      Solve transpose(U)*y = b
!         b(1) = b(1)/A(1,1)
!         b(2) = (b(2)-A(1,2)*b(1))/A(2,2)
!         b(3) = (b(3)-A(1,3)*b(1)-A(2,3)*b(2))/A(3,3)
!
!!      Solve transpose(L)*x = y
!         b(2) = b(2)-A(3,2)*b(3)
!!         L = ipvt(2)
!!         IF (L /= 2) THEN
!!            TMP = B(2); B(2) = B(L); B(L) = TMP
!!         END IF
!         b(1) = b(1)-A(3,1)*b(3)-A(2,1)*b(2)
!!         L = ipvt(1)
!!         IF (L /= 1) THEN
!!            TMP = B(1); B(1) = B(L); B(L) = TMP
!!         END IF
!   
!      END SELECT
!
!END SUBROUTINE SOL3

! End of SPARSE_UTIL function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! KppSolve - sparse back substitution
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      X         - Vector for variables
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE KppSolve ( JVS, X )

! JVS - sparse Jacobian of variables
  REAL(kind=sp) :: JVS(LU_NONZERO)
! X - Vector for variables
  REAL(kind=sp) :: X(NVAR)

  X(29) = X(29)-JVS(108)*X(27)
  X(37) = X(37)-JVS(148)*X(22)-JVS(149)*X(26)
  X(45) = X(45)-JVS(180)*X(26)
  X(50) = X(50)-JVS(205)*X(38)
  X(51) = X(51)-JVS(213)*X(33)-JVS(214)*X(42)
  X(52) = X(52)-JVS(223)*X(24)
  X(53) = X(53)-JVS(231)*X(25)
  X(55) = X(55)-JVS(248)*X(37)
  X(56) = X(56)-JVS(254)*X(45)-JVS(255)*X(50)-JVS(256)*X(55)
  X(58) = X(58)-JVS(281)*X(32)-JVS(282)*X(52)-JVS(283)*X(57)
  X(61) = X(61)-JVS(308)*X(22)-JVS(309)*X(26)-JVS(310)*X(37)-JVS(311)*X(46)
  X(64) = X(64)-JVS(330)*X(63)
  X(66) = X(66)-JVS(346)*X(37)-JVS(347)*X(46)-JVS(348)*X(54)-JVS(349)*X(59)-JVS(350)*X(61)
  X(68) = X(68)-JVS(372)*X(38)-JVS(373)*X(39)-JVS(374)*X(40)-JVS(375)*X(41)-JVS(376)*X(47)-JVS(377)*X(63)
  X(69) = X(69)-JVS(393)*X(31)-JVS(394)*X(49)-JVS(395)*X(60)-JVS(396)*X(62)-JVS(397)*X(68)
  X(71) = X(71)-JVS(424)*X(39)-JVS(425)*X(54)-JVS(426)*X(59)-JVS(427)*X(64)-JVS(428)*X(70)
  X(72) = X(72)-JVS(440)*X(26)-JVS(441)*X(37)-JVS(442)*X(54)-JVS(443)*X(59)-JVS(444)*X(61)-JVS(445)*X(63)-JVS(446)*X(64)&
            &-JVS(447)*X(67)-JVS(448)*X(70)-JVS(449)*X(71)
  X(73) = X(73)-JVS(460)*X(41)-JVS(461)*X(44)-JVS(462)*X(54)-JVS(463)*X(55)-JVS(464)*X(59)-JVS(465)*X(61)-JVS(466)*X(62)&
            &-JVS(467)*X(63)-JVS(468)*X(64)-JVS(469)*X(66)-JVS(470)*X(67)-JVS(471)*X(70)-JVS(472)*X(71)-JVS(473)*X(72)
  X(74) = X(74)-JVS(485)*X(48)-JVS(486)*X(59)-JVS(487)*X(67)-JVS(488)*X(70)-JVS(489)*X(73)
  X(75) = X(75)-JVS(503)*X(28)-JVS(504)*X(35)-JVS(505)*X(45)-JVS(506)*X(55)-JVS(507)*X(61)-JVS(508)*X(67)-JVS(509)*X(70)&
            &-JVS(510)*X(74)
  X(76) = X(76)-JVS(525)*X(24)-JVS(526)*X(52)-JVS(527)*X(57)-JVS(528)*X(58)-JVS(529)*X(65)-JVS(530)*X(68)-JVS(531)*X(70)&
            &-JVS(532)*X(72)-JVS(533)*X(73)
  X(77) = X(77)-JVS(550)*X(29)-JVS(551)*X(52)-JVS(552)*X(57)-JVS(553)*X(58)-JVS(554)*X(60)-JVS(555)*X(65)-JVS(556)*X(68)&
            &-JVS(557)*X(70)-JVS(558)*X(72)-JVS(559)*X(73)-JVS(560)*X(76)
  X(78) = X(78)-JVS(576)*X(23)-JVS(577)*X(40)-JVS(578)*X(41)-JVS(579)*X(43)-JVS(580)*X(49)-JVS(581)*X(55)-JVS(582)*X(59)&
            &-JVS(583)*X(61)-JVS(584)*X(62)-JVS(585)*X(63)-JVS(586)*X(64)-JVS(587)*X(66)-JVS(588)*X(67)-JVS(589)*X(70)&
            &-JVS(590)*X(71)-JVS(591)*X(72)-JVS(592)*X(74)-JVS(593)*X(75)
  X(79) = X(79)-JVS(608)*X(22)-JVS(609)*X(23)-JVS(610)*X(26)-JVS(611)*X(38)-JVS(612)*X(39)-JVS(613)*X(41)-JVS(614)*X(43)&
            &-JVS(615)*X(44)-JVS(616)*X(45)-JVS(617)*X(48)-JVS(618)*X(49)-JVS(619)*X(54)-JVS(620)*X(55)-JVS(621)*X(59)&
            &-JVS(622)*X(61)-JVS(623)*X(62)-JVS(624)*X(63)-JVS(625)*X(64)-JVS(626)*X(67)-JVS(627)*X(70)-JVS(628)*X(71)&
            &-JVS(629)*X(72)-JVS(630)*X(74)-JVS(631)*X(75)-JVS(632)*X(78)
  X(80) = X(80)-JVS(646)*X(23)-JVS(647)*X(28)-JVS(648)*X(34)-JVS(649)*X(35)-JVS(650)*X(38)-JVS(651)*X(43)-JVS(652)*X(49)&
            &-JVS(653)*X(73)-JVS(654)*X(74)-JVS(655)*X(75)-JVS(656)*X(77)-JVS(657)*X(78)-JVS(658)*X(79)
  X(81) = X(81)-JVS(671)*X(27)-JVS(672)*X(29)-JVS(673)*X(47)-JVS(674)*X(51)-JVS(675)*X(57)-JVS(676)*X(58)-JVS(677)*X(59)&
            &-JVS(678)*X(60)-JVS(679)*X(62)-JVS(680)*X(63)-JVS(681)*X(64)-JVS(682)*X(65)-JVS(683)*X(68)-JVS(684)*X(69)&
            &-JVS(685)*X(70)-JVS(686)*X(72)-JVS(687)*X(73)-JVS(688)*X(76)-JVS(689)*X(77)-JVS(690)*X(78)-JVS(691)*X(79)&
            &-JVS(692)*X(80)
  X(82) = X(82)-JVS(704)*X(1)-JVS(705)*X(2)-JVS(706)*X(3)-JVS(707)*X(19)-JVS(708)*X(20)-JVS(709)*X(24)-JVS(710)*X(32)&
            &-JVS(711)*X(38)-JVS(712)*X(39)-JVS(713)*X(40)-JVS(714)*X(41)-JVS(715)*X(47)-JVS(716)*X(50)-JVS(717)*X(52)&
            &-JVS(718)*X(57)-JVS(719)*X(58)-JVS(720)*X(62)-JVS(721)*X(63)-JVS(722)*X(64)-JVS(723)*X(65)-JVS(724)*X(68)&
            &-JVS(725)*X(70)-JVS(726)*X(72)-JVS(727)*X(73)-JVS(728)*X(76)-JVS(729)*X(77)-JVS(730)*X(78)-JVS(731)*X(79)&
            &-JVS(732)*X(80)-JVS(733)*X(81)
  X(83) = X(83)-JVS(744)*X(19)-JVS(745)*X(22)-JVS(746)*X(23)-JVS(747)*X(26)-JVS(748)*X(30)-JVS(749)*X(31)-JVS(750)*X(32)&
            &-JVS(751)*X(33)-JVS(752)*X(34)-JVS(753)*X(35)-JVS(754)*X(36)-JVS(755)*X(38)-JVS(756)*X(39)-JVS(757)*X(40)&
            &-JVS(758)*X(41)-JVS(759)*X(42)-JVS(760)*X(43)-JVS(761)*X(44)-JVS(762)*X(45)-JVS(763)*X(47)-JVS(764)*X(48)&
            &-JVS(765)*X(49)-JVS(766)*X(50)-JVS(767)*X(51)-JVS(768)*X(52)-JVS(769)*X(53)-JVS(770)*X(55)-JVS(771)*X(56)&
            &-JVS(772)*X(57)-JVS(773)*X(58)-JVS(774)*X(59)-JVS(775)*X(60)-JVS(776)*X(61)-JVS(777)*X(62)-JVS(778)*X(63)&
            &-JVS(779)*X(64)-JVS(780)*X(65)-JVS(781)*X(66)-JVS(782)*X(67)-JVS(783)*X(68)-JVS(784)*X(69)-JVS(785)*X(70)&
            &-JVS(786)*X(71)-JVS(787)*X(72)-JVS(788)*X(73)-JVS(789)*X(74)-JVS(790)*X(75)-JVS(791)*X(76)-JVS(792)*X(77)&
            &-JVS(793)*X(78)-JVS(794)*X(79)-JVS(795)*X(80)-JVS(796)*X(81)-JVS(797)*X(82)
  X(84) = X(84)-JVS(807)*X(55)-JVS(808)*X(59)-JVS(809)*X(61)-JVS(810)*X(62)-JVS(811)*X(63)-JVS(812)*X(64)-JVS(813)*X(65)&
            &-JVS(814)*X(67)-JVS(815)*X(69)-JVS(816)*X(70)-JVS(817)*X(72)-JVS(818)*X(73)-JVS(819)*X(74)-JVS(820)*X(75)&
            &-JVS(821)*X(76)-JVS(822)*X(77)-JVS(823)*X(78)-JVS(824)*X(79)-JVS(825)*X(80)-JVS(826)*X(81)-JVS(827)*X(82)&
            &-JVS(828)*X(83)
  X(85) = X(85)-JVS(837)*X(22)-JVS(838)*X(26)-JVS(839)*X(36)-JVS(840)*X(37)-JVS(841)*X(38)-JVS(842)*X(39)-JVS(843)*X(40)&
            &-JVS(844)*X(41)-JVS(845)*X(43)-JVS(846)*X(44)-JVS(847)*X(45)-JVS(848)*X(46)-JVS(849)*X(47)-JVS(850)*X(48)&
            &-JVS(851)*X(49)-JVS(852)*X(50)-JVS(853)*X(54)-JVS(854)*X(55)-JVS(855)*X(56)-JVS(856)*X(59)-JVS(857)*X(61)&
            &-JVS(858)*X(62)-JVS(859)*X(63)-JVS(860)*X(64)-JVS(861)*X(66)-JVS(862)*X(67)-JVS(863)*X(69)-JVS(864)*X(70)&
            &-JVS(865)*X(71)-JVS(866)*X(72)-JVS(867)*X(73)-JVS(868)*X(74)-JVS(869)*X(75)-JVS(870)*X(76)-JVS(871)*X(77)&
            &-JVS(872)*X(78)-JVS(873)*X(79)-JVS(874)*X(80)-JVS(875)*X(81)-JVS(876)*X(82)-JVS(877)*X(83)-JVS(878)*X(84)
  X(86) = X(86)-JVS(886)*X(21)-JVS(887)*X(25)-JVS(888)*X(27)-JVS(889)*X(28)-JVS(890)*X(30)-JVS(891)*X(32)-JVS(892)*X(36)&
            &-JVS(893)*X(37)-JVS(894)*X(42)-JVS(895)*X(46)-JVS(896)*X(48)-JVS(897)*X(49)-JVS(898)*X(53)-JVS(899)*X(54)&
            &-JVS(900)*X(57)-JVS(901)*X(59)-JVS(902)*X(61)-JVS(903)*X(62)-JVS(904)*X(63)-JVS(905)*X(64)-JVS(906)*X(65)&
            &-JVS(907)*X(66)-JVS(908)*X(67)-JVS(909)*X(69)-JVS(910)*X(70)-JVS(911)*X(71)-JVS(912)*X(72)-JVS(913)*X(73)&
            &-JVS(914)*X(74)-JVS(915)*X(75)-JVS(916)*X(76)-JVS(917)*X(77)-JVS(918)*X(78)-JVS(919)*X(79)-JVS(920)*X(80)&
            &-JVS(921)*X(81)-JVS(922)*X(82)-JVS(923)*X(83)-JVS(924)*X(84)-JVS(925)*X(85)
  X(87) = X(87)-JVS(932)*X(39)-JVS(933)*X(41)-JVS(934)*X(44)-JVS(935)*X(48)-JVS(936)*X(54)-JVS(937)*X(63)-JVS(938)*X(64)&
            &-JVS(939)*X(66)-JVS(940)*X(67)-JVS(941)*X(70)-JVS(942)*X(71)-JVS(943)*X(72)-JVS(944)*X(74)-JVS(945)*X(75)&
            &-JVS(946)*X(79)-JVS(947)*X(80)-JVS(948)*X(81)-JVS(949)*X(82)-JVS(950)*X(83)-JVS(951)*X(84)-JVS(952)*X(85)&
            &-JVS(953)*X(86)
  X(88) = X(88)-JVS(959)*X(27)-JVS(960)*X(29)-JVS(961)*X(30)-JVS(962)*X(37)-JVS(963)*X(49)-JVS(964)*X(65)-JVS(965)*X(69)&
            &-JVS(966)*X(70)-JVS(967)*X(71)-JVS(968)*X(72)-JVS(969)*X(73)-JVS(970)*X(74)-JVS(971)*X(75)-JVS(972)*X(76)&
            &-JVS(973)*X(77)-JVS(974)*X(78)-JVS(975)*X(79)-JVS(976)*X(80)-JVS(977)*X(81)-JVS(978)*X(82)-JVS(979)*X(83)&
            &-JVS(980)*X(84)-JVS(981)*X(85)-JVS(982)*X(86)-JVS(983)*X(87)
  X(89) = X(89)-JVS(988)*X(42)-JVS(989)*X(51)-JVS(990)*X(60)-JVS(991)*X(65)-JVS(992)*X(73)-JVS(993)*X(75)-JVS(994)*X(76)&
            &-JVS(995)*X(77)-JVS(996)*X(78)-JVS(997)*X(79)-JVS(998)*X(80)-JVS(999)*X(81)-JVS(1000)*X(82)-JVS(1001)*X(83)&
            &-JVS(1002)*X(84)-JVS(1003)*X(85)-JVS(1004)*X(86)-JVS(1005)*X(87)-JVS(1006)*X(88)
  X(90) = X(90)-JVS(1010)*X(25)-JVS(1011)*X(28)-JVS(1012)*X(36)-JVS(1013)*X(42)-JVS(1014)*X(48)-JVS(1015)*X(53)&
            &-JVS(1016)*X(57)-JVS(1017)*X(59)-JVS(1018)*X(61)-JVS(1019)*X(62)-JVS(1020)*X(63)-JVS(1021)*X(64)-JVS(1022)&
            &*X(66)-JVS(1023)*X(67)-JVS(1024)*X(70)-JVS(1025)*X(71)-JVS(1026)*X(72)-JVS(1027)*X(73)-JVS(1028)*X(74)&
            &-JVS(1029)*X(75)-JVS(1030)*X(76)-JVS(1031)*X(77)-JVS(1032)*X(78)-JVS(1033)*X(79)-JVS(1034)*X(80)-JVS(1035)&
            &*X(81)-JVS(1036)*X(82)-JVS(1037)*X(83)-JVS(1038)*X(84)-JVS(1039)*X(85)-JVS(1040)*X(86)-JVS(1041)*X(87)&
            &-JVS(1042)*X(88)-JVS(1043)*X(89)
  X(91) = X(91)-JVS(1046)*X(20)-JVS(1047)*X(21)-JVS(1048)*X(23)-JVS(1049)*X(33)-JVS(1050)*X(42)-JVS(1051)*X(51)&
            &-JVS(1052)*X(60)-JVS(1053)*X(65)-JVS(1054)*X(73)-JVS(1055)*X(75)-JVS(1056)*X(76)-JVS(1057)*X(77)-JVS(1058)&
            &*X(78)-JVS(1059)*X(79)-JVS(1060)*X(80)-JVS(1061)*X(81)-JVS(1062)*X(82)-JVS(1063)*X(83)-JVS(1064)*X(84)&
            &-JVS(1065)*X(85)-JVS(1066)*X(86)-JVS(1067)*X(87)-JVS(1068)*X(88)-JVS(1069)*X(89)-JVS(1070)*X(90)
  X(91) = X(91)/JVS(1071)
  X(90) = (X(90)-JVS(1045)*X(91))/(JVS(1044))
  X(89) = (X(89)-JVS(1008)*X(90)-JVS(1009)*X(91))/(JVS(1007))
  X(88) = (X(88)-JVS(985)*X(89)-JVS(986)*X(90)-JVS(987)*X(91))/(JVS(984))
  X(87) = (X(87)-JVS(955)*X(88)-JVS(956)*X(89)-JVS(957)*X(90)-JVS(958)*X(91))/(JVS(954))
  X(86) = (X(86)-JVS(927)*X(87)-JVS(928)*X(88)-JVS(929)*X(89)-JVS(930)*X(90)-JVS(931)*X(91))/(JVS(926))
  X(85) = (X(85)-JVS(880)*X(86)-JVS(881)*X(87)-JVS(882)*X(88)-JVS(883)*X(89)-JVS(884)*X(90)-JVS(885)*X(91))/(JVS(879))
  X(84) = (X(84)-JVS(830)*X(85)-JVS(831)*X(86)-JVS(832)*X(87)-JVS(833)*X(88)-JVS(834)*X(89)-JVS(835)*X(90)-JVS(836)&
            &*X(91))/(JVS(829))
  X(83) = (X(83)-JVS(799)*X(84)-JVS(800)*X(85)-JVS(801)*X(86)-JVS(802)*X(87)-JVS(803)*X(88)-JVS(804)*X(89)-JVS(805)&
            &*X(90)-JVS(806)*X(91))/(JVS(798))
  X(82) = (X(82)-JVS(735)*X(83)-JVS(736)*X(84)-JVS(737)*X(85)-JVS(738)*X(86)-JVS(739)*X(87)-JVS(740)*X(88)-JVS(741)&
            &*X(89)-JVS(742)*X(90)-JVS(743)*X(91))/(JVS(734))
  X(81) = (X(81)-JVS(694)*X(82)-JVS(695)*X(83)-JVS(696)*X(84)-JVS(697)*X(85)-JVS(698)*X(86)-JVS(699)*X(87)-JVS(700)&
            &*X(88)-JVS(701)*X(89)-JVS(702)*X(90)-JVS(703)*X(91))/(JVS(693))
  X(80) = (X(80)-JVS(660)*X(81)-JVS(661)*X(82)-JVS(662)*X(83)-JVS(663)*X(84)-JVS(664)*X(85)-JVS(665)*X(86)-JVS(666)&
            &*X(87)-JVS(667)*X(88)-JVS(668)*X(89)-JVS(669)*X(90)-JVS(670)*X(91))/(JVS(659))
  X(79) = (X(79)-JVS(634)*X(80)-JVS(635)*X(81)-JVS(636)*X(82)-JVS(637)*X(83)-JVS(638)*X(84)-JVS(639)*X(85)-JVS(640)&
            &*X(86)-JVS(641)*X(87)-JVS(642)*X(88)-JVS(643)*X(89)-JVS(644)*X(90)-JVS(645)*X(91))/(JVS(633))
  X(78) = (X(78)-JVS(595)*X(79)-JVS(596)*X(80)-JVS(597)*X(81)-JVS(598)*X(82)-JVS(599)*X(83)-JVS(600)*X(84)-JVS(601)&
            &*X(85)-JVS(602)*X(86)-JVS(603)*X(87)-JVS(604)*X(88)-JVS(605)*X(89)-JVS(606)*X(90)-JVS(607)*X(91))/(JVS(594))
  X(77) = (X(77)-JVS(562)*X(78)-JVS(563)*X(79)-JVS(564)*X(80)-JVS(565)*X(81)-JVS(566)*X(82)-JVS(567)*X(83)-JVS(568)&
            &*X(84)-JVS(569)*X(85)-JVS(570)*X(86)-JVS(571)*X(87)-JVS(572)*X(88)-JVS(573)*X(89)-JVS(574)*X(90)-JVS(575)&
            &*X(91))/(JVS(561))
  X(76) = (X(76)-JVS(535)*X(77)-JVS(536)*X(78)-JVS(537)*X(79)-JVS(538)*X(80)-JVS(539)*X(81)-JVS(540)*X(82)-JVS(541)&
            &*X(83)-JVS(542)*X(84)-JVS(543)*X(85)-JVS(544)*X(86)-JVS(545)*X(87)-JVS(546)*X(88)-JVS(547)*X(89)-JVS(548)*X(90)&
            &-JVS(549)*X(91))/(JVS(534))
  X(75) = (X(75)-JVS(512)*X(79)-JVS(513)*X(80)-JVS(514)*X(81)-JVS(515)*X(82)-JVS(516)*X(83)-JVS(517)*X(84)-JVS(518)&
            &*X(85)-JVS(519)*X(86)-JVS(520)*X(87)-JVS(521)*X(88)-JVS(522)*X(89)-JVS(523)*X(90)-JVS(524)*X(91))/(JVS(511))
  X(74) = (X(74)-JVS(491)*X(75)-JVS(492)*X(79)-JVS(493)*X(80)-JVS(494)*X(81)-JVS(495)*X(82)-JVS(496)*X(83)-JVS(497)&
            &*X(84)-JVS(498)*X(85)-JVS(499)*X(86)-JVS(500)*X(88)-JVS(501)*X(90)-JVS(502)*X(91))/(JVS(490))
  X(73) = (X(73)-JVS(475)*X(79)-JVS(476)*X(81)-JVS(477)*X(82)-JVS(478)*X(83)-JVS(479)*X(84)-JVS(480)*X(85)-JVS(481)&
            &*X(86)-JVS(482)*X(88)-JVS(483)*X(90)-JVS(484)*X(91))/(JVS(474))
  X(72) = (X(72)-JVS(451)*X(79)-JVS(452)*X(81)-JVS(453)*X(82)-JVS(454)*X(83)-JVS(455)*X(84)-JVS(456)*X(85)-JVS(457)&
            &*X(86)-JVS(458)*X(88)-JVS(459)*X(90))/(JVS(450))
  X(71) = (X(71)-JVS(430)*X(72)-JVS(431)*X(79)-JVS(432)*X(81)-JVS(433)*X(82)-JVS(434)*X(83)-JVS(435)*X(84)-JVS(436)&
            &*X(85)-JVS(437)*X(86)-JVS(438)*X(88)-JVS(439)*X(90))/(JVS(429))
  X(70) = (X(70)-JVS(418)*X(81)-JVS(419)*X(82)-JVS(420)*X(83)-JVS(421)*X(84)-JVS(422)*X(86)-JVS(423)*X(90))/(JVS(417))
  X(69) = (X(69)-JVS(399)*X(70)-JVS(400)*X(72)-JVS(401)*X(73)-JVS(402)*X(76)-JVS(403)*X(77)-JVS(404)*X(78)-JVS(405)&
            &*X(80)-JVS(406)*X(81)-JVS(407)*X(82)-JVS(408)*X(83)-JVS(409)*X(84)-JVS(410)*X(85)-JVS(411)*X(86)-JVS(412)*X(87)&
            &-JVS(413)*X(88)-JVS(414)*X(89)-JVS(415)*X(90)-JVS(416)*X(91))/(JVS(398))
  X(68) = (X(68)-JVS(379)*X(70)-JVS(380)*X(72)-JVS(381)*X(73)-JVS(382)*X(76)-JVS(383)*X(77)-JVS(384)*X(78)-JVS(385)&
            &*X(80)-JVS(386)*X(81)-JVS(387)*X(82)-JVS(388)*X(83)-JVS(389)*X(84)-JVS(390)*X(85)-JVS(391)*X(87)-JVS(392)&
            &*X(90))/(JVS(378))
  X(67) = (X(67)-JVS(365)*X(70)-JVS(366)*X(81)-JVS(367)*X(82)-JVS(368)*X(83)-JVS(369)*X(84)-JVS(370)*X(86)-JVS(371)&
            &*X(90))/(JVS(364))
  X(66) = (X(66)-JVS(352)*X(67)-JVS(353)*X(70)-JVS(354)*X(71)-JVS(355)*X(72)-JVS(356)*X(81)-JVS(357)*X(82)-JVS(358)&
            &*X(83)-JVS(359)*X(84)-JVS(360)*X(85)-JVS(361)*X(86)-JVS(362)*X(88)-JVS(363)*X(90))/(JVS(351))
  X(65) = (X(65)-JVS(338)*X(76)-JVS(339)*X(81)-JVS(340)*X(82)-JVS(341)*X(83)-JVS(342)*X(84)-JVS(343)*X(88)-JVS(344)&
            &*X(89)-JVS(345)*X(91))/(JVS(337))
  X(64) = (X(64)-JVS(332)*X(81)-JVS(333)*X(82)-JVS(334)*X(83)-JVS(335)*X(84)-JVS(336)*X(90))/(JVS(331))
  X(63) = (X(63)-JVS(325)*X(81)-JVS(326)*X(82)-JVS(327)*X(83)-JVS(328)*X(84)-JVS(329)*X(90))/(JVS(324))
  X(62) = (X(62)-JVS(319)*X(81)-JVS(320)*X(82)-JVS(321)*X(83)-JVS(322)*X(84)-JVS(323)*X(90))/(JVS(318))
  X(61) = (X(61)-JVS(313)*X(83)-JVS(314)*X(85)-JVS(315)*X(86)-JVS(316)*X(88)-JVS(317)*X(90))/(JVS(312))
  X(60) = (X(60)-JVS(299)*X(73)-JVS(300)*X(77)-JVS(301)*X(78)-JVS(302)*X(81)-JVS(303)*X(83)-JVS(304)*X(85)-JVS(305)&
            &*X(87)-JVS(306)*X(89)-JVS(307)*X(91))/(JVS(298))
  X(59) = (X(59)-JVS(294)*X(81)-JVS(295)*X(83)-JVS(296)*X(84)-JVS(297)*X(90))/(JVS(293))
  X(58) = (X(58)-JVS(285)*X(65)-JVS(286)*X(76)-JVS(287)*X(77)-JVS(288)*X(81)-JVS(289)*X(82)-JVS(290)*X(83)-JVS(291)&
            &*X(85)-JVS(292)*X(86))/(JVS(284))
  X(57) = (X(57)-JVS(276)*X(76)-JVS(277)*X(81)-JVS(278)*X(82)-JVS(279)*X(83)-JVS(280)*X(86))/(JVS(275))
  X(56) = (X(56)-JVS(258)*X(59)-JVS(259)*X(61)-JVS(260)*X(62)-JVS(261)*X(63)-JVS(262)*X(64)-JVS(263)*X(67)-JVS(264)&
            &*X(70)-JVS(265)*X(73)-JVS(266)*X(78)-JVS(267)*X(81)-JVS(268)*X(82)-JVS(269)*X(83)-JVS(270)*X(84)-JVS(271)*X(87)&
            &-JVS(272)*X(88)-JVS(273)*X(90)-JVS(274)*X(91))/(JVS(257))
  X(55) = (X(55)-JVS(250)*X(61)-JVS(251)*X(83)-JVS(252)*X(84)-JVS(253)*X(88))/(JVS(249))
  X(54) = (X(54)-JVS(244)*X(72)-JVS(245)*X(82)-JVS(246)*X(83)-JVS(247)*X(86))/(JVS(243))
  X(53) = (X(53)-JVS(233)*X(61)-JVS(234)*X(66)-JVS(235)*X(67)-JVS(236)*X(73)-JVS(237)*X(78)-JVS(238)*X(83)-JVS(239)&
            &*X(85)-JVS(240)*X(86)-JVS(241)*X(87)-JVS(242)*X(90))/(JVS(232))
  X(52) = (X(52)-JVS(225)*X(57)-JVS(226)*X(58)-JVS(227)*X(76)-JVS(228)*X(77)-JVS(229)*X(82)-JVS(230)*X(83))/(JVS(224))
  X(51) = (X(51)-JVS(216)*X(80)-JVS(217)*X(81)-JVS(218)*X(83)-JVS(219)*X(85)-JVS(220)*X(86)-JVS(221)*X(89)-JVS(222)&
            &*X(91))/(JVS(215))
  X(50) = (X(50)-JVS(207)*X(62)-JVS(208)*X(63)-JVS(209)*X(64)-JVS(210)*X(70)-JVS(211)*X(82)-JVS(212)*X(83))/(JVS(206))
  X(49) = (X(49)-JVS(202)*X(78)-JVS(203)*X(85)-JVS(204)*X(88))/(JVS(201))
  X(48) = (X(48)-JVS(198)*X(74)-JVS(199)*X(83)-JVS(200)*X(86))/(JVS(197))
  X(47) = (X(47)-JVS(193)*X(81)-JVS(194)*X(82)-JVS(195)*X(83)-JVS(196)*X(85))/(JVS(192))
  X(46) = (X(46)-JVS(187)*X(61)-JVS(188)*X(83)-JVS(189)*X(85)-JVS(190)*X(86)-JVS(191)*X(90))/(JVS(186))
  X(45) = (X(45)-JVS(182)*X(55)-JVS(183)*X(67)-JVS(184)*X(83)-JVS(185)*X(84))/(JVS(181))
  X(44) = (X(44)-JVS(176)*X(71)-JVS(177)*X(79)-JVS(178)*X(83)-JVS(179)*X(85))/(JVS(175))
  X(43) = (X(43)-JVS(171)*X(49)-JVS(172)*X(80)-JVS(173)*X(83)-JVS(174)*X(85))/(JVS(170))
  X(42) = (X(42)-JVS(167)*X(86)-JVS(168)*X(89)-JVS(169)*X(91))/(JVS(166))
  X(41) = (X(41)-JVS(164)*X(82)-JVS(165)*X(83))/(JVS(163))
  X(40) = (X(40)-JVS(160)*X(80)-JVS(161)*X(82)-JVS(162)*X(83))/(JVS(159))
  X(39) = (X(39)-JVS(157)*X(82)-JVS(158)*X(83))/(JVS(156))
  X(38) = (X(38)-JVS(154)*X(82)-JVS(155)*X(83))/(JVS(153))
  X(37) = (X(37)-JVS(151)*X(83)-JVS(152)*X(88))/(JVS(150))
  X(36) = (X(36)-JVS(145)*X(83)-JVS(146)*X(85)-JVS(147)*X(86))/(JVS(144))
  X(35) = (X(35)-JVS(140)*X(74)-JVS(141)*X(75)-JVS(142)*X(83)-JVS(143)*X(85))/(JVS(139))
  X(34) = (X(34)-JVS(133)*X(74)-JVS(134)*X(75)-JVS(135)*X(79)-JVS(136)*X(80)-JVS(137)*X(83)-JVS(138)*X(85))/(JVS(132))
  X(33) = (X(33)-JVS(128)*X(42)-JVS(129)*X(83)-JVS(130)*X(89)-JVS(131)*X(91))/(JVS(127))
  X(32) = (X(32)-JVS(124)*X(82)-JVS(125)*X(83)-JVS(126)*X(86))/(JVS(123))
  X(31) = (X(31)-JVS(118)*X(49)-JVS(119)*X(62)-JVS(120)*X(83)-JVS(121)*X(84)-JVS(122)*X(88))/(JVS(117))
  X(30) = (X(30)-JVS(114)*X(83)-JVS(115)*X(86)-JVS(116)*X(88))/(JVS(113))
  X(29) = (X(29)-JVS(110)*X(77)-JVS(111)*X(86)-JVS(112)*X(88))/(JVS(109))
  X(28) = (X(28)-JVS(106)*X(75)-JVS(107)*X(86))/(JVS(105))
  X(27) = (X(27)-JVS(103)*X(86)-JVS(104)*X(88))/(JVS(102))
  X(26) = (X(26)-JVS(101)*X(83))/(JVS(100))
  X(25) = (X(25)-JVS(98)*X(86)-JVS(99)*X(90))/(JVS(97))
  X(24) = (X(24)-JVS(95)*X(76)-JVS(96)*X(82))/(JVS(94))
  X(23) = (X(23)-JVS(93)*X(83))/(JVS(92))
  X(22) = (X(22)-JVS(91)*X(83))/(JVS(90))
  X(21) = (X(21)-JVS(88)*X(86)-JVS(89)*X(91))/(JVS(87))
  X(20) = (X(20)-JVS(85)*X(76)-JVS(86)*X(89))/(JVS(84))
  X(19) = (X(19)-JVS(83)*X(83))/(JVS(82))
  X(18) = (X(18)-JVS(79)*X(83)-JVS(80)*X(84)-JVS(81)*X(90))/(JVS(78))
  X(17) = (X(17)-JVS(72)*X(18)-JVS(73)*X(59)-JVS(74)*X(81)-JVS(75)*X(83)-JVS(76)*X(84)-JVS(77)*X(90))/(JVS(71))
  X(16) = (X(16)-JVS(63)*X(17)-JVS(64)*X(18)-JVS(65)*X(59)-JVS(66)*X(70)-JVS(67)*X(81)-JVS(68)*X(83)-JVS(69)*X(84)&
            &-JVS(70)*X(90))/(JVS(62))
  X(15) = (X(15)-JVS(54)*X(16)-JVS(55)*X(18)-JVS(56)*X(59)-JVS(57)*X(70)-JVS(58)*X(81)-JVS(59)*X(83)-JVS(60)*X(84)&
            &-JVS(61)*X(90))/(JVS(53))
  X(14) = (X(14)-JVS(45)*X(15)-JVS(46)*X(18)-JVS(47)*X(59)-JVS(48)*X(70)-JVS(49)*X(81)-JVS(50)*X(83)-JVS(51)*X(84)&
            &-JVS(52)*X(90))/(JVS(44))
  X(13) = (X(13)-JVS(42)*X(14)-JVS(43)*X(83))/(JVS(41))
  X(12) = (X(12)-JVS(40)*X(83))/(JVS(39))
  X(11) = (X(11)-JVS(37)*X(12)-JVS(38)*X(83))/(JVS(36))
  X(10) = (X(10)-JVS(34)*X(11)-JVS(35)*X(83))/(JVS(33))
  X(9) = (X(9)-JVS(32)*X(83))/(JVS(31))
  X(8) = (X(8)-JVS(26)*X(9)-JVS(27)*X(10)-JVS(28)*X(22)-JVS(29)*X(26)-JVS(30)*X(83))/(JVS(25))
  X(7) = (X(7)-JVS(20)*X(8)-JVS(21)*X(9)-JVS(22)*X(22)-JVS(23)*X(26)-JVS(24)*X(83))/(JVS(19))
  X(6) = (X(6)-JVS(14)*X(7)-JVS(15)*X(9)-JVS(16)*X(22)-JVS(17)*X(26)-JVS(18)*X(83))/(JVS(13))
  X(5) = (X(5)-JVS(8)*X(6)-JVS(9)*X(9)-JVS(10)*X(22)-JVS(11)*X(26)-JVS(12)*X(83))/(JVS(7))
  X(4) = (X(4)-JVS(5)*X(5)-JVS(6)*X(83))/(JVS(4))
  X(3) = X(3)/JVS(3)
  X(2) = X(2)/JVS(2)
  X(1) = X(1)/JVS(1)
      
END SUBROUTINE KppSolve

! End of KppSolve function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! KppSolveTR - sparse, transposed back substitution
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      X         - Vector for variables
!      XX        - Vector for output variables
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE KppSolveTR ( JVS, X, XX )

! JVS - sparse Jacobian of variables
  REAL(kind=sp) :: JVS(LU_NONZERO)
! X - Vector for variables
  REAL(kind=sp) :: X(NVAR)
! XX - Vector for output variables
  REAL(kind=sp) :: XX(NVAR)

  XX(1) = X(1)/JVS(1)
  XX(2) = X(2)/JVS(2)
  XX(3) = X(3)/JVS(3)
  XX(4) = X(4)/JVS(4)
  XX(5) = (X(5)-JVS(5)*XX(4))/(JVS(7))
  XX(6) = (X(6)-JVS(8)*XX(5))/(JVS(13))
  XX(7) = (X(7)-JVS(14)*XX(6))/(JVS(19))
  XX(8) = (X(8)-JVS(20)*XX(7))/(JVS(25))
  XX(9) = (X(9)-JVS(9)*XX(5)-JVS(15)*XX(6)-JVS(21)*XX(7)-JVS(26)*XX(8))/(JVS(31))
  XX(10) = (X(10)-JVS(27)*XX(8))/(JVS(33))
  XX(11) = (X(11)-JVS(34)*XX(10))/(JVS(36))
  XX(12) = (X(12)-JVS(37)*XX(11))/(JVS(39))
  XX(13) = X(13)/JVS(41)
  XX(14) = (X(14)-JVS(42)*XX(13))/(JVS(44))
  XX(15) = (X(15)-JVS(45)*XX(14))/(JVS(53))
  XX(16) = (X(16)-JVS(54)*XX(15))/(JVS(62))
  XX(17) = (X(17)-JVS(63)*XX(16))/(JVS(71))
  XX(18) = (X(18)-JVS(46)*XX(14)-JVS(55)*XX(15)-JVS(64)*XX(16)-JVS(72)*XX(17))/(JVS(78))
  XX(19) = X(19)/JVS(82)
  XX(20) = X(20)/JVS(84)
  XX(21) = X(21)/JVS(87)
  XX(22) = (X(22)-JVS(10)*XX(5)-JVS(16)*XX(6)-JVS(22)*XX(7)-JVS(28)*XX(8))/(JVS(90))
  XX(23) = X(23)/JVS(92)
  XX(24) = X(24)/JVS(94)
  XX(25) = X(25)/JVS(97)
  XX(26) = (X(26)-JVS(11)*XX(5)-JVS(17)*XX(6)-JVS(23)*XX(7)-JVS(29)*XX(8))/(JVS(100))
  XX(27) = X(27)/JVS(102)
  XX(28) = X(28)/JVS(105)
  XX(29) = X(29)/JVS(109)
  XX(30) = X(30)/JVS(113)
  XX(31) = X(31)/JVS(117)
  XX(32) = X(32)/JVS(123)
  XX(33) = X(33)/JVS(127)
  XX(34) = X(34)/JVS(132)
  XX(35) = X(35)/JVS(139)
  XX(36) = X(36)/JVS(144)
  XX(37) = X(37)/JVS(150)
  XX(38) = X(38)/JVS(153)
  XX(39) = X(39)/JVS(156)
  XX(40) = X(40)/JVS(159)
  XX(41) = X(41)/JVS(163)
  XX(42) = (X(42)-JVS(128)*XX(33))/(JVS(166))
  XX(43) = X(43)/JVS(170)
  XX(44) = X(44)/JVS(175)
  XX(45) = X(45)/JVS(181)
  XX(46) = X(46)/JVS(186)
  XX(47) = X(47)/JVS(192)
  XX(48) = X(48)/JVS(197)
  XX(49) = (X(49)-JVS(118)*XX(31)-JVS(171)*XX(43))/(JVS(201))
  XX(50) = X(50)/JVS(206)
  XX(51) = X(51)/JVS(215)
  XX(52) = X(52)/JVS(224)
  XX(53) = X(53)/JVS(232)
  XX(54) = X(54)/JVS(243)
  XX(55) = (X(55)-JVS(182)*XX(45))/(JVS(249))
  XX(56) = X(56)/JVS(257)
  XX(57) = (X(57)-JVS(225)*XX(52))/(JVS(275))
  XX(58) = (X(58)-JVS(226)*XX(52))/(JVS(284))
  XX(59) = (X(59)-JVS(47)*XX(14)-JVS(56)*XX(15)-JVS(65)*XX(16)-JVS(73)*XX(17)-JVS(258)*XX(56))/(JVS(293))
  XX(60) = X(60)/JVS(298)
  XX(61) = (X(61)-JVS(187)*XX(46)-JVS(233)*XX(53)-JVS(250)*XX(55)-JVS(259)*XX(56))/(JVS(312))
  XX(62) = (X(62)-JVS(119)*XX(31)-JVS(207)*XX(50)-JVS(260)*XX(56))/(JVS(318))
  XX(63) = (X(63)-JVS(208)*XX(50)-JVS(261)*XX(56))/(JVS(324))
  XX(64) = (X(64)-JVS(209)*XX(50)-JVS(262)*XX(56))/(JVS(331))
  XX(65) = (X(65)-JVS(285)*XX(58))/(JVS(337))
  XX(66) = (X(66)-JVS(234)*XX(53))/(JVS(351))
  XX(67) = (X(67)-JVS(183)*XX(45)-JVS(235)*XX(53)-JVS(263)*XX(56)-JVS(352)*XX(66))/(JVS(364))
  XX(68) = X(68)/JVS(378)
  XX(69) = X(69)/JVS(398)
  XX(70) = (X(70)-JVS(48)*XX(14)-JVS(57)*XX(15)-JVS(66)*XX(16)-JVS(210)*XX(50)-JVS(264)*XX(56)-JVS(353)*XX(66)-JVS(365)&
             &*XX(67)-JVS(379)*XX(68)-JVS(399)*XX(69))/(JVS(417))
  XX(71) = (X(71)-JVS(176)*XX(44)-JVS(354)*XX(66))/(JVS(429))
  XX(72) = (X(72)-JVS(244)*XX(54)-JVS(355)*XX(66)-JVS(380)*XX(68)-JVS(400)*XX(69)-JVS(430)*XX(71))/(JVS(450))
  XX(73) = (X(73)-JVS(236)*XX(53)-JVS(265)*XX(56)-JVS(299)*XX(60)-JVS(381)*XX(68)-JVS(401)*XX(69))/(JVS(474))
  XX(74) = (X(74)-JVS(133)*XX(34)-JVS(140)*XX(35)-JVS(198)*XX(48))/(JVS(490))
  XX(75) = (X(75)-JVS(106)*XX(28)-JVS(134)*XX(34)-JVS(141)*XX(35)-JVS(491)*XX(74))/(JVS(511))
  XX(76) = (X(76)-JVS(85)*XX(20)-JVS(95)*XX(24)-JVS(227)*XX(52)-JVS(276)*XX(57)-JVS(286)*XX(58)-JVS(338)*XX(65)-JVS(382)&
             &*XX(68)-JVS(402)*XX(69))/(JVS(534))
  XX(77) = (X(77)-JVS(110)*XX(29)-JVS(228)*XX(52)-JVS(287)*XX(58)-JVS(300)*XX(60)-JVS(383)*XX(68)-JVS(403)*XX(69)&
             &-JVS(535)*XX(76))/(JVS(561))
  XX(78) = (X(78)-JVS(202)*XX(49)-JVS(237)*XX(53)-JVS(266)*XX(56)-JVS(301)*XX(60)-JVS(384)*XX(68)-JVS(404)*XX(69)&
             &-JVS(536)*XX(76)-JVS(562)*XX(77))/(JVS(594))
  XX(79) = (X(79)-JVS(135)*XX(34)-JVS(177)*XX(44)-JVS(431)*XX(71)-JVS(451)*XX(72)-JVS(475)*XX(73)-JVS(492)*XX(74)&
             &-JVS(512)*XX(75)-JVS(537)*XX(76)-JVS(563)*XX(77)-JVS(595)*XX(78))/(JVS(633))
  XX(80) = (X(80)-JVS(136)*XX(34)-JVS(160)*XX(40)-JVS(172)*XX(43)-JVS(216)*XX(51)-JVS(385)*XX(68)-JVS(405)*XX(69)&
             &-JVS(493)*XX(74)-JVS(513)*XX(75)-JVS(538)*XX(76)-JVS(564)*XX(77)-JVS(596)*XX(78)-JVS(634)*XX(79))/(JVS(659))
  XX(81) = (X(81)-JVS(49)*XX(14)-JVS(58)*XX(15)-JVS(67)*XX(16)-JVS(74)*XX(17)-JVS(193)*XX(47)-JVS(217)*XX(51)-JVS(267)&
             &*XX(56)-JVS(277)*XX(57)-JVS(288)*XX(58)-JVS(294)*XX(59)-JVS(302)*XX(60)-JVS(319)*XX(62)-JVS(325)*XX(63)&
             &-JVS(332)*XX(64)-JVS(339)*XX(65)-JVS(356)*XX(66)-JVS(366)*XX(67)-JVS(386)*XX(68)-JVS(406)*XX(69)-JVS(418)&
             &*XX(70)-JVS(432)*XX(71)-JVS(452)*XX(72)-JVS(476)*XX(73)-JVS(494)*XX(74)-JVS(514)*XX(75)-JVS(539)*XX(76)&
             &-JVS(565)*XX(77)-JVS(597)*XX(78)-JVS(635)*XX(79)-JVS(660)*XX(80))/(JVS(693))
  XX(82) = (X(82)-JVS(96)*XX(24)-JVS(124)*XX(32)-JVS(154)*XX(38)-JVS(157)*XX(39)-JVS(161)*XX(40)-JVS(164)*XX(41)&
             &-JVS(194)*XX(47)-JVS(211)*XX(50)-JVS(229)*XX(52)-JVS(245)*XX(54)-JVS(268)*XX(56)-JVS(278)*XX(57)-JVS(289)&
             &*XX(58)-JVS(320)*XX(62)-JVS(326)*XX(63)-JVS(333)*XX(64)-JVS(340)*XX(65)-JVS(357)*XX(66)-JVS(367)*XX(67)&
             &-JVS(387)*XX(68)-JVS(407)*XX(69)-JVS(419)*XX(70)-JVS(433)*XX(71)-JVS(453)*XX(72)-JVS(477)*XX(73)-JVS(495)&
             &*XX(74)-JVS(515)*XX(75)-JVS(540)*XX(76)-JVS(566)*XX(77)-JVS(598)*XX(78)-JVS(636)*XX(79)-JVS(661)*XX(80)&
             &-JVS(694)*XX(81))/(JVS(734))
  XX(83) = (X(83)-JVS(6)*XX(4)-JVS(12)*XX(5)-JVS(18)*XX(6)-JVS(24)*XX(7)-JVS(30)*XX(8)-JVS(32)*XX(9)-JVS(35)*XX(10)&
             &-JVS(38)*XX(11)-JVS(40)*XX(12)-JVS(43)*XX(13)-JVS(50)*XX(14)-JVS(59)*XX(15)-JVS(68)*XX(16)-JVS(75)*XX(17)&
             &-JVS(79)*XX(18)-JVS(83)*XX(19)-JVS(91)*XX(22)-JVS(93)*XX(23)-JVS(101)*XX(26)-JVS(114)*XX(30)-JVS(120)*XX(31)&
             &-JVS(125)*XX(32)-JVS(129)*XX(33)-JVS(137)*XX(34)-JVS(142)*XX(35)-JVS(145)*XX(36)-JVS(151)*XX(37)-JVS(155)&
             &*XX(38)-JVS(158)*XX(39)-JVS(162)*XX(40)-JVS(165)*XX(41)-JVS(173)*XX(43)-JVS(178)*XX(44)-JVS(184)*XX(45)&
             &-JVS(188)*XX(46)-JVS(195)*XX(47)-JVS(199)*XX(48)-JVS(212)*XX(50)-JVS(218)*XX(51)-JVS(230)*XX(52)-JVS(238)&
             &*XX(53)-JVS(246)*XX(54)-JVS(251)*XX(55)-JVS(269)*XX(56)-JVS(279)*XX(57)-JVS(290)*XX(58)-JVS(295)*XX(59)&
             &-JVS(303)*XX(60)-JVS(313)*XX(61)-JVS(321)*XX(62)-JVS(327)*XX(63)-JVS(334)*XX(64)-JVS(341)*XX(65)-JVS(358)&
             &*XX(66)-JVS(368)*XX(67)-JVS(388)*XX(68)-JVS(408)*XX(69)-JVS(420)*XX(70)-JVS(434)*XX(71)-JVS(454)*XX(72)&
             &-JVS(478)*XX(73)-JVS(496)*XX(74)-JVS(516)*XX(75)-JVS(541)*XX(76)-JVS(567)*XX(77)-JVS(599)*XX(78)-JVS(637)&
             &*XX(79)-JVS(662)*XX(80)-JVS(695)*XX(81)-JVS(735)*XX(82))/(JVS(798))
  XX(84) = (X(84)-JVS(51)*XX(14)-JVS(60)*XX(15)-JVS(69)*XX(16)-JVS(76)*XX(17)-JVS(80)*XX(18)-JVS(121)*XX(31)-JVS(185)&
             &*XX(45)-JVS(252)*XX(55)-JVS(270)*XX(56)-JVS(296)*XX(59)-JVS(322)*XX(62)-JVS(328)*XX(63)-JVS(335)*XX(64)&
             &-JVS(342)*XX(65)-JVS(359)*XX(66)-JVS(369)*XX(67)-JVS(389)*XX(68)-JVS(409)*XX(69)-JVS(421)*XX(70)-JVS(435)&
             &*XX(71)-JVS(455)*XX(72)-JVS(479)*XX(73)-JVS(497)*XX(74)-JVS(517)*XX(75)-JVS(542)*XX(76)-JVS(568)*XX(77)&
             &-JVS(600)*XX(78)-JVS(638)*XX(79)-JVS(663)*XX(80)-JVS(696)*XX(81)-JVS(736)*XX(82)-JVS(799)*XX(83))/(JVS(829))
  XX(85) = (X(85)-JVS(138)*XX(34)-JVS(143)*XX(35)-JVS(146)*XX(36)-JVS(174)*XX(43)-JVS(179)*XX(44)-JVS(189)*XX(46)&
             &-JVS(196)*XX(47)-JVS(203)*XX(49)-JVS(219)*XX(51)-JVS(239)*XX(53)-JVS(291)*XX(58)-JVS(304)*XX(60)-JVS(314)&
             &*XX(61)-JVS(360)*XX(66)-JVS(390)*XX(68)-JVS(410)*XX(69)-JVS(436)*XX(71)-JVS(456)*XX(72)-JVS(480)*XX(73)&
             &-JVS(498)*XX(74)-JVS(518)*XX(75)-JVS(543)*XX(76)-JVS(569)*XX(77)-JVS(601)*XX(78)-JVS(639)*XX(79)-JVS(664)&
             &*XX(80)-JVS(697)*XX(81)-JVS(737)*XX(82)-JVS(800)*XX(83)-JVS(830)*XX(84))/(JVS(879))
  XX(86) = (X(86)-JVS(88)*XX(21)-JVS(98)*XX(25)-JVS(103)*XX(27)-JVS(107)*XX(28)-JVS(111)*XX(29)-JVS(115)*XX(30)-JVS(126)&
             &*XX(32)-JVS(147)*XX(36)-JVS(167)*XX(42)-JVS(190)*XX(46)-JVS(200)*XX(48)-JVS(220)*XX(51)-JVS(240)*XX(53)&
             &-JVS(247)*XX(54)-JVS(280)*XX(57)-JVS(292)*XX(58)-JVS(315)*XX(61)-JVS(361)*XX(66)-JVS(370)*XX(67)-JVS(411)&
             &*XX(69)-JVS(422)*XX(70)-JVS(437)*XX(71)-JVS(457)*XX(72)-JVS(481)*XX(73)-JVS(499)*XX(74)-JVS(519)*XX(75)&
             &-JVS(544)*XX(76)-JVS(570)*XX(77)-JVS(602)*XX(78)-JVS(640)*XX(79)-JVS(665)*XX(80)-JVS(698)*XX(81)-JVS(738)&
             &*XX(82)-JVS(801)*XX(83)-JVS(831)*XX(84)-JVS(880)*XX(85))/(JVS(926))
  XX(87) = (X(87)-JVS(241)*XX(53)-JVS(271)*XX(56)-JVS(305)*XX(60)-JVS(391)*XX(68)-JVS(412)*XX(69)-JVS(520)*XX(75)&
             &-JVS(545)*XX(76)-JVS(571)*XX(77)-JVS(603)*XX(78)-JVS(641)*XX(79)-JVS(666)*XX(80)-JVS(699)*XX(81)-JVS(739)&
             &*XX(82)-JVS(802)*XX(83)-JVS(832)*XX(84)-JVS(881)*XX(85)-JVS(927)*XX(86))/(JVS(954))
  XX(88) = (X(88)-JVS(104)*XX(27)-JVS(112)*XX(29)-JVS(116)*XX(30)-JVS(122)*XX(31)-JVS(152)*XX(37)-JVS(204)*XX(49)&
             &-JVS(253)*XX(55)-JVS(272)*XX(56)-JVS(316)*XX(61)-JVS(343)*XX(65)-JVS(362)*XX(66)-JVS(413)*XX(69)-JVS(438)&
             &*XX(71)-JVS(458)*XX(72)-JVS(482)*XX(73)-JVS(500)*XX(74)-JVS(521)*XX(75)-JVS(546)*XX(76)-JVS(572)*XX(77)&
             &-JVS(604)*XX(78)-JVS(642)*XX(79)-JVS(667)*XX(80)-JVS(700)*XX(81)-JVS(740)*XX(82)-JVS(803)*XX(83)-JVS(833)&
             &*XX(84)-JVS(882)*XX(85)-JVS(928)*XX(86)-JVS(955)*XX(87))/(JVS(984))
  XX(89) = (X(89)-JVS(86)*XX(20)-JVS(130)*XX(33)-JVS(168)*XX(42)-JVS(221)*XX(51)-JVS(306)*XX(60)-JVS(344)*XX(65)&
             &-JVS(414)*XX(69)-JVS(522)*XX(75)-JVS(547)*XX(76)-JVS(573)*XX(77)-JVS(605)*XX(78)-JVS(643)*XX(79)-JVS(668)&
             &*XX(80)-JVS(701)*XX(81)-JVS(741)*XX(82)-JVS(804)*XX(83)-JVS(834)*XX(84)-JVS(883)*XX(85)-JVS(929)*XX(86)&
             &-JVS(956)*XX(87)-JVS(985)*XX(88))/(JVS(1007))
  XX(90) = (X(90)-JVS(52)*XX(14)-JVS(61)*XX(15)-JVS(70)*XX(16)-JVS(77)*XX(17)-JVS(81)*XX(18)-JVS(99)*XX(25)-JVS(191)&
             &*XX(46)-JVS(242)*XX(53)-JVS(273)*XX(56)-JVS(297)*XX(59)-JVS(317)*XX(61)-JVS(323)*XX(62)-JVS(329)*XX(63)&
             &-JVS(336)*XX(64)-JVS(363)*XX(66)-JVS(371)*XX(67)-JVS(392)*XX(68)-JVS(415)*XX(69)-JVS(423)*XX(70)-JVS(439)&
             &*XX(71)-JVS(459)*XX(72)-JVS(483)*XX(73)-JVS(501)*XX(74)-JVS(523)*XX(75)-JVS(548)*XX(76)-JVS(574)*XX(77)&
             &-JVS(606)*XX(78)-JVS(644)*XX(79)-JVS(669)*XX(80)-JVS(702)*XX(81)-JVS(742)*XX(82)-JVS(805)*XX(83)-JVS(835)&
             &*XX(84)-JVS(884)*XX(85)-JVS(930)*XX(86)-JVS(957)*XX(87)-JVS(986)*XX(88)-JVS(1008)*XX(89))/(JVS(1044))
  XX(91) = (X(91)-JVS(89)*XX(21)-JVS(131)*XX(33)-JVS(169)*XX(42)-JVS(222)*XX(51)-JVS(274)*XX(56)-JVS(307)*XX(60)&
             &-JVS(345)*XX(65)-JVS(416)*XX(69)-JVS(484)*XX(73)-JVS(502)*XX(74)-JVS(524)*XX(75)-JVS(549)*XX(76)-JVS(575)&
             &*XX(77)-JVS(607)*XX(78)-JVS(645)*XX(79)-JVS(670)*XX(80)-JVS(703)*XX(81)-JVS(743)*XX(82)-JVS(806)*XX(83)&
             &-JVS(836)*XX(84)-JVS(885)*XX(85)-JVS(931)*XX(86)-JVS(958)*XX(87)-JVS(987)*XX(88)-JVS(1009)*XX(89)-JVS(1045)&
             &*XX(90))/(JVS(1071))
  XX(91) = XX(91)
  XX(90) = XX(90)-JVS(1070)*XX(91)
  XX(89) = XX(89)-JVS(1043)*XX(90)-JVS(1069)*XX(91)
  XX(88) = XX(88)-JVS(1006)*XX(89)-JVS(1042)*XX(90)-JVS(1068)*XX(91)
  XX(87) = XX(87)-JVS(983)*XX(88)-JVS(1005)*XX(89)-JVS(1041)*XX(90)-JVS(1067)*XX(91)
  XX(86) = XX(86)-JVS(953)*XX(87)-JVS(982)*XX(88)-JVS(1004)*XX(89)-JVS(1040)*XX(90)-JVS(1066)*XX(91)
  XX(85) = XX(85)-JVS(925)*XX(86)-JVS(952)*XX(87)-JVS(981)*XX(88)-JVS(1003)*XX(89)-JVS(1039)*XX(90)-JVS(1065)*XX(91)
  XX(84) = XX(84)-JVS(878)*XX(85)-JVS(924)*XX(86)-JVS(951)*XX(87)-JVS(980)*XX(88)-JVS(1002)*XX(89)-JVS(1038)*XX(90)&
             &-JVS(1064)*XX(91)
  XX(83) = XX(83)-JVS(828)*XX(84)-JVS(877)*XX(85)-JVS(923)*XX(86)-JVS(950)*XX(87)-JVS(979)*XX(88)-JVS(1001)*XX(89)&
             &-JVS(1037)*XX(90)-JVS(1063)*XX(91)
  XX(82) = XX(82)-JVS(797)*XX(83)-JVS(827)*XX(84)-JVS(876)*XX(85)-JVS(922)*XX(86)-JVS(949)*XX(87)-JVS(978)*XX(88)&
             &-JVS(1000)*XX(89)-JVS(1036)*XX(90)-JVS(1062)*XX(91)
  XX(81) = XX(81)-JVS(733)*XX(82)-JVS(796)*XX(83)-JVS(826)*XX(84)-JVS(875)*XX(85)-JVS(921)*XX(86)-JVS(948)*XX(87)&
             &-JVS(977)*XX(88)-JVS(999)*XX(89)-JVS(1035)*XX(90)-JVS(1061)*XX(91)
  XX(80) = XX(80)-JVS(692)*XX(81)-JVS(732)*XX(82)-JVS(795)*XX(83)-JVS(825)*XX(84)-JVS(874)*XX(85)-JVS(920)*XX(86)&
             &-JVS(947)*XX(87)-JVS(976)*XX(88)-JVS(998)*XX(89)-JVS(1034)*XX(90)-JVS(1060)*XX(91)
  XX(79) = XX(79)-JVS(658)*XX(80)-JVS(691)*XX(81)-JVS(731)*XX(82)-JVS(794)*XX(83)-JVS(824)*XX(84)-JVS(873)*XX(85)&
             &-JVS(919)*XX(86)-JVS(946)*XX(87)-JVS(975)*XX(88)-JVS(997)*XX(89)-JVS(1033)*XX(90)-JVS(1059)*XX(91)
  XX(78) = XX(78)-JVS(632)*XX(79)-JVS(657)*XX(80)-JVS(690)*XX(81)-JVS(730)*XX(82)-JVS(793)*XX(83)-JVS(823)*XX(84)&
             &-JVS(872)*XX(85)-JVS(918)*XX(86)-JVS(974)*XX(88)-JVS(996)*XX(89)-JVS(1032)*XX(90)-JVS(1058)*XX(91)
  XX(77) = XX(77)-JVS(656)*XX(80)-JVS(689)*XX(81)-JVS(729)*XX(82)-JVS(792)*XX(83)-JVS(822)*XX(84)-JVS(871)*XX(85)&
             &-JVS(917)*XX(86)-JVS(973)*XX(88)-JVS(995)*XX(89)-JVS(1031)*XX(90)-JVS(1057)*XX(91)
  XX(76) = XX(76)-JVS(560)*XX(77)-JVS(688)*XX(81)-JVS(728)*XX(82)-JVS(791)*XX(83)-JVS(821)*XX(84)-JVS(870)*XX(85)&
             &-JVS(916)*XX(86)-JVS(972)*XX(88)-JVS(994)*XX(89)-JVS(1030)*XX(90)-JVS(1056)*XX(91)
  XX(75) = XX(75)-JVS(593)*XX(78)-JVS(631)*XX(79)-JVS(655)*XX(80)-JVS(790)*XX(83)-JVS(820)*XX(84)-JVS(869)*XX(85)&
             &-JVS(915)*XX(86)-JVS(945)*XX(87)-JVS(971)*XX(88)-JVS(993)*XX(89)-JVS(1029)*XX(90)-JVS(1055)*XX(91)
  XX(74) = XX(74)-JVS(510)*XX(75)-JVS(592)*XX(78)-JVS(630)*XX(79)-JVS(654)*XX(80)-JVS(789)*XX(83)-JVS(819)*XX(84)&
             &-JVS(868)*XX(85)-JVS(914)*XX(86)-JVS(944)*XX(87)-JVS(970)*XX(88)-JVS(1028)*XX(90)
  XX(73) = XX(73)-JVS(489)*XX(74)-JVS(533)*XX(76)-JVS(559)*XX(77)-JVS(653)*XX(80)-JVS(687)*XX(81)-JVS(727)*XX(82)&
             &-JVS(788)*XX(83)-JVS(818)*XX(84)-JVS(867)*XX(85)-JVS(913)*XX(86)-JVS(969)*XX(88)-JVS(992)*XX(89)-JVS(1027)&
             &*XX(90)-JVS(1054)*XX(91)
  XX(72) = XX(72)-JVS(473)*XX(73)-JVS(532)*XX(76)-JVS(558)*XX(77)-JVS(591)*XX(78)-JVS(629)*XX(79)-JVS(686)*XX(81)&
             &-JVS(726)*XX(82)-JVS(787)*XX(83)-JVS(817)*XX(84)-JVS(866)*XX(85)-JVS(912)*XX(86)-JVS(943)*XX(87)-JVS(968)&
             &*XX(88)-JVS(1026)*XX(90)
  XX(71) = XX(71)-JVS(449)*XX(72)-JVS(472)*XX(73)-JVS(590)*XX(78)-JVS(628)*XX(79)-JVS(786)*XX(83)-JVS(865)*XX(85)&
             &-JVS(911)*XX(86)-JVS(942)*XX(87)-JVS(967)*XX(88)-JVS(1025)*XX(90)
  XX(70) = XX(70)-JVS(428)*XX(71)-JVS(448)*XX(72)-JVS(471)*XX(73)-JVS(488)*XX(74)-JVS(509)*XX(75)-JVS(531)*XX(76)&
             &-JVS(557)*XX(77)-JVS(589)*XX(78)-JVS(627)*XX(79)-JVS(685)*XX(81)-JVS(725)*XX(82)-JVS(785)*XX(83)-JVS(816)&
             &*XX(84)-JVS(864)*XX(85)-JVS(910)*XX(86)-JVS(941)*XX(87)-JVS(966)*XX(88)-JVS(1024)*XX(90)
  XX(69) = XX(69)-JVS(684)*XX(81)-JVS(784)*XX(83)-JVS(815)*XX(84)-JVS(863)*XX(85)-JVS(909)*XX(86)-JVS(965)*XX(88)
  XX(68) = XX(68)-JVS(397)*XX(69)-JVS(530)*XX(76)-JVS(556)*XX(77)-JVS(683)*XX(81)-JVS(724)*XX(82)-JVS(783)*XX(83)
  XX(67) = XX(67)-JVS(447)*XX(72)-JVS(470)*XX(73)-JVS(487)*XX(74)-JVS(508)*XX(75)-JVS(588)*XX(78)-JVS(626)*XX(79)&
             &-JVS(782)*XX(83)-JVS(814)*XX(84)-JVS(862)*XX(85)-JVS(908)*XX(86)-JVS(940)*XX(87)-JVS(1023)*XX(90)
  XX(66) = XX(66)-JVS(469)*XX(73)-JVS(587)*XX(78)-JVS(781)*XX(83)-JVS(861)*XX(85)-JVS(907)*XX(86)-JVS(939)*XX(87)&
             &-JVS(1022)*XX(90)
  XX(65) = XX(65)-JVS(529)*XX(76)-JVS(555)*XX(77)-JVS(682)*XX(81)-JVS(723)*XX(82)-JVS(780)*XX(83)-JVS(813)*XX(84)&
             &-JVS(906)*XX(86)-JVS(964)*XX(88)-JVS(991)*XX(89)-JVS(1053)*XX(91)
  XX(64) = XX(64)-JVS(427)*XX(71)-JVS(446)*XX(72)-JVS(468)*XX(73)-JVS(586)*XX(78)-JVS(625)*XX(79)-JVS(681)*XX(81)&
             &-JVS(722)*XX(82)-JVS(779)*XX(83)-JVS(812)*XX(84)-JVS(860)*XX(85)-JVS(905)*XX(86)-JVS(938)*XX(87)-JVS(1021)&
             &*XX(90)
  XX(63) = XX(63)-JVS(330)*XX(64)-JVS(377)*XX(68)-JVS(445)*XX(72)-JVS(467)*XX(73)-JVS(585)*XX(78)-JVS(624)*XX(79)&
             &-JVS(680)*XX(81)-JVS(721)*XX(82)-JVS(778)*XX(83)-JVS(811)*XX(84)-JVS(859)*XX(85)-JVS(904)*XX(86)-JVS(937)&
             &*XX(87)-JVS(1020)*XX(90)
  XX(62) = XX(62)-JVS(396)*XX(69)-JVS(466)*XX(73)-JVS(584)*XX(78)-JVS(623)*XX(79)-JVS(679)*XX(81)-JVS(720)*XX(82)&
             &-JVS(777)*XX(83)-JVS(810)*XX(84)-JVS(858)*XX(85)-JVS(903)*XX(86)-JVS(1019)*XX(90)
  XX(61) = XX(61)-JVS(350)*XX(66)-JVS(444)*XX(72)-JVS(465)*XX(73)-JVS(507)*XX(75)-JVS(583)*XX(78)-JVS(622)*XX(79)&
             &-JVS(776)*XX(83)-JVS(809)*XX(84)-JVS(857)*XX(85)-JVS(902)*XX(86)-JVS(1018)*XX(90)
  XX(60) = XX(60)-JVS(395)*XX(69)-JVS(554)*XX(77)-JVS(678)*XX(81)-JVS(775)*XX(83)-JVS(990)*XX(89)-JVS(1052)*XX(91)
  XX(59) = XX(59)-JVS(349)*XX(66)-JVS(426)*XX(71)-JVS(443)*XX(72)-JVS(464)*XX(73)-JVS(486)*XX(74)-JVS(582)*XX(78)&
             &-JVS(621)*XX(79)-JVS(677)*XX(81)-JVS(774)*XX(83)-JVS(808)*XX(84)-JVS(856)*XX(85)-JVS(901)*XX(86)-JVS(1017)&
             &*XX(90)
  XX(58) = XX(58)-JVS(528)*XX(76)-JVS(553)*XX(77)-JVS(676)*XX(81)-JVS(719)*XX(82)-JVS(773)*XX(83)
  XX(57) = XX(57)-JVS(283)*XX(58)-JVS(527)*XX(76)-JVS(552)*XX(77)-JVS(675)*XX(81)-JVS(718)*XX(82)-JVS(772)*XX(83)&
             &-JVS(900)*XX(86)-JVS(1016)*XX(90)
  XX(56) = XX(56)-JVS(771)*XX(83)-JVS(855)*XX(85)
  XX(55) = XX(55)-JVS(256)*XX(56)-JVS(463)*XX(73)-JVS(506)*XX(75)-JVS(581)*XX(78)-JVS(620)*XX(79)-JVS(770)*XX(83)&
             &-JVS(807)*XX(84)-JVS(854)*XX(85)
  XX(54) = XX(54)-JVS(348)*XX(66)-JVS(425)*XX(71)-JVS(442)*XX(72)-JVS(462)*XX(73)-JVS(619)*XX(79)-JVS(853)*XX(85)&
             &-JVS(899)*XX(86)-JVS(936)*XX(87)
  XX(53) = XX(53)-JVS(769)*XX(83)-JVS(898)*XX(86)-JVS(1015)*XX(90)
  XX(52) = XX(52)-JVS(282)*XX(58)-JVS(526)*XX(76)-JVS(551)*XX(77)-JVS(717)*XX(82)-JVS(768)*XX(83)
  XX(51) = XX(51)-JVS(674)*XX(81)-JVS(767)*XX(83)-JVS(989)*XX(89)-JVS(1051)*XX(91)
  XX(50) = XX(50)-JVS(255)*XX(56)-JVS(716)*XX(82)-JVS(766)*XX(83)-JVS(852)*XX(85)
  XX(49) = XX(49)-JVS(394)*XX(69)-JVS(580)*XX(78)-JVS(618)*XX(79)-JVS(652)*XX(80)-JVS(765)*XX(83)-JVS(851)*XX(85)&
             &-JVS(897)*XX(86)-JVS(963)*XX(88)
  XX(48) = XX(48)-JVS(485)*XX(74)-JVS(617)*XX(79)-JVS(764)*XX(83)-JVS(850)*XX(85)-JVS(896)*XX(86)-JVS(935)*XX(87)&
             &-JVS(1014)*XX(90)
  XX(47) = XX(47)-JVS(376)*XX(68)-JVS(673)*XX(81)-JVS(715)*XX(82)-JVS(763)*XX(83)-JVS(849)*XX(85)
  XX(46) = XX(46)-JVS(311)*XX(61)-JVS(347)*XX(66)-JVS(848)*XX(85)-JVS(895)*XX(86)
  XX(45) = XX(45)-JVS(254)*XX(56)-JVS(505)*XX(75)-JVS(616)*XX(79)-JVS(762)*XX(83)-JVS(847)*XX(85)
  XX(44) = XX(44)-JVS(461)*XX(73)-JVS(615)*XX(79)-JVS(761)*XX(83)-JVS(846)*XX(85)-JVS(934)*XX(87)
  XX(43) = XX(43)-JVS(579)*XX(78)-JVS(614)*XX(79)-JVS(651)*XX(80)-JVS(760)*XX(83)-JVS(845)*XX(85)
  XX(42) = XX(42)-JVS(214)*XX(51)-JVS(759)*XX(83)-JVS(894)*XX(86)-JVS(988)*XX(89)-JVS(1013)*XX(90)-JVS(1050)*XX(91)
  XX(41) = XX(41)-JVS(375)*XX(68)-JVS(460)*XX(73)-JVS(578)*XX(78)-JVS(613)*XX(79)-JVS(714)*XX(82)-JVS(758)*XX(83)&
             &-JVS(844)*XX(85)-JVS(933)*XX(87)
  XX(40) = XX(40)-JVS(374)*XX(68)-JVS(577)*XX(78)-JVS(713)*XX(82)-JVS(757)*XX(83)-JVS(843)*XX(85)
  XX(39) = XX(39)-JVS(373)*XX(68)-JVS(424)*XX(71)-JVS(612)*XX(79)-JVS(712)*XX(82)-JVS(756)*XX(83)-JVS(842)*XX(85)&
             &-JVS(932)*XX(87)
  XX(38) = XX(38)-JVS(205)*XX(50)-JVS(372)*XX(68)-JVS(611)*XX(79)-JVS(650)*XX(80)-JVS(711)*XX(82)-JVS(755)*XX(83)&
             &-JVS(841)*XX(85)
  XX(37) = XX(37)-JVS(248)*XX(55)-JVS(310)*XX(61)-JVS(346)*XX(66)-JVS(441)*XX(72)-JVS(840)*XX(85)-JVS(893)*XX(86)&
             &-JVS(962)*XX(88)
  XX(36) = XX(36)-JVS(754)*XX(83)-JVS(839)*XX(85)-JVS(892)*XX(86)-JVS(1012)*XX(90)
  XX(35) = XX(35)-JVS(504)*XX(75)-JVS(649)*XX(80)-JVS(753)*XX(83)
  XX(34) = XX(34)-JVS(648)*XX(80)-JVS(752)*XX(83)
  XX(33) = XX(33)-JVS(213)*XX(51)-JVS(751)*XX(83)-JVS(1049)*XX(91)
  XX(32) = XX(32)-JVS(281)*XX(58)-JVS(710)*XX(82)-JVS(750)*XX(83)-JVS(891)*XX(86)
  XX(31) = XX(31)-JVS(393)*XX(69)-JVS(749)*XX(83)
  XX(30) = XX(30)-JVS(748)*XX(83)-JVS(890)*XX(86)-JVS(961)*XX(88)
  XX(29) = XX(29)-JVS(550)*XX(77)-JVS(672)*XX(81)-JVS(960)*XX(88)
  XX(28) = XX(28)-JVS(503)*XX(75)-JVS(647)*XX(80)-JVS(889)*XX(86)-JVS(1011)*XX(90)
  XX(27) = XX(27)-JVS(108)*XX(29)-JVS(671)*XX(81)-JVS(888)*XX(86)-JVS(959)*XX(88)
  XX(26) = XX(26)-JVS(149)*XX(37)-JVS(180)*XX(45)-JVS(309)*XX(61)-JVS(440)*XX(72)-JVS(610)*XX(79)-JVS(747)*XX(83)&
             &-JVS(838)*XX(85)
  XX(25) = XX(25)-JVS(231)*XX(53)-JVS(887)*XX(86)-JVS(1010)*XX(90)
  XX(24) = XX(24)-JVS(223)*XX(52)-JVS(525)*XX(76)-JVS(709)*XX(82)
  XX(23) = XX(23)-JVS(576)*XX(78)-JVS(609)*XX(79)-JVS(646)*XX(80)-JVS(746)*XX(83)-JVS(1048)*XX(91)
  XX(22) = XX(22)-JVS(148)*XX(37)-JVS(308)*XX(61)-JVS(608)*XX(79)-JVS(745)*XX(83)-JVS(837)*XX(85)
  XX(21) = XX(21)-JVS(886)*XX(86)-JVS(1047)*XX(91)
  XX(20) = XX(20)-JVS(708)*XX(82)-JVS(1046)*XX(91)
  XX(19) = XX(19)-JVS(707)*XX(82)-JVS(744)*XX(83)
  XX(18) = XX(18)
  XX(17) = XX(17)
  XX(16) = XX(16)
  XX(15) = XX(15)
  XX(14) = XX(14)
  XX(13) = XX(13)
  XX(12) = XX(12)
  XX(11) = XX(11)
  XX(10) = XX(10)
  XX(9) = XX(9)
  XX(8) = XX(8)
  XX(7) = XX(7)
  XX(6) = XX(6)
  XX(5) = XX(5)
  XX(4) = XX(4)
  XX(3) = XX(3)-JVS(706)*XX(82)
  XX(2) = XX(2)-JVS(705)*XX(82)
  XX(1) = XX(1)-JVS(704)*XX(82)
      
END SUBROUTINE KppSolveTR

! End of KppSolveTR function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE cbm5_strato_SOA_LinearAlgebra

