! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Linear Algebra Data and Routines File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : cbm5_SOA_LinearAlgebra.f90
! Time                 : Tue Apr  5 09:32:49 2022
! Working directory    : /home/kouzne/SILAM/silamgit/kpp/cbm5_SOA
! Equation file        : cbm5_SOA.kpp
! Output root filename : cbm5_SOA
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE cbm5_SOA_LinearAlgebra

  USE cbm5_SOA_Parameters
  USE cbm5_SOA_JacobianSP

  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! SPARSE_UTIL - SPARSE utility functions
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppDecomp( JVS, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse LU factorization
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm5_SOA_Parameters
  USE cbm5_SOA_JacobianSP

      INTEGER  :: IER
      REAL(kind=sp) :: JVS(LU_NONZERO), W(NVAR), a
      INTEGER  :: k, kk, j, jj

      a = 0. ! mz_rs_20050606
      IER = 0
      DO k=1,NVAR
        ! mz_rs_20050606: don't check if real value == 0
        ! IF ( JVS( LU_DIAG(k) ) .EQ. 0. ) THEN
        IF ( ABS(JVS(LU_DIAG(k))) < TINY(a) ) THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              W( LU_ICOL(kk) ) = JVS(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            a = -W(j) / JVS( LU_DIAG(j) )
            W(j) = -a
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               W( LU_ICOL(jj) ) = W( LU_ICOL(jj) ) + a*JVS(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVS(kk) = W( LU_ICOL(kk) )
         END DO
      END DO
      
END SUBROUTINE KppDecomp


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppDecompCmplx( JVS, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse LU factorization, complex
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm5_SOA_Parameters
  USE cbm5_SOA_JacobianSP

      INTEGER        :: IER
      DOUBLE COMPLEX :: JVS(LU_NONZERO), W(NVAR), a
      REAL(kind=sp)  :: b = 0.0
      INTEGER        :: k, kk, j, jj

      IER = 0
      DO k=1,NVAR
        IF ( ABS(JVS(LU_DIAG(k))) < TINY(b) ) THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              W( LU_ICOL(kk) ) = JVS(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            a = -W(j) / JVS( LU_DIAG(j) )
            W(j) = -a
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               W( LU_ICOL(jj) ) = W( LU_ICOL(jj) ) + a*JVS(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVS(kk) = W( LU_ICOL(kk) )
         END DO
      END DO
      
END SUBROUTINE KppDecompCmplx


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppDecompCmplxR( JVSR, JVSI, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!    Sparse LU factorization, complex
!   (Real and Imaginary parts are used instead of complex data type)     
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm5_SOA_Parameters
  USE cbm5_SOA_JacobianSP

      INTEGER       :: IER
      REAL(kind=sp) :: JVSR(LU_NONZERO), JVSI(LU_NONZERO) 
      REAL(kind=sp) :: WR(NVAR), WI(NVAR), ar, ai, den
      INTEGER       :: k, kk, j, jj

      IER = 0
      ar  = 0.0
      DO k=1,NVAR
        IF (  ( ABS(JVSR(LU_DIAG(k))) < TINY(ar) ) .AND. &
              ( ABS(JVSI(LU_DIAG(k))) < TINY(ar) ) )  THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              WR( LU_ICOL(kk) ) = JVSR(kk)
              WI( LU_ICOL(kk) ) = JVSI(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            den = JVSR(LU_DIAG(j))**2 + JVSI(LU_DIAG(j))**2
            ar = -(WR(j)*JVSR(LU_DIAG(j)) + WI(j)*JVSI(LU_DIAG(j)))/den
            ai = -(WI(j)*JVSR(LU_DIAG(j)) - WR(j)*JVSI(LU_DIAG(j)))/den
            WR(j) = -ar
            WI(j) = -ai
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               WR( LU_ICOL(jj) ) = WR( LU_ICOL(jj) ) + ar*JVSR(jj) - ai*JVSI(jj)
               WI( LU_ICOL(jj) ) = WI( LU_ICOL(jj) ) + ar*JVSI(jj) + ai*JVSR(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVSR(kk) = WR( LU_ICOL(kk) )
            JVSI(kk) = WI( LU_ICOL(kk) )
         END DO
      END DO

END SUBROUTINE KppDecompCmplxR


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveIndirect( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse solve subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm5_SOA_Parameters
  USE cbm5_SOA_JacobianSP

      INTEGER  :: i, j
      REAL(kind=sp) :: JVS(LU_NONZERO), X(NVAR), sum

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1 
             X(i) = X(i) - JVS(j)*X(LU_ICOL(j));
         END DO  
      END DO

      DO i=NVAR,1,-1
        sum = X(i);
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
          sum = sum - JVS(j)*X(LU_ICOL(j));
        END DO
        X(i) = sum/JVS(LU_DIAG(i));
      END DO
      
END SUBROUTINE KppSolveIndirect


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveTRIndirect( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve transpose subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm5_SOA_Parameters
  USE cbm5_SOA_JacobianSP

      INTEGER       :: i, j
      REAL(kind=sp) :: JVS(LU_NONZERO), X(NVAR)

      DO i=1,NVAR
        X(i) = X(i)/JVS(LU_DIAG(i))
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
	  X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
	END DO
      END DO

      DO i=NVAR, 1, -1
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
	  X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
	END DO
      END DO
      
END SUBROUTINE KppSolveTRIndirect


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveCmplx( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm5_SOA_Parameters
  USE cbm5_SOA_JacobianSP

      INTEGER        :: i, j
      DOUBLE COMPLEX :: JVS(LU_NONZERO), X(NVAR), sum

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1 
             X(i) = X(i) - JVS(j)*X(LU_ICOL(j));
         END DO  
      END DO

      DO i=NVAR,1,-1
        sum = X(i);
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
          sum = sum - JVS(j)*X(LU_ICOL(j));
        END DO
        X(i) = sum/JVS(LU_DIAG(i));
      END DO
      
END SUBROUTINE KppSolveCmplx

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveCmplxR( JVSR, JVSI, XR, XI )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!   Complex sparse solve subroutine using indirect addressing
!   (Real and Imaginary parts are used instead of complex data type)     
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm5_SOA_Parameters
  USE cbm5_SOA_JacobianSP

      INTEGER       ::  i, j
      REAL(kind=sp) ::  JVSR(LU_NONZERO), JVSI(LU_NONZERO), XR(NVAR), XI(NVAR), sumr, sumi, den

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1 
             XR(i) = XR(i) - (JVSR(j)*XR(LU_ICOL(j)) - JVSI(j)*XI(LU_ICOL(j)))
             XI(i) = XI(i) - (JVSR(j)*XI(LU_ICOL(j)) + JVSI(j)*XR(LU_ICOL(j)))
         END DO  
      END DO

      DO i=NVAR,1,-1
        sumr = XR(i); sumi = XI(i)
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
            sumr = sumr - (JVSR(j)*XR(LU_ICOL(j)) - JVSI(j)*XI(LU_ICOL(j)))
            sumi = sumi - (JVSR(j)*XI(LU_ICOL(j)) + JVSI(j)*XR(LU_ICOL(j)))
        END DO
        den   = JVSR(LU_DIAG(i))**2 + JVSI(LU_DIAG(i))**2
        XR(i) = (sumr*JVSR(LU_DIAG(i)) + sumi*JVSI(LU_DIAG(i)))/den
        XI(i) = (sumi*JVSR(LU_DIAG(i)) - sumr*JVSI(LU_DIAG(i)))/den
      END DO
      
END SUBROUTINE KppSolveCmplxR


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveTRCmplx( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve transpose subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm5_SOA_Parameters
  USE cbm5_SOA_JacobianSP

      INTEGER        :: i, j
      DOUBLE COMPLEX :: JVS(LU_NONZERO), X(NVAR)

      DO i=1,NVAR
        X(i) = X(i)/JVS(LU_DIAG(i))
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
	  X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
	END DO
      END DO

      DO i=NVAR, 1, -1
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
	  X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
	END DO
      END DO
      
END SUBROUTINE KppSolveTRCmplx


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveTRCmplxR( JVSR, JVSI, XR, XI )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!   Complex sparse solve transpose subroutine using indirect addressing
!   (Real and Imaginary parts are used instead of complex data type)     
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm5_SOA_Parameters
  USE cbm5_SOA_JacobianSP

      INTEGER       ::  i, j
      REAL(kind=sp) ::  JVSR(LU_NONZERO), JVSI(LU_NONZERO), XR(NVAR), XI(NVAR), den

      DO i=1,NVAR
        den   = JVSR(LU_DIAG(i))**2 + JVSI(LU_DIAG(i))**2
        XR(i) = (XR(i)*JVSR(LU_DIAG(i)) + XI(i)*JVSI(LU_DIAG(i)))/den
        XI(i) = (XI(i)*JVSR(LU_DIAG(i)) - XR(i)*JVSI(LU_DIAG(i)))/den
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
	  XR(LU_ICOL(j)) = XR(LU_ICOL(j))-(JVSR(j)*XR(i) - JVSI(j)*XI(i))
	  XI(LU_ICOL(j)) = XI(LU_ICOL(j))-(JVSI(j)*XR(i) + JVSR(j)*XI(i))
	END DO
      END DO

      DO i=NVAR, 1, -1
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
	  XR(LU_ICOL(j)) = XR(LU_ICOL(j))-(JVSR(j)*XR(i) - JVSI(j)*XI(i))
	  XI(LU_ICOL(j)) = XI(LU_ICOL(j))-(JVSI(j)*XR(i) + JVSR(j)*XI(i))
	END DO
      END DO
      
END SUBROUTINE KppSolveTRCmplxR


!
! Next few commented subroutines perform sparse big linear algebra
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppDecompBig( JVS, IP, IER )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Sparse LU factorization
!!        for the Runge Kutta (3n)x(3n) linear system
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE cbm5_SOA_Parameters
!  USE cbm5_SOA_JacobianSP
!
!      INTEGER  :: IP3(3), IER, IP(3,NVAR)
!      REAL(kind=sp) :: JVS(3,3,LU_NONZERO), W(3,3,NVAR), a(3,3), E(3,3)
!      INTEGER  :: k, kk, j, jj
!
!      a = 0.0d0
!      IER = 0
!      DO k=1,NVAR
!        DO kk = LU_CROW(k), LU_CROW(k+1)-1
!              W( 1:3,1:3,LU_ICOL(kk) ) = JVS(1:3,1:3,kk)
!        END DO
!        DO kk = LU_CROW(k), LU_DIAG(k)-1
!            j = LU_ICOL(kk)
!            E(1:3,1:3) = JVS( 1:3,1:3,LU_DIAG(j) )
!            ! CALL DGETRF(3,3,E,3,IP3,IER) 
!            CALL FAC3(E,IP3,IER)
!            IF ( IER /= 0 )  RETURN
!            ! a = W(j) / JVS( LU_DIAG(j) )
!            a(1:3,1:3) = W( 1:3,1:3,j )
!            ! CALL DGETRS ('N',3,3,E,3,IP3,a,3,IER) 
!            CALL SOL3('N',E,IP3,a(1,1))
!            CALL SOL3('N',E,IP3,a(1,2))
!            CALL SOL3('N',E,IP3,a(1,3))
!            W(1:3,1:3,j) = a(1:3,1:3)
!            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
!               W( 1:3,1:3,LU_ICOL(jj) ) = W( 1:3,1:3,LU_ICOL(jj) ) &
!                        - MATMUL( a(1:3,1:3) , JVS(1:3,1:3,jj) )
!            END DO
!         END DO
!         DO kk = LU_CROW(k), LU_CROW(k+1)-1
!            JVS(1:3,1:3,kk) = W( 1:3,1:3,LU_ICOL(kk) )
!         END DO
!      END DO
!
!      DO k=1,NVAR
!         ! CALL WGEFA(JVS(1,1,LU_DIAG(k)),3,3,IP(1,k),IER)
!         ! CALL DGETRF(3,3,JVS(1,1,LU_DIAG(k)),3,IP(1,k),IER)
!         CALL FAC3(JVS(1,1,LU_DIAG(k)),IP(1,k),IER)
!         IF ( IER /= 0 )  RETURN
!      END DO 
!      
!END SUBROUTINE KppDecompBig
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppSolveBig( JVS, IP, X )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Sparse solve subroutine using indirect addressing
!!        for the Runge Kutta (3n)x(3n) linear system
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE cbm5_SOA_Parameters
!  USE cbm5_SOA_JacobianSP
!
!      INTEGER  :: i, j, k, m, IP3(3), IP(3,NVAR), IER
!      REAL(kind=sp) :: JVS(3,3,LU_NONZERO), X(3,NVAR), sum(3)
!
!      DO i=1,NVAR
!        DO j = LU_CROW(i), LU_DIAG(i)-1 
!          !X(1:3,i) = X(1:3,i) - MATMUL(JVS(1:3,1:3,j),X(1:3,LU_ICOL(j)));
!          DO k=1,3
!            DO m=1,3
!	       X(k,i) = X(k,i) - JVS(k,m,j)*X(m,LU_ICOL(j))
!            END DO
!          END DO
!        END DO  
!      END DO
!
!      DO i=NVAR,1,-1
!        sum(1:3) = X(1:3,i);
!        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
!          !sum(1:3) = sum(1:3) - MATMUL(JVS(1:3,1:3,j),X(1:3,LU_ICOL(j)));
!          DO k=1,3
!            DO m=1,3
!	       sum(k) = sum(k) - JVS(k,m,j)*X(m,LU_ICOL(j))
!            END DO
!          END DO
!        END DO
!        ! X(i) = sum/JVS(LU_DIAG(i));
!        ! CALL DGETRS ('N',3,1,JVS(1:3,1:3,LU_DIAG(i)),3,IP(1,i),sum,3,0) 
!        ! CALL WGESL('N',JVS(1,1,LU_DIAG(i)),3,3,IP(1,i),sum)
!        CALL SOL3('N',JVS(1,1,LU_DIAG(i)),IP(1,i),sum)
!        X(1:3,i) = sum(1:3)
!      END DO
!      
!END SUBROUTINE KppSolveBig
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppSolveBigTR( JVS, IP, X )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Big sparse transpose solve using indirect addressing
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE cbm5_SOA_Parameters
!  USE cbm5_SOA_JacobianSP
!
!      INTEGER       :: i, j, k, m, IP(3,NVAR)
!      REAL(kind=sp) :: JVS(3,3,LU_NONZERO), X(3,NVAR)
!
!      DO i=1,NVAR
!        ! X(i) = X(i)/JVS(LU_DIAG(i))
!        CALL SOL3('T',JVS(1,1,LU_DIAG(i)),IP(1,i),X(1,i))
!        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
!	  !X(1:3,LU_ICOL(j)) = X(1:3,LU_ICOL(j)) &
!          !    - MATMUL( TRANSPOSE(JVS(1:3,1:3,j)), X(1:3,i) )
!          DO k=1,3
!            DO m=1,3
!	       X(k,LU_ICOL(j)) = X(k,LU_ICOL(j)) - JVS(m,k,j)*X(m,i)
!            END DO
!          END DO
!	END DO
!      END DO
!
!      DO i=NVAR, 1, -1
!        DO j=LU_CROW(i),LU_DIAG(i)-1
!	  !X(1:3,LU_ICOL(j)) = X(1:3,LU_ICOL(j)) &
!          !   - MATMUL( TRANSPOSE(JVS(1:3,1:3,j)), X(1:3,i) )
!          DO k=1,3
!            DO m=1,3
!	       X(k,LU_ICOL(j)) = X(k,LU_ICOL(j)) - JVS(m,k,j)*X(m,i)
!            END DO
!          END DO
!	END DO
!      END DO
!      
!END SUBROUTINE KppSolveBigTR
!
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE FAC3(A,IPVT,INFO)
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!     FAC3 FACTORS THE MATRIX A (3,3) BY
!!           GAUSS ELIMINATION WITH PARTIAL PIVOTING
!!     LINPACK - LIKE 
!!
!!     Remove comments to perform pivoting
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!
!      REAL(kind=sp) :: A(3,3)
!      INTEGER       :: IPVT(3),INFO
!!      INTEGER       :: L
!!      REAL(kind=sp) :: t, dmax, da, TMP(3)
!      REAL(kind=sp), PARAMETER :: ZERO = 0.0, ONE = 1.0
!
!      info = 0
!!      t = TINY(da)
!!      
!!      da = ABS(A(1,1)); L = 1
!!      IF ( ABS(A(2,1))>da ) THEN
!!        da = ABS(A(2,1)); L = 2
!!        IF ( ABS(A(3,1))>da ) THEN
!!          L = 3
!!        END IF  
!!      END IF  
!!      IPVT(1)  = L
!!      IF (L /=1 ) THEN
!!         TMP(1:3) = A(L,1:3)
!!         A(L,1:3) = A(1,1:3)
!!         A(1,1:3) = TMP(1:3)
!!      END IF
!!      IF (ABS(A(1,1)) < t) THEN
!!         info = 1
!!         return
!!      END IF   
!!
!      A(2,1) = A(2,1)/A(1,1)
!      A(2,2) = A(2,2) - A(2,1)*A(1,2)
!      A(2,3) = A(2,3) - A(2,1)*A(1,3)
!      A(3,1) = A(3,1)/A(1,1)
!      A(3,2) = A(3,2) - A(3,1)*A(1,2)
!      A(3,3) = A(3,3) - A(3,1)*A(1,3)
!      
!!      IPVT(2)  = 2
!!      IF (ABS(A(3,2))>ABS(A(2,2))) THEN
!!         IPVT(2)  = 3
!!         TMP(2:3) = A(3,2:3)
!!         A(3,2:3) = A(2,2:3)
!!         A(2,2:3) = TMP(2:3)
!!      END IF
!!      IF (ABS(A(2,2)) < t) THEN
!!         info = 1
!!         return
!!      END IF   
!!      
!      A(3,2)   = A(3,2)/A(2,2)
!      A(3,3)   = A(3,3) - A(3,2)*A(2,3)
!      IPVT(3)  = 3
!      
!END SUBROUTINE FAC3
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE SOL3(Trans,A,IPVT,b)
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!     SOL3 solves the system 3x3
!!     A * x = b  or  trans(a) * x = b
!!     using the factors computed by WGEFA.
!!
!!     Trans      = 'N'   to solve  A*x = b ,
!!                = 'T'   to solve  transpose(A)*x = b
!!     LINPACK - LIKE 
!!
!!     Remove comments to use pivoting
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!      CHARACTER     :: Trans
!      REAL(kind=sp) :: a(3,3),b(3)
!      INTEGER       :: IPVT(3)
!!      INTEGER       :: L
!!      REAL(kind=sp) :: TMP
!      
!      SELECT CASE (Trans)
!
!      CASE ('n','N')  !  Solve  A * x = b
!
!!     Solve  L*y = b
!!         L = IPVT(1)
!!         IF (L /= 1) THEN
!!            TMP = B(1); B(1) = B(L); B(L) = TMP
!!         END IF
!         b(2) = b(2)-A(2,1)*b(1)
!         b(3) = b(3)-A(3,1)*b(1)
!         
!!         L = IPVT(2)
!!         IF (L /= 2) THEN
!!            TMP = B(2); B(2) = B(L); B(L) = TMP
!!         END IF
!         b(3) = b(3)-A(3,2)*b(2)
!
!!     Solve  U*x = y
!         b(3) = b(3)/A(3,3)
!         b(2) = (b(2)-A(2,3)*b(3))/A(2,2)
!         b(1) = (b(1)-A(1,3)*b(3)-A(1,2)*b(2))/A(1,1)
!      
!      
!      CASE ('t','T')  !  Solve transpose(A) * x = b
!
!!      Solve transpose(U)*y = b
!         b(1) = b(1)/A(1,1)
!         b(2) = (b(2)-A(1,2)*b(1))/A(2,2)
!         b(3) = (b(3)-A(1,3)*b(1)-A(2,3)*b(2))/A(3,3)
!
!!      Solve transpose(L)*x = y
!         b(2) = b(2)-A(3,2)*b(3)
!!         L = ipvt(2)
!!         IF (L /= 2) THEN
!!            TMP = B(2); B(2) = B(L); B(L) = TMP
!!         END IF
!         b(1) = b(1)-A(3,1)*b(3)-A(2,1)*b(2)
!!         L = ipvt(1)
!!         IF (L /= 1) THEN
!!            TMP = B(1); B(1) = B(L); B(L) = TMP
!!         END IF
!   
!      END SELECT
!
!END SUBROUTINE SOL3

! End of SPARSE_UTIL function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! KppSolve - sparse back substitution
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      X         - Vector for variables
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE KppSolve ( JVS, X )

! JVS - sparse Jacobian of variables
  REAL(kind=sp) :: JVS(LU_NONZERO)
! X - Vector for variables
  REAL(kind=sp) :: X(NVAR)

  X(30) = X(30)-JVS(128)*X(17)-JVS(129)*X(22)
  X(33) = X(33)-JVS(142)*X(22)
  X(37) = X(37)-JVS(162)*X(31)
  X(38) = X(38)-JVS(169)*X(33)
  X(39) = X(39)-JVS(185)*X(30)
  X(40) = X(40)-JVS(191)*X(21)
  X(45) = X(45)-JVS(223)*X(17)-JVS(224)*X(22)-JVS(225)*X(30)-JVS(226)*X(34)
  X(47) = X(47)-JVS(239)*X(46)
  X(48) = X(48)-JVS(246)*X(30)-JVS(247)*X(34)-JVS(248)*X(36)-JVS(249)*X(44)-JVS(250)*X(45)-JVS(251)*X(46)-JVS(252)*X(47)
  X(49) = X(49)-JVS(263)*X(20)-JVS(264)*X(32)-JVS(265)*X(36)-JVS(266)*X(39)-JVS(267)*X(41)-JVS(268)*X(42)-JVS(269)*X(43)&
            &-JVS(270)*X(44)-JVS(271)*X(45)-JVS(272)*X(46)-JVS(273)*X(47)-JVS(274)*X(48)
  X(50) = X(50)-JVS(286)*X(18)-JVS(287)*X(20)-JVS(288)*X(32)-JVS(289)*X(35)-JVS(290)*X(36)-JVS(291)*X(42)-JVS(292)*X(43)&
            &-JVS(293)*X(47)-JVS(294)*X(48)
  X(51) = X(51)-JVS(309)*X(19)-JVS(310)*X(20)-JVS(311)*X(31)-JVS(312)*X(37)-JVS(313)*X(39)-JVS(314)*X(41)-JVS(315)*X(42)&
            &-JVS(316)*X(43)-JVS(317)*X(44)-JVS(318)*X(45)-JVS(319)*X(46)-JVS(320)*X(47)-JVS(321)*X(48)
  X(52) = X(52)-JVS(335)*X(39)-JVS(336)*X(41)-JVS(337)*X(42)-JVS(338)*X(43)-JVS(339)*X(44)-JVS(340)*X(45)-JVS(341)*X(46)&
            &-JVS(342)*X(47)
  X(53) = X(53)-JVS(352)*X(23)-JVS(353)*X(27)-JVS(354)*X(28)-JVS(355)*X(37)-JVS(356)*X(49)-JVS(357)*X(50)-JVS(358)*X(51)&
            &-JVS(359)*X(52)
  X(54) = X(54)-JVS(372)*X(35)-JVS(373)*X(44)-JVS(374)*X(46)-JVS(375)*X(47)-JVS(376)*X(49)-JVS(377)*X(52)-JVS(378)*X(53)
  X(55) = X(55)-JVS(390)*X(17)-JVS(391)*X(18)-JVS(392)*X(20)-JVS(393)*X(22)-JVS(394)*X(32)-JVS(395)*X(33)-JVS(396)*X(35)&
            &-JVS(397)*X(36)-JVS(398)*X(37)-JVS(399)*X(39)-JVS(400)*X(41)-JVS(401)*X(42)-JVS(402)*X(43)-JVS(403)*X(44)&
            &-JVS(404)*X(45)-JVS(405)*X(46)-JVS(406)*X(47)-JVS(407)*X(51)-JVS(408)*X(52)-JVS(409)*X(53)-JVS(410)*X(54)
  X(56) = X(56)-JVS(421)*X(21)-JVS(422)*X(23)-JVS(423)*X(29)-JVS(424)*X(35)-JVS(425)*X(40)-JVS(426)*X(41)-JVS(427)*X(42)&
            &-JVS(428)*X(43)-JVS(429)*X(44)-JVS(430)*X(45)-JVS(431)*X(46)-JVS(432)*X(47)-JVS(433)*X(48)-JVS(434)*X(49)&
            &-JVS(435)*X(50)-JVS(436)*X(51)-JVS(437)*X(52)-JVS(438)*X(53)-JVS(439)*X(54)-JVS(440)*X(55)
  X(57) = X(57)-JVS(450)*X(23)-JVS(451)*X(28)-JVS(452)*X(33)-JVS(453)*X(39)-JVS(454)*X(45)-JVS(455)*X(47)-JVS(456)*X(50)&
            &-JVS(457)*X(52)-JVS(458)*X(53)-JVS(459)*X(54)-JVS(460)*X(55)-JVS(461)*X(56)
  X(58) = X(58)-JVS(470)*X(16)-JVS(471)*X(25)-JVS(472)*X(41)-JVS(473)*X(42)-JVS(474)*X(43)-JVS(475)*X(44)-JVS(476)*X(46)&
            &-JVS(477)*X(49)-JVS(478)*X(50)-JVS(479)*X(51)-JVS(480)*X(52)-JVS(481)*X(53)-JVS(482)*X(54)-JVS(483)*X(55)&
            &-JVS(484)*X(56)-JVS(485)*X(57)
  X(59) = X(59)-JVS(493)*X(21)-JVS(494)*X(23)-JVS(495)*X(24)-JVS(496)*X(29)-JVS(497)*X(30)-JVS(498)*X(31)-JVS(499)*X(34)&
            &-JVS(500)*X(35)-JVS(501)*X(36)-JVS(502)*X(40)-JVS(503)*X(41)-JVS(504)*X(42)-JVS(505)*X(43)-JVS(506)*X(44)&
            &-JVS(507)*X(45)-JVS(508)*X(46)-JVS(509)*X(47)-JVS(510)*X(48)-JVS(511)*X(49)-JVS(512)*X(50)-JVS(513)*X(51)&
            &-JVS(514)*X(52)-JVS(515)*X(53)-JVS(516)*X(54)-JVS(517)*X(55)-JVS(518)*X(56)-JVS(519)*X(57)-JVS(520)*X(58)
  X(60) = X(60)-JVS(527)*X(16)-JVS(528)*X(17)-JVS(529)*X(18)-JVS(530)*X(19)-JVS(531)*X(20)-JVS(532)*X(22)-JVS(533)*X(25)&
            &-JVS(534)*X(26)-JVS(535)*X(29)-JVS(536)*X(30)-JVS(537)*X(31)-JVS(538)*X(32)-JVS(539)*X(33)-JVS(540)*X(34)&
            &-JVS(541)*X(35)-JVS(542)*X(36)-JVS(543)*X(37)-JVS(544)*X(38)-JVS(545)*X(39)-JVS(546)*X(41)-JVS(547)*X(42)&
            &-JVS(548)*X(43)-JVS(549)*X(44)-JVS(550)*X(45)-JVS(551)*X(46)-JVS(552)*X(47)-JVS(553)*X(48)-JVS(554)*X(49)&
            &-JVS(555)*X(50)-JVS(556)*X(51)-JVS(557)*X(52)-JVS(558)*X(53)-JVS(559)*X(54)-JVS(560)*X(55)-JVS(561)*X(56)&
            &-JVS(562)*X(57)-JVS(563)*X(58)-JVS(564)*X(59)
  X(61) = X(61)-JVS(570)*X(22)-JVS(571)*X(30)-JVS(572)*X(36)-JVS(573)*X(42)-JVS(574)*X(43)-JVS(575)*X(44)-JVS(576)*X(45)&
            &-JVS(577)*X(46)-JVS(578)*X(47)-JVS(579)*X(52)-JVS(580)*X(54)-JVS(581)*X(55)-JVS(582)*X(56)-JVS(583)*X(57)&
            &-JVS(584)*X(58)-JVS(585)*X(59)-JVS(586)*X(60)
  X(62) = X(62)-JVS(591)*X(18)-JVS(592)*X(36)-JVS(593)*X(43)-JVS(594)*X(44)-JVS(595)*X(46)-JVS(596)*X(52)-JVS(597)*X(54)&
            &-JVS(598)*X(55)-JVS(599)*X(56)-JVS(600)*X(57)-JVS(601)*X(58)-JVS(602)*X(59)-JVS(603)*X(60)-JVS(604)*X(61)
  X(63) = X(63)-JVS(608)*X(24)-JVS(609)*X(30)-JVS(610)*X(31)-JVS(611)*X(46)-JVS(612)*X(51)-JVS(613)*X(52)-JVS(614)*X(53)&
            &-JVS(615)*X(54)-JVS(616)*X(55)-JVS(617)*X(56)-JVS(618)*X(57)-JVS(619)*X(58)-JVS(620)*X(59)-JVS(621)*X(60)&
            &-JVS(622)*X(61)-JVS(623)*X(62)
  X(64) = X(64)-JVS(626)*X(16)-JVS(627)*X(17)-JVS(628)*X(18)-JVS(629)*X(19)-JVS(630)*X(20)-JVS(631)*X(22)-JVS(632)*X(24)&
            &-JVS(633)*X(25)-JVS(634)*X(26)-JVS(635)*X(27)-JVS(636)*X(28)-JVS(637)*X(29)-JVS(638)*X(31)-JVS(639)*X(32)&
            &-JVS(640)*X(33)-JVS(641)*X(35)-JVS(642)*X(37)-JVS(643)*X(38)-JVS(644)*X(39)-JVS(645)*X(40)-JVS(646)*X(41)&
            &-JVS(647)*X(42)-JVS(648)*X(43)-JVS(649)*X(44)-JVS(650)*X(45)-JVS(651)*X(46)-JVS(652)*X(47)-JVS(653)*X(48)&
            &-JVS(654)*X(49)-JVS(655)*X(50)-JVS(656)*X(51)-JVS(657)*X(52)-JVS(658)*X(53)-JVS(659)*X(54)-JVS(660)*X(55)&
            &-JVS(661)*X(56)-JVS(662)*X(57)-JVS(663)*X(58)-JVS(664)*X(59)-JVS(665)*X(60)-JVS(666)*X(61)-JVS(667)*X(62)&
            &-JVS(668)*X(63)
  X(64) = X(64)/JVS(669)
  X(63) = (X(63)-JVS(625)*X(64))/(JVS(624))
  X(62) = (X(62)-JVS(606)*X(63)-JVS(607)*X(64))/(JVS(605))
  X(61) = (X(61)-JVS(588)*X(62)-JVS(589)*X(63)-JVS(590)*X(64))/(JVS(587))
  X(60) = (X(60)-JVS(566)*X(61)-JVS(567)*X(62)-JVS(568)*X(63)-JVS(569)*X(64))/(JVS(565))
  X(59) = (X(59)-JVS(522)*X(60)-JVS(523)*X(61)-JVS(524)*X(62)-JVS(525)*X(63)-JVS(526)*X(64))/(JVS(521))
  X(58) = (X(58)-JVS(487)*X(59)-JVS(488)*X(60)-JVS(489)*X(61)-JVS(490)*X(62)-JVS(491)*X(63)-JVS(492)*X(64))/(JVS(486))
  X(57) = (X(57)-JVS(463)*X(58)-JVS(464)*X(59)-JVS(465)*X(60)-JVS(466)*X(61)-JVS(467)*X(62)-JVS(468)*X(63)-JVS(469)&
            &*X(64))/(JVS(462))
  X(56) = (X(56)-JVS(442)*X(57)-JVS(443)*X(58)-JVS(444)*X(59)-JVS(445)*X(60)-JVS(446)*X(61)-JVS(447)*X(62)-JVS(448)&
            &*X(63)-JVS(449)*X(64))/(JVS(441))
  X(55) = (X(55)-JVS(412)*X(56)-JVS(413)*X(57)-JVS(414)*X(58)-JVS(415)*X(59)-JVS(416)*X(60)-JVS(417)*X(61)-JVS(418)&
            &*X(62)-JVS(419)*X(63)-JVS(420)*X(64))/(JVS(411))
  X(54) = (X(54)-JVS(380)*X(55)-JVS(381)*X(56)-JVS(382)*X(57)-JVS(383)*X(58)-JVS(384)*X(59)-JVS(385)*X(60)-JVS(386)&
            &*X(61)-JVS(387)*X(62)-JVS(388)*X(63)-JVS(389)*X(64))/(JVS(379))
  X(53) = (X(53)-JVS(361)*X(54)-JVS(362)*X(55)-JVS(363)*X(56)-JVS(364)*X(57)-JVS(365)*X(58)-JVS(366)*X(59)-JVS(367)&
            &*X(60)-JVS(368)*X(61)-JVS(369)*X(62)-JVS(370)*X(63)-JVS(371)*X(64))/(JVS(360))
  X(52) = (X(52)-JVS(344)*X(54)-JVS(345)*X(56)-JVS(346)*X(57)-JVS(347)*X(58)-JVS(348)*X(59)-JVS(349)*X(60)-JVS(350)&
            &*X(63)-JVS(351)*X(64))/(JVS(343))
  X(51) = (X(51)-JVS(323)*X(52)-JVS(324)*X(53)-JVS(325)*X(54)-JVS(326)*X(56)-JVS(327)*X(57)-JVS(328)*X(58)-JVS(329)&
            &*X(59)-JVS(330)*X(60)-JVS(331)*X(61)-JVS(332)*X(62)-JVS(333)*X(63)-JVS(334)*X(64))/(JVS(322))
  X(50) = (X(50)-JVS(296)*X(52)-JVS(297)*X(53)-JVS(298)*X(54)-JVS(299)*X(55)-JVS(300)*X(56)-JVS(301)*X(57)-JVS(302)&
            &*X(58)-JVS(303)*X(59)-JVS(304)*X(60)-JVS(305)*X(61)-JVS(306)*X(62)-JVS(307)*X(63)-JVS(308)*X(64))/(JVS(295))
  X(49) = (X(49)-JVS(276)*X(52)-JVS(277)*X(55)-JVS(278)*X(56)-JVS(279)*X(58)-JVS(280)*X(59)-JVS(281)*X(60)-JVS(282)&
            &*X(61)-JVS(283)*X(62)-JVS(284)*X(63)-JVS(285)*X(64))/(JVS(275))
  X(48) = (X(48)-JVS(254)*X(52)-JVS(255)*X(56)-JVS(256)*X(58)-JVS(257)*X(59)-JVS(258)*X(60)-JVS(259)*X(61)-JVS(260)&
            &*X(62)-JVS(261)*X(63)-JVS(262)*X(64))/(JVS(253))
  X(47) = (X(47)-JVS(241)*X(52)-JVS(242)*X(56)-JVS(243)*X(58)-JVS(244)*X(59)-JVS(245)*X(64))/(JVS(240))
  X(46) = (X(46)-JVS(234)*X(52)-JVS(235)*X(56)-JVS(236)*X(58)-JVS(237)*X(59)-JVS(238)*X(64))/(JVS(233))
  X(45) = (X(45)-JVS(228)*X(56)-JVS(229)*X(59)-JVS(230)*X(60)-JVS(231)*X(63)-JVS(232)*X(64))/(JVS(227))
  X(44) = (X(44)-JVS(219)*X(52)-JVS(220)*X(56)-JVS(221)*X(58)-JVS(222)*X(64))/(JVS(218))
  X(43) = (X(43)-JVS(214)*X(52)-JVS(215)*X(56)-JVS(216)*X(58)-JVS(217)*X(64))/(JVS(213))
  X(42) = (X(42)-JVS(209)*X(52)-JVS(210)*X(56)-JVS(211)*X(58)-JVS(212)*X(64))/(JVS(208))
  X(41) = (X(41)-JVS(204)*X(52)-JVS(205)*X(56)-JVS(206)*X(58)-JVS(207)*X(64))/(JVS(203))
  X(40) = (X(40)-JVS(193)*X(45)-JVS(194)*X(47)-JVS(195)*X(48)-JVS(196)*X(49)-JVS(197)*X(50)-JVS(198)*X(51)-JVS(199)&
            &*X(56)-JVS(200)*X(59)-JVS(201)*X(60)-JVS(202)*X(64))/(JVS(192))
  X(39) = (X(39)-JVS(187)*X(45)-JVS(188)*X(52)-JVS(189)*X(63)-JVS(190)*X(64))/(JVS(186))
  X(38) = (X(38)-JVS(171)*X(39)-JVS(172)*X(41)-JVS(173)*X(42)-JVS(174)*X(43)-JVS(175)*X(44)-JVS(176)*X(46)-JVS(177)&
            &*X(47)-JVS(178)*X(49)-JVS(179)*X(50)-JVS(180)*X(51)-JVS(181)*X(52)-JVS(182)*X(56)-JVS(183)*X(58)-JVS(184)&
            &*X(64))/(JVS(170))
  X(37) = (X(37)-JVS(164)*X(51)-JVS(165)*X(53)-JVS(166)*X(60)-JVS(167)*X(63)-JVS(168)*X(64))/(JVS(163))
  X(36) = (X(36)-JVS(159)*X(59)-JVS(160)*X(61)-JVS(161)*X(64))/(JVS(158))
  X(35) = (X(35)-JVS(155)*X(54)-JVS(156)*X(59)-JVS(157)*X(64))/(JVS(154))
  X(34) = (X(34)-JVS(149)*X(45)-JVS(150)*X(56)-JVS(151)*X(59)-JVS(152)*X(60)-JVS(153)*X(64))/(JVS(148))
  X(33) = (X(33)-JVS(144)*X(39)-JVS(145)*X(47)-JVS(146)*X(52)-JVS(147)*X(64))/(JVS(143))
  X(32) = (X(32)-JVS(138)*X(55)-JVS(139)*X(60)-JVS(140)*X(62)-JVS(141)*X(64))/(JVS(137))
  X(31) = (X(31)-JVS(134)*X(51)-JVS(135)*X(60)-JVS(136)*X(63))/(JVS(133))
  X(30) = (X(30)-JVS(131)*X(63)-JVS(132)*X(64))/(JVS(130))
  X(29) = (X(29)-JVS(125)*X(59)-JVS(126)*X(60)-JVS(127)*X(64))/(JVS(124))
  X(28) = (X(28)-JVS(120)*X(54)-JVS(121)*X(57)-JVS(122)*X(60)-JVS(123)*X(64))/(JVS(119))
  X(27) = (X(27)-JVS(113)*X(53)-JVS(114)*X(54)-JVS(115)*X(55)-JVS(116)*X(57)-JVS(117)*X(60)-JVS(118)*X(64))/(JVS(112))
  X(26) = (X(26)-JVS(107)*X(31)-JVS(108)*X(41)-JVS(109)*X(52)-JVS(110)*X(63)-JVS(111)*X(64))/(JVS(106))
  X(25) = (X(25)-JVS(103)*X(58)-JVS(104)*X(60)-JVS(105)*X(64))/(JVS(102))
  X(24) = (X(24)-JVS(99)*X(59)-JVS(100)*X(63)-JVS(101)*X(64))/(JVS(98))
  X(23) = (X(23)-JVS(96)*X(57)-JVS(97)*X(59))/(JVS(95))
  X(22) = (X(22)-JVS(94)*X(64))/(JVS(93))
  X(21) = (X(21)-JVS(91)*X(56)-JVS(92)*X(59))/(JVS(90))
  X(20) = (X(20)-JVS(89)*X(64))/(JVS(88))
  X(19) = (X(19)-JVS(86)*X(53)-JVS(87)*X(64))/(JVS(85))
  X(18) = (X(18)-JVS(84)*X(64))/(JVS(83))
  X(17) = (X(17)-JVS(82)*X(64))/(JVS(81))
  X(16) = (X(16)-JVS(80)*X(52))/(JVS(79))
  X(15) = (X(15)-JVS(76)*X(52)-JVS(77)*X(56)-JVS(78)*X(64))/(JVS(75))
  X(14) = (X(14)-JVS(69)*X(15)-JVS(70)*X(44)-JVS(71)*X(52)-JVS(72)*X(56)-JVS(73)*X(58)-JVS(74)*X(64))/(JVS(68))
  X(13) = (X(13)-JVS(60)*X(14)-JVS(61)*X(15)-JVS(62)*X(44)-JVS(63)*X(46)-JVS(64)*X(52)-JVS(65)*X(56)-JVS(66)*X(58)&
            &-JVS(67)*X(64))/(JVS(59))
  X(12) = (X(12)-JVS(51)*X(13)-JVS(52)*X(15)-JVS(53)*X(44)-JVS(54)*X(46)-JVS(55)*X(52)-JVS(56)*X(56)-JVS(57)*X(58)&
            &-JVS(58)*X(64))/(JVS(50))
  X(11) = (X(11)-JVS(42)*X(12)-JVS(43)*X(15)-JVS(44)*X(44)-JVS(45)*X(46)-JVS(46)*X(52)-JVS(47)*X(56)-JVS(48)*X(58)&
            &-JVS(49)*X(64))/(JVS(41))
  X(10) = (X(10)-JVS(39)*X(11)-JVS(40)*X(64))/(JVS(38))
  X(9) = (X(9)-JVS(37)*X(64))/(JVS(36))
  X(8) = (X(8)-JVS(34)*X(9)-JVS(35)*X(64))/(JVS(33))
  X(7) = (X(7)-JVS(31)*X(8)-JVS(32)*X(64))/(JVS(30))
  X(6) = (X(6)-JVS(29)*X(64))/(JVS(28))
  X(5) = (X(5)-JVS(23)*X(6)-JVS(24)*X(7)-JVS(25)*X(17)-JVS(26)*X(22)-JVS(27)*X(64))/(JVS(22))
  X(4) = (X(4)-JVS(17)*X(5)-JVS(18)*X(6)-JVS(19)*X(17)-JVS(20)*X(22)-JVS(21)*X(64))/(JVS(16))
  X(3) = (X(3)-JVS(11)*X(4)-JVS(12)*X(6)-JVS(13)*X(17)-JVS(14)*X(22)-JVS(15)*X(64))/(JVS(10))
  X(2) = (X(2)-JVS(5)*X(3)-JVS(6)*X(6)-JVS(7)*X(17)-JVS(8)*X(22)-JVS(9)*X(64))/(JVS(4))
  X(1) = (X(1)-JVS(2)*X(2)-JVS(3)*X(64))/(JVS(1))
      
END SUBROUTINE KppSolve

! End of KppSolve function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! KppSolveTR - sparse, transposed back substitution
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      X         - Vector for variables
!      XX        - Vector for output variables
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE KppSolveTR ( JVS, X, XX )

! JVS - sparse Jacobian of variables
  REAL(kind=sp) :: JVS(LU_NONZERO)
! X - Vector for variables
  REAL(kind=sp) :: X(NVAR)
! XX - Vector for output variables
  REAL(kind=sp) :: XX(NVAR)

  XX(1) = X(1)/JVS(1)
  XX(2) = (X(2)-JVS(2)*XX(1))/(JVS(4))
  XX(3) = (X(3)-JVS(5)*XX(2))/(JVS(10))
  XX(4) = (X(4)-JVS(11)*XX(3))/(JVS(16))
  XX(5) = (X(5)-JVS(17)*XX(4))/(JVS(22))
  XX(6) = (X(6)-JVS(6)*XX(2)-JVS(12)*XX(3)-JVS(18)*XX(4)-JVS(23)*XX(5))/(JVS(28))
  XX(7) = (X(7)-JVS(24)*XX(5))/(JVS(30))
  XX(8) = (X(8)-JVS(31)*XX(7))/(JVS(33))
  XX(9) = (X(9)-JVS(34)*XX(8))/(JVS(36))
  XX(10) = X(10)/JVS(38)
  XX(11) = (X(11)-JVS(39)*XX(10))/(JVS(41))
  XX(12) = (X(12)-JVS(42)*XX(11))/(JVS(50))
  XX(13) = (X(13)-JVS(51)*XX(12))/(JVS(59))
  XX(14) = (X(14)-JVS(60)*XX(13))/(JVS(68))
  XX(15) = (X(15)-JVS(43)*XX(11)-JVS(52)*XX(12)-JVS(61)*XX(13)-JVS(69)*XX(14))/(JVS(75))
  XX(16) = X(16)/JVS(79)
  XX(17) = (X(17)-JVS(7)*XX(2)-JVS(13)*XX(3)-JVS(19)*XX(4)-JVS(25)*XX(5))/(JVS(81))
  XX(18) = X(18)/JVS(83)
  XX(19) = X(19)/JVS(85)
  XX(20) = X(20)/JVS(88)
  XX(21) = X(21)/JVS(90)
  XX(22) = (X(22)-JVS(8)*XX(2)-JVS(14)*XX(3)-JVS(20)*XX(4)-JVS(26)*XX(5))/(JVS(93))
  XX(23) = X(23)/JVS(95)
  XX(24) = X(24)/JVS(98)
  XX(25) = X(25)/JVS(102)
  XX(26) = X(26)/JVS(106)
  XX(27) = X(27)/JVS(112)
  XX(28) = X(28)/JVS(119)
  XX(29) = X(29)/JVS(124)
  XX(30) = X(30)/JVS(130)
  XX(31) = (X(31)-JVS(107)*XX(26))/(JVS(133))
  XX(32) = X(32)/JVS(137)
  XX(33) = X(33)/JVS(143)
  XX(34) = X(34)/JVS(148)
  XX(35) = X(35)/JVS(154)
  XX(36) = X(36)/JVS(158)
  XX(37) = X(37)/JVS(163)
  XX(38) = X(38)/JVS(170)
  XX(39) = (X(39)-JVS(144)*XX(33)-JVS(171)*XX(38))/(JVS(186))
  XX(40) = X(40)/JVS(192)
  XX(41) = (X(41)-JVS(108)*XX(26)-JVS(172)*XX(38))/(JVS(203))
  XX(42) = (X(42)-JVS(173)*XX(38))/(JVS(208))
  XX(43) = (X(43)-JVS(174)*XX(38))/(JVS(213))
  XX(44) = (X(44)-JVS(44)*XX(11)-JVS(53)*XX(12)-JVS(62)*XX(13)-JVS(70)*XX(14)-JVS(175)*XX(38))/(JVS(218))
  XX(45) = (X(45)-JVS(149)*XX(34)-JVS(187)*XX(39)-JVS(193)*XX(40))/(JVS(227))
  XX(46) = (X(46)-JVS(45)*XX(11)-JVS(54)*XX(12)-JVS(63)*XX(13)-JVS(176)*XX(38))/(JVS(233))
  XX(47) = (X(47)-JVS(145)*XX(33)-JVS(177)*XX(38)-JVS(194)*XX(40))/(JVS(240))
  XX(48) = (X(48)-JVS(195)*XX(40))/(JVS(253))
  XX(49) = (X(49)-JVS(178)*XX(38)-JVS(196)*XX(40))/(JVS(275))
  XX(50) = (X(50)-JVS(179)*XX(38)-JVS(197)*XX(40))/(JVS(295))
  XX(51) = (X(51)-JVS(134)*XX(31)-JVS(164)*XX(37)-JVS(180)*XX(38)-JVS(198)*XX(40))/(JVS(322))
  XX(52) = (X(52)-JVS(46)*XX(11)-JVS(55)*XX(12)-JVS(64)*XX(13)-JVS(71)*XX(14)-JVS(76)*XX(15)-JVS(80)*XX(16)-JVS(109)&
             &*XX(26)-JVS(146)*XX(33)-JVS(181)*XX(38)-JVS(188)*XX(39)-JVS(204)*XX(41)-JVS(209)*XX(42)-JVS(214)*XX(43)&
             &-JVS(219)*XX(44)-JVS(234)*XX(46)-JVS(241)*XX(47)-JVS(254)*XX(48)-JVS(276)*XX(49)-JVS(296)*XX(50)-JVS(323)&
             &*XX(51))/(JVS(343))
  XX(53) = (X(53)-JVS(86)*XX(19)-JVS(113)*XX(27)-JVS(165)*XX(37)-JVS(297)*XX(50)-JVS(324)*XX(51))/(JVS(360))
  XX(54) = (X(54)-JVS(114)*XX(27)-JVS(120)*XX(28)-JVS(155)*XX(35)-JVS(298)*XX(50)-JVS(325)*XX(51)-JVS(344)*XX(52)&
             &-JVS(361)*XX(53))/(JVS(379))
  XX(55) = (X(55)-JVS(115)*XX(27)-JVS(138)*XX(32)-JVS(277)*XX(49)-JVS(299)*XX(50)-JVS(362)*XX(53)-JVS(380)*XX(54))&
             &/(JVS(411))
  XX(56) = (X(56)-JVS(47)*XX(11)-JVS(56)*XX(12)-JVS(65)*XX(13)-JVS(72)*XX(14)-JVS(77)*XX(15)-JVS(91)*XX(21)-JVS(150)&
             &*XX(34)-JVS(182)*XX(38)-JVS(199)*XX(40)-JVS(205)*XX(41)-JVS(210)*XX(42)-JVS(215)*XX(43)-JVS(220)*XX(44)&
             &-JVS(228)*XX(45)-JVS(235)*XX(46)-JVS(242)*XX(47)-JVS(255)*XX(48)-JVS(278)*XX(49)-JVS(300)*XX(50)-JVS(326)&
             &*XX(51)-JVS(345)*XX(52)-JVS(363)*XX(53)-JVS(381)*XX(54)-JVS(412)*XX(55))/(JVS(441))
  XX(57) = (X(57)-JVS(96)*XX(23)-JVS(116)*XX(27)-JVS(121)*XX(28)-JVS(301)*XX(50)-JVS(327)*XX(51)-JVS(346)*XX(52)&
             &-JVS(364)*XX(53)-JVS(382)*XX(54)-JVS(413)*XX(55)-JVS(442)*XX(56))/(JVS(462))
  XX(58) = (X(58)-JVS(48)*XX(11)-JVS(57)*XX(12)-JVS(66)*XX(13)-JVS(73)*XX(14)-JVS(103)*XX(25)-JVS(183)*XX(38)-JVS(206)&
             &*XX(41)-JVS(211)*XX(42)-JVS(216)*XX(43)-JVS(221)*XX(44)-JVS(236)*XX(46)-JVS(243)*XX(47)-JVS(256)*XX(48)&
             &-JVS(279)*XX(49)-JVS(302)*XX(50)-JVS(328)*XX(51)-JVS(347)*XX(52)-JVS(365)*XX(53)-JVS(383)*XX(54)-JVS(414)&
             &*XX(55)-JVS(443)*XX(56)-JVS(463)*XX(57))/(JVS(486))
  XX(59) = (X(59)-JVS(92)*XX(21)-JVS(97)*XX(23)-JVS(99)*XX(24)-JVS(125)*XX(29)-JVS(151)*XX(34)-JVS(156)*XX(35)-JVS(159)&
             &*XX(36)-JVS(200)*XX(40)-JVS(229)*XX(45)-JVS(237)*XX(46)-JVS(244)*XX(47)-JVS(257)*XX(48)-JVS(280)*XX(49)&
             &-JVS(303)*XX(50)-JVS(329)*XX(51)-JVS(348)*XX(52)-JVS(366)*XX(53)-JVS(384)*XX(54)-JVS(415)*XX(55)-JVS(444)&
             &*XX(56)-JVS(464)*XX(57)-JVS(487)*XX(58))/(JVS(521))
  XX(60) = (X(60)-JVS(104)*XX(25)-JVS(117)*XX(27)-JVS(122)*XX(28)-JVS(126)*XX(29)-JVS(135)*XX(31)-JVS(139)*XX(32)&
             &-JVS(152)*XX(34)-JVS(166)*XX(37)-JVS(201)*XX(40)-JVS(230)*XX(45)-JVS(258)*XX(48)-JVS(281)*XX(49)-JVS(304)&
             &*XX(50)-JVS(330)*XX(51)-JVS(349)*XX(52)-JVS(367)*XX(53)-JVS(385)*XX(54)-JVS(416)*XX(55)-JVS(445)*XX(56)&
             &-JVS(465)*XX(57)-JVS(488)*XX(58)-JVS(522)*XX(59))/(JVS(565))
  XX(61) = (X(61)-JVS(160)*XX(36)-JVS(259)*XX(48)-JVS(282)*XX(49)-JVS(305)*XX(50)-JVS(331)*XX(51)-JVS(368)*XX(53)&
             &-JVS(386)*XX(54)-JVS(417)*XX(55)-JVS(446)*XX(56)-JVS(466)*XX(57)-JVS(489)*XX(58)-JVS(523)*XX(59)-JVS(566)&
             &*XX(60))/(JVS(587))
  XX(62) = (X(62)-JVS(140)*XX(32)-JVS(260)*XX(48)-JVS(283)*XX(49)-JVS(306)*XX(50)-JVS(332)*XX(51)-JVS(369)*XX(53)&
             &-JVS(387)*XX(54)-JVS(418)*XX(55)-JVS(447)*XX(56)-JVS(467)*XX(57)-JVS(490)*XX(58)-JVS(524)*XX(59)-JVS(567)&
             &*XX(60)-JVS(588)*XX(61))/(JVS(605))
  XX(63) = (X(63)-JVS(100)*XX(24)-JVS(110)*XX(26)-JVS(131)*XX(30)-JVS(136)*XX(31)-JVS(167)*XX(37)-JVS(189)*XX(39)&
             &-JVS(231)*XX(45)-JVS(261)*XX(48)-JVS(284)*XX(49)-JVS(307)*XX(50)-JVS(333)*XX(51)-JVS(350)*XX(52)-JVS(370)&
             &*XX(53)-JVS(388)*XX(54)-JVS(419)*XX(55)-JVS(448)*XX(56)-JVS(468)*XX(57)-JVS(491)*XX(58)-JVS(525)*XX(59)&
             &-JVS(568)*XX(60)-JVS(589)*XX(61)-JVS(606)*XX(62))/(JVS(624))
  XX(64) = (X(64)-JVS(3)*XX(1)-JVS(9)*XX(2)-JVS(15)*XX(3)-JVS(21)*XX(4)-JVS(27)*XX(5)-JVS(29)*XX(6)-JVS(32)*XX(7)&
             &-JVS(35)*XX(8)-JVS(37)*XX(9)-JVS(40)*XX(10)-JVS(49)*XX(11)-JVS(58)*XX(12)-JVS(67)*XX(13)-JVS(74)*XX(14)&
             &-JVS(78)*XX(15)-JVS(82)*XX(17)-JVS(84)*XX(18)-JVS(87)*XX(19)-JVS(89)*XX(20)-JVS(94)*XX(22)-JVS(101)*XX(24)&
             &-JVS(105)*XX(25)-JVS(111)*XX(26)-JVS(118)*XX(27)-JVS(123)*XX(28)-JVS(127)*XX(29)-JVS(132)*XX(30)-JVS(141)&
             &*XX(32)-JVS(147)*XX(33)-JVS(153)*XX(34)-JVS(157)*XX(35)-JVS(161)*XX(36)-JVS(168)*XX(37)-JVS(184)*XX(38)&
             &-JVS(190)*XX(39)-JVS(202)*XX(40)-JVS(207)*XX(41)-JVS(212)*XX(42)-JVS(217)*XX(43)-JVS(222)*XX(44)-JVS(232)&
             &*XX(45)-JVS(238)*XX(46)-JVS(245)*XX(47)-JVS(262)*XX(48)-JVS(285)*XX(49)-JVS(308)*XX(50)-JVS(334)*XX(51)&
             &-JVS(351)*XX(52)-JVS(371)*XX(53)-JVS(389)*XX(54)-JVS(420)*XX(55)-JVS(449)*XX(56)-JVS(469)*XX(57)-JVS(492)&
             &*XX(58)-JVS(526)*XX(59)-JVS(569)*XX(60)-JVS(590)*XX(61)-JVS(607)*XX(62)-JVS(625)*XX(63))/(JVS(669))
  XX(64) = XX(64)
  XX(63) = XX(63)-JVS(668)*XX(64)
  XX(62) = XX(62)-JVS(623)*XX(63)-JVS(667)*XX(64)
  XX(61) = XX(61)-JVS(604)*XX(62)-JVS(622)*XX(63)-JVS(666)*XX(64)
  XX(60) = XX(60)-JVS(586)*XX(61)-JVS(603)*XX(62)-JVS(621)*XX(63)-JVS(665)*XX(64)
  XX(59) = XX(59)-JVS(564)*XX(60)-JVS(585)*XX(61)-JVS(602)*XX(62)-JVS(620)*XX(63)-JVS(664)*XX(64)
  XX(58) = XX(58)-JVS(520)*XX(59)-JVS(563)*XX(60)-JVS(584)*XX(61)-JVS(601)*XX(62)-JVS(619)*XX(63)-JVS(663)*XX(64)
  XX(57) = XX(57)-JVS(485)*XX(58)-JVS(519)*XX(59)-JVS(562)*XX(60)-JVS(583)*XX(61)-JVS(600)*XX(62)-JVS(618)*XX(63)&
             &-JVS(662)*XX(64)
  XX(56) = XX(56)-JVS(461)*XX(57)-JVS(484)*XX(58)-JVS(518)*XX(59)-JVS(561)*XX(60)-JVS(582)*XX(61)-JVS(599)*XX(62)&
             &-JVS(617)*XX(63)-JVS(661)*XX(64)
  XX(55) = XX(55)-JVS(440)*XX(56)-JVS(460)*XX(57)-JVS(483)*XX(58)-JVS(517)*XX(59)-JVS(560)*XX(60)-JVS(581)*XX(61)&
             &-JVS(598)*XX(62)-JVS(616)*XX(63)-JVS(660)*XX(64)
  XX(54) = XX(54)-JVS(410)*XX(55)-JVS(439)*XX(56)-JVS(459)*XX(57)-JVS(482)*XX(58)-JVS(516)*XX(59)-JVS(559)*XX(60)&
             &-JVS(580)*XX(61)-JVS(597)*XX(62)-JVS(615)*XX(63)-JVS(659)*XX(64)
  XX(53) = XX(53)-JVS(378)*XX(54)-JVS(409)*XX(55)-JVS(438)*XX(56)-JVS(458)*XX(57)-JVS(481)*XX(58)-JVS(515)*XX(59)&
             &-JVS(558)*XX(60)-JVS(614)*XX(63)-JVS(658)*XX(64)
  XX(52) = XX(52)-JVS(359)*XX(53)-JVS(377)*XX(54)-JVS(408)*XX(55)-JVS(437)*XX(56)-JVS(457)*XX(57)-JVS(480)*XX(58)&
             &-JVS(514)*XX(59)-JVS(557)*XX(60)-JVS(579)*XX(61)-JVS(596)*XX(62)-JVS(613)*XX(63)-JVS(657)*XX(64)
  XX(51) = XX(51)-JVS(358)*XX(53)-JVS(407)*XX(55)-JVS(436)*XX(56)-JVS(479)*XX(58)-JVS(513)*XX(59)-JVS(556)*XX(60)&
             &-JVS(612)*XX(63)-JVS(656)*XX(64)
  XX(50) = XX(50)-JVS(357)*XX(53)-JVS(435)*XX(56)-JVS(456)*XX(57)-JVS(478)*XX(58)-JVS(512)*XX(59)-JVS(555)*XX(60)&
             &-JVS(655)*XX(64)
  XX(49) = XX(49)-JVS(356)*XX(53)-JVS(376)*XX(54)-JVS(434)*XX(56)-JVS(477)*XX(58)-JVS(511)*XX(59)-JVS(554)*XX(60)&
             &-JVS(654)*XX(64)
  XX(48) = XX(48)-JVS(274)*XX(49)-JVS(294)*XX(50)-JVS(321)*XX(51)-JVS(433)*XX(56)-JVS(510)*XX(59)-JVS(553)*XX(60)&
             &-JVS(653)*XX(64)
  XX(47) = XX(47)-JVS(252)*XX(48)-JVS(273)*XX(49)-JVS(293)*XX(50)-JVS(320)*XX(51)-JVS(342)*XX(52)-JVS(375)*XX(54)&
             &-JVS(406)*XX(55)-JVS(432)*XX(56)-JVS(455)*XX(57)-JVS(509)*XX(59)-JVS(552)*XX(60)-JVS(578)*XX(61)-JVS(652)&
             &*XX(64)
  XX(46) = XX(46)-JVS(239)*XX(47)-JVS(251)*XX(48)-JVS(272)*XX(49)-JVS(319)*XX(51)-JVS(341)*XX(52)-JVS(374)*XX(54)&
             &-JVS(405)*XX(55)-JVS(431)*XX(56)-JVS(476)*XX(58)-JVS(508)*XX(59)-JVS(551)*XX(60)-JVS(577)*XX(61)-JVS(595)&
             &*XX(62)-JVS(611)*XX(63)-JVS(651)*XX(64)
  XX(45) = XX(45)-JVS(250)*XX(48)-JVS(271)*XX(49)-JVS(318)*XX(51)-JVS(340)*XX(52)-JVS(404)*XX(55)-JVS(430)*XX(56)&
             &-JVS(454)*XX(57)-JVS(507)*XX(59)-JVS(550)*XX(60)-JVS(576)*XX(61)-JVS(650)*XX(64)
  XX(44) = XX(44)-JVS(249)*XX(48)-JVS(270)*XX(49)-JVS(317)*XX(51)-JVS(339)*XX(52)-JVS(373)*XX(54)-JVS(403)*XX(55)&
             &-JVS(429)*XX(56)-JVS(475)*XX(58)-JVS(506)*XX(59)-JVS(549)*XX(60)-JVS(575)*XX(61)-JVS(594)*XX(62)-JVS(649)&
             &*XX(64)
  XX(43) = XX(43)-JVS(269)*XX(49)-JVS(292)*XX(50)-JVS(316)*XX(51)-JVS(338)*XX(52)-JVS(402)*XX(55)-JVS(428)*XX(56)&
             &-JVS(474)*XX(58)-JVS(505)*XX(59)-JVS(548)*XX(60)-JVS(574)*XX(61)-JVS(593)*XX(62)-JVS(648)*XX(64)
  XX(42) = XX(42)-JVS(268)*XX(49)-JVS(291)*XX(50)-JVS(315)*XX(51)-JVS(337)*XX(52)-JVS(401)*XX(55)-JVS(427)*XX(56)&
             &-JVS(473)*XX(58)-JVS(504)*XX(59)-JVS(547)*XX(60)-JVS(573)*XX(61)-JVS(647)*XX(64)
  XX(41) = XX(41)-JVS(267)*XX(49)-JVS(314)*XX(51)-JVS(336)*XX(52)-JVS(400)*XX(55)-JVS(426)*XX(56)-JVS(472)*XX(58)&
             &-JVS(503)*XX(59)-JVS(546)*XX(60)-JVS(646)*XX(64)
  XX(40) = XX(40)-JVS(425)*XX(56)-JVS(502)*XX(59)-JVS(645)*XX(64)
  XX(39) = XX(39)-JVS(266)*XX(49)-JVS(313)*XX(51)-JVS(335)*XX(52)-JVS(399)*XX(55)-JVS(453)*XX(57)-JVS(545)*XX(60)&
             &-JVS(644)*XX(64)
  XX(38) = XX(38)-JVS(544)*XX(60)-JVS(643)*XX(64)
  XX(37) = XX(37)-JVS(312)*XX(51)-JVS(355)*XX(53)-JVS(398)*XX(55)-JVS(543)*XX(60)-JVS(642)*XX(64)
  XX(36) = XX(36)-JVS(248)*XX(48)-JVS(265)*XX(49)-JVS(290)*XX(50)-JVS(397)*XX(55)-JVS(501)*XX(59)-JVS(542)*XX(60)&
             &-JVS(572)*XX(61)-JVS(592)*XX(62)
  XX(35) = XX(35)-JVS(289)*XX(50)-JVS(372)*XX(54)-JVS(396)*XX(55)-JVS(424)*XX(56)-JVS(500)*XX(59)-JVS(541)*XX(60)&
             &-JVS(641)*XX(64)
  XX(34) = XX(34)-JVS(226)*XX(45)-JVS(247)*XX(48)-JVS(499)*XX(59)-JVS(540)*XX(60)
  XX(33) = XX(33)-JVS(169)*XX(38)-JVS(395)*XX(55)-JVS(452)*XX(57)-JVS(539)*XX(60)-JVS(640)*XX(64)
  XX(32) = XX(32)-JVS(264)*XX(49)-JVS(288)*XX(50)-JVS(394)*XX(55)-JVS(538)*XX(60)-JVS(639)*XX(64)
  XX(31) = XX(31)-JVS(162)*XX(37)-JVS(311)*XX(51)-JVS(498)*XX(59)-JVS(537)*XX(60)-JVS(610)*XX(63)-JVS(638)*XX(64)
  XX(30) = XX(30)-JVS(185)*XX(39)-JVS(225)*XX(45)-JVS(246)*XX(48)-JVS(497)*XX(59)-JVS(536)*XX(60)-JVS(571)*XX(61)&
             &-JVS(609)*XX(63)
  XX(29) = XX(29)-JVS(423)*XX(56)-JVS(496)*XX(59)-JVS(535)*XX(60)-JVS(637)*XX(64)
  XX(28) = XX(28)-JVS(354)*XX(53)-JVS(451)*XX(57)-JVS(636)*XX(64)
  XX(27) = XX(27)-JVS(353)*XX(53)-JVS(635)*XX(64)
  XX(26) = XX(26)-JVS(534)*XX(60)-JVS(634)*XX(64)
  XX(25) = XX(25)-JVS(471)*XX(58)-JVS(533)*XX(60)-JVS(633)*XX(64)
  XX(24) = XX(24)-JVS(495)*XX(59)-JVS(608)*XX(63)-JVS(632)*XX(64)
  XX(23) = XX(23)-JVS(352)*XX(53)-JVS(422)*XX(56)-JVS(450)*XX(57)-JVS(494)*XX(59)
  XX(22) = XX(22)-JVS(129)*XX(30)-JVS(142)*XX(33)-JVS(224)*XX(45)-JVS(393)*XX(55)-JVS(532)*XX(60)-JVS(570)*XX(61)&
             &-JVS(631)*XX(64)
  XX(21) = XX(21)-JVS(191)*XX(40)-JVS(421)*XX(56)-JVS(493)*XX(59)
  XX(20) = XX(20)-JVS(263)*XX(49)-JVS(287)*XX(50)-JVS(310)*XX(51)-JVS(392)*XX(55)-JVS(531)*XX(60)-JVS(630)*XX(64)
  XX(19) = XX(19)-JVS(309)*XX(51)-JVS(530)*XX(60)-JVS(629)*XX(64)
  XX(18) = XX(18)-JVS(286)*XX(50)-JVS(391)*XX(55)-JVS(529)*XX(60)-JVS(591)*XX(62)-JVS(628)*XX(64)
  XX(17) = XX(17)-JVS(128)*XX(30)-JVS(223)*XX(45)-JVS(390)*XX(55)-JVS(528)*XX(60)-JVS(627)*XX(64)
  XX(16) = XX(16)-JVS(470)*XX(58)-JVS(527)*XX(60)-JVS(626)*XX(64)
  XX(15) = XX(15)
  XX(14) = XX(14)
  XX(13) = XX(13)
  XX(12) = XX(12)
  XX(11) = XX(11)
  XX(10) = XX(10)
  XX(9) = XX(9)
  XX(8) = XX(8)
  XX(7) = XX(7)
  XX(6) = XX(6)
  XX(5) = XX(5)
  XX(4) = XX(4)
  XX(3) = XX(3)
  XX(2) = XX(2)
  XX(1) = XX(1)
      
END SUBROUTINE KppSolveTR

! End of KppSolveTR function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE cbm5_SOA_LinearAlgebra

