! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Linear Algebra Data and Routines File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : cbm7_strato_SOA_LinearAlgebra.f90
! Time                 : Mon Nov 11 16:35:56 2024
! Working directory    : /fmi/scratch/project_2001411/risto/puhtiruns/testCB7/silam_dev-testCB7-maxiter/kpp/cbm7_strato_SOA
! Equation file        : cbm7_strato_SOA.kpp
! Output root filename : cbm7_strato_SOA
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE cbm7_strato_SOA_LinearAlgebra

  USE cbm7_strato_SOA_Parameters
  USE cbm7_strato_SOA_JacobianSP

  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! SPARSE_UTIL - SPARSE utility functions
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppDecomp( JVS, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse LU factorization
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm7_strato_SOA_Parameters
  USE cbm7_strato_SOA_JacobianSP

      INTEGER  :: IER
      REAL(kind=sp) :: JVS(LU_NONZERO), W(NVAR), a
      INTEGER  :: k, kk, j, jj

      a = 0. ! mz_rs_20050606
      IER = 0
      DO k=1,NVAR
        ! mz_rs_20050606: don't check if real value == 0
        ! IF ( JVS( LU_DIAG(k) ) .EQ. 0. ) THEN
        IF ( ABS(JVS(LU_DIAG(k))) < TINY(a) ) THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              W( LU_ICOL(kk) ) = JVS(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            a = -W(j) / JVS( LU_DIAG(j) )
            W(j) = -a
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               W( LU_ICOL(jj) ) = W( LU_ICOL(jj) ) + a*JVS(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVS(kk) = W( LU_ICOL(kk) )
         END DO
      END DO
      
END SUBROUTINE KppDecomp


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppDecompCmplx( JVS, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse LU factorization, complex
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm7_strato_SOA_Parameters
  USE cbm7_strato_SOA_JacobianSP

      INTEGER        :: IER
      DOUBLE COMPLEX :: JVS(LU_NONZERO), W(NVAR), a
      REAL(kind=sp)  :: b = 0.0
      INTEGER        :: k, kk, j, jj

      IER = 0
      DO k=1,NVAR
        IF ( ABS(JVS(LU_DIAG(k))) < TINY(b) ) THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              W( LU_ICOL(kk) ) = JVS(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            a = -W(j) / JVS( LU_DIAG(j) )
            W(j) = -a
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               W( LU_ICOL(jj) ) = W( LU_ICOL(jj) ) + a*JVS(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVS(kk) = W( LU_ICOL(kk) )
         END DO
      END DO
      
END SUBROUTINE KppDecompCmplx


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppDecompCmplxR( JVSR, JVSI, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!    Sparse LU factorization, complex
!   (Real and Imaginary parts are used instead of complex data type)     
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm7_strato_SOA_Parameters
  USE cbm7_strato_SOA_JacobianSP

      INTEGER       :: IER
      REAL(kind=sp) :: JVSR(LU_NONZERO), JVSI(LU_NONZERO) 
      REAL(kind=sp) :: WR(NVAR), WI(NVAR), ar, ai, den
      INTEGER       :: k, kk, j, jj

      IER = 0
      ar  = 0.0
      DO k=1,NVAR
        IF (  ( ABS(JVSR(LU_DIAG(k))) < TINY(ar) ) .AND. &
              ( ABS(JVSI(LU_DIAG(k))) < TINY(ar) ) )  THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              WR( LU_ICOL(kk) ) = JVSR(kk)
              WI( LU_ICOL(kk) ) = JVSI(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            den = JVSR(LU_DIAG(j))**2 + JVSI(LU_DIAG(j))**2
            ar = -(WR(j)*JVSR(LU_DIAG(j)) + WI(j)*JVSI(LU_DIAG(j)))/den
            ai = -(WI(j)*JVSR(LU_DIAG(j)) - WR(j)*JVSI(LU_DIAG(j)))/den
            WR(j) = -ar
            WI(j) = -ai
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               WR( LU_ICOL(jj) ) = WR( LU_ICOL(jj) ) + ar*JVSR(jj) - ai*JVSI(jj)
               WI( LU_ICOL(jj) ) = WI( LU_ICOL(jj) ) + ar*JVSI(jj) + ai*JVSR(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVSR(kk) = WR( LU_ICOL(kk) )
            JVSI(kk) = WI( LU_ICOL(kk) )
         END DO
      END DO

END SUBROUTINE KppDecompCmplxR


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveIndirect( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse solve subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm7_strato_SOA_Parameters
  USE cbm7_strato_SOA_JacobianSP

      INTEGER  :: i, j
      REAL(kind=sp) :: JVS(LU_NONZERO), X(NVAR), sum

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1 
             X(i) = X(i) - JVS(j)*X(LU_ICOL(j));
         END DO  
      END DO

      DO i=NVAR,1,-1
        sum = X(i);
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
          sum = sum - JVS(j)*X(LU_ICOL(j));
        END DO
        X(i) = sum/JVS(LU_DIAG(i));
      END DO
      
END SUBROUTINE KppSolveIndirect


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveTRIndirect( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve transpose subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm7_strato_SOA_Parameters
  USE cbm7_strato_SOA_JacobianSP

      INTEGER       :: i, j
      REAL(kind=sp) :: JVS(LU_NONZERO), X(NVAR)

      DO i=1,NVAR
        X(i) = X(i)/JVS(LU_DIAG(i))
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
	  X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
	END DO
      END DO

      DO i=NVAR, 1, -1
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
	  X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
	END DO
      END DO
      
END SUBROUTINE KppSolveTRIndirect


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveCmplx( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm7_strato_SOA_Parameters
  USE cbm7_strato_SOA_JacobianSP

      INTEGER        :: i, j
      DOUBLE COMPLEX :: JVS(LU_NONZERO), X(NVAR), sum

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1 
             X(i) = X(i) - JVS(j)*X(LU_ICOL(j));
         END DO  
      END DO

      DO i=NVAR,1,-1
        sum = X(i);
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
          sum = sum - JVS(j)*X(LU_ICOL(j));
        END DO
        X(i) = sum/JVS(LU_DIAG(i));
      END DO
      
END SUBROUTINE KppSolveCmplx

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveCmplxR( JVSR, JVSI, XR, XI )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!   Complex sparse solve subroutine using indirect addressing
!   (Real and Imaginary parts are used instead of complex data type)     
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm7_strato_SOA_Parameters
  USE cbm7_strato_SOA_JacobianSP

      INTEGER       ::  i, j
      REAL(kind=sp) ::  JVSR(LU_NONZERO), JVSI(LU_NONZERO), XR(NVAR), XI(NVAR), sumr, sumi, den

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1 
             XR(i) = XR(i) - (JVSR(j)*XR(LU_ICOL(j)) - JVSI(j)*XI(LU_ICOL(j)))
             XI(i) = XI(i) - (JVSR(j)*XI(LU_ICOL(j)) + JVSI(j)*XR(LU_ICOL(j)))
         END DO  
      END DO

      DO i=NVAR,1,-1
        sumr = XR(i); sumi = XI(i)
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
            sumr = sumr - (JVSR(j)*XR(LU_ICOL(j)) - JVSI(j)*XI(LU_ICOL(j)))
            sumi = sumi - (JVSR(j)*XI(LU_ICOL(j)) + JVSI(j)*XR(LU_ICOL(j)))
        END DO
        den   = JVSR(LU_DIAG(i))**2 + JVSI(LU_DIAG(i))**2
        XR(i) = (sumr*JVSR(LU_DIAG(i)) + sumi*JVSI(LU_DIAG(i)))/den
        XI(i) = (sumi*JVSR(LU_DIAG(i)) - sumr*JVSI(LU_DIAG(i)))/den
      END DO
      
END SUBROUTINE KppSolveCmplxR


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveTRCmplx( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve transpose subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm7_strato_SOA_Parameters
  USE cbm7_strato_SOA_JacobianSP

      INTEGER        :: i, j
      DOUBLE COMPLEX :: JVS(LU_NONZERO), X(NVAR)

      DO i=1,NVAR
        X(i) = X(i)/JVS(LU_DIAG(i))
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
	  X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
	END DO
      END DO

      DO i=NVAR, 1, -1
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
	  X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
	END DO
      END DO
      
END SUBROUTINE KppSolveTRCmplx


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveTRCmplxR( JVSR, JVSI, XR, XI )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!   Complex sparse solve transpose subroutine using indirect addressing
!   (Real and Imaginary parts are used instead of complex data type)     
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE cbm7_strato_SOA_Parameters
  USE cbm7_strato_SOA_JacobianSP

      INTEGER       ::  i, j
      REAL(kind=sp) ::  JVSR(LU_NONZERO), JVSI(LU_NONZERO), XR(NVAR), XI(NVAR), den

      DO i=1,NVAR
        den   = JVSR(LU_DIAG(i))**2 + JVSI(LU_DIAG(i))**2
        XR(i) = (XR(i)*JVSR(LU_DIAG(i)) + XI(i)*JVSI(LU_DIAG(i)))/den
        XI(i) = (XI(i)*JVSR(LU_DIAG(i)) - XR(i)*JVSI(LU_DIAG(i)))/den
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
	  XR(LU_ICOL(j)) = XR(LU_ICOL(j))-(JVSR(j)*XR(i) - JVSI(j)*XI(i))
	  XI(LU_ICOL(j)) = XI(LU_ICOL(j))-(JVSI(j)*XR(i) + JVSR(j)*XI(i))
	END DO
      END DO

      DO i=NVAR, 1, -1
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
	  XR(LU_ICOL(j)) = XR(LU_ICOL(j))-(JVSR(j)*XR(i) - JVSI(j)*XI(i))
	  XI(LU_ICOL(j)) = XI(LU_ICOL(j))-(JVSI(j)*XR(i) + JVSR(j)*XI(i))
	END DO
      END DO
      
END SUBROUTINE KppSolveTRCmplxR


!
! Next few commented subroutines perform sparse big linear algebra
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppDecompBig( JVS, IP, IER )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Sparse LU factorization
!!        for the Runge Kutta (3n)x(3n) linear system
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE cbm7_strato_SOA_Parameters
!  USE cbm7_strato_SOA_JacobianSP
!
!      INTEGER  :: IP3(3), IER, IP(3,NVAR)
!      REAL(kind=sp) :: JVS(3,3,LU_NONZERO), W(3,3,NVAR), a(3,3), E(3,3)
!      INTEGER  :: k, kk, j, jj
!
!      a = 0.0d0
!      IER = 0
!      DO k=1,NVAR
!        DO kk = LU_CROW(k), LU_CROW(k+1)-1
!              W( 1:3,1:3,LU_ICOL(kk) ) = JVS(1:3,1:3,kk)
!        END DO
!        DO kk = LU_CROW(k), LU_DIAG(k)-1
!            j = LU_ICOL(kk)
!            E(1:3,1:3) = JVS( 1:3,1:3,LU_DIAG(j) )
!            ! CALL DGETRF(3,3,E,3,IP3,IER) 
!            CALL FAC3(E,IP3,IER)
!            IF ( IER /= 0 )  RETURN
!            ! a = W(j) / JVS( LU_DIAG(j) )
!            a(1:3,1:3) = W( 1:3,1:3,j )
!            ! CALL DGETRS ('N',3,3,E,3,IP3,a,3,IER) 
!            CALL SOL3('N',E,IP3,a(1,1))
!            CALL SOL3('N',E,IP3,a(1,2))
!            CALL SOL3('N',E,IP3,a(1,3))
!            W(1:3,1:3,j) = a(1:3,1:3)
!            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
!               W( 1:3,1:3,LU_ICOL(jj) ) = W( 1:3,1:3,LU_ICOL(jj) ) &
!                        - MATMUL( a(1:3,1:3) , JVS(1:3,1:3,jj) )
!            END DO
!         END DO
!         DO kk = LU_CROW(k), LU_CROW(k+1)-1
!            JVS(1:3,1:3,kk) = W( 1:3,1:3,LU_ICOL(kk) )
!         END DO
!      END DO
!
!      DO k=1,NVAR
!         ! CALL WGEFA(JVS(1,1,LU_DIAG(k)),3,3,IP(1,k),IER)
!         ! CALL DGETRF(3,3,JVS(1,1,LU_DIAG(k)),3,IP(1,k),IER)
!         CALL FAC3(JVS(1,1,LU_DIAG(k)),IP(1,k),IER)
!         IF ( IER /= 0 )  RETURN
!      END DO 
!      
!END SUBROUTINE KppDecompBig
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppSolveBig( JVS, IP, X )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Sparse solve subroutine using indirect addressing
!!        for the Runge Kutta (3n)x(3n) linear system
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE cbm7_strato_SOA_Parameters
!  USE cbm7_strato_SOA_JacobianSP
!
!      INTEGER  :: i, j, k, m, IP3(3), IP(3,NVAR), IER
!      REAL(kind=sp) :: JVS(3,3,LU_NONZERO), X(3,NVAR), sum(3)
!
!      DO i=1,NVAR
!        DO j = LU_CROW(i), LU_DIAG(i)-1 
!          !X(1:3,i) = X(1:3,i) - MATMUL(JVS(1:3,1:3,j),X(1:3,LU_ICOL(j)));
!          DO k=1,3
!            DO m=1,3
!	       X(k,i) = X(k,i) - JVS(k,m,j)*X(m,LU_ICOL(j))
!            END DO
!          END DO
!        END DO  
!      END DO
!
!      DO i=NVAR,1,-1
!        sum(1:3) = X(1:3,i);
!        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
!          !sum(1:3) = sum(1:3) - MATMUL(JVS(1:3,1:3,j),X(1:3,LU_ICOL(j)));
!          DO k=1,3
!            DO m=1,3
!	       sum(k) = sum(k) - JVS(k,m,j)*X(m,LU_ICOL(j))
!            END DO
!          END DO
!        END DO
!        ! X(i) = sum/JVS(LU_DIAG(i));
!        ! CALL DGETRS ('N',3,1,JVS(1:3,1:3,LU_DIAG(i)),3,IP(1,i),sum,3,0) 
!        ! CALL WGESL('N',JVS(1,1,LU_DIAG(i)),3,3,IP(1,i),sum)
!        CALL SOL3('N',JVS(1,1,LU_DIAG(i)),IP(1,i),sum)
!        X(1:3,i) = sum(1:3)
!      END DO
!      
!END SUBROUTINE KppSolveBig
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppSolveBigTR( JVS, IP, X )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Big sparse transpose solve using indirect addressing
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE cbm7_strato_SOA_Parameters
!  USE cbm7_strato_SOA_JacobianSP
!
!      INTEGER       :: i, j, k, m, IP(3,NVAR)
!      REAL(kind=sp) :: JVS(3,3,LU_NONZERO), X(3,NVAR)
!
!      DO i=1,NVAR
!        ! X(i) = X(i)/JVS(LU_DIAG(i))
!        CALL SOL3('T',JVS(1,1,LU_DIAG(i)),IP(1,i),X(1,i))
!        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
!	  !X(1:3,LU_ICOL(j)) = X(1:3,LU_ICOL(j)) &
!          !    - MATMUL( TRANSPOSE(JVS(1:3,1:3,j)), X(1:3,i) )
!          DO k=1,3
!            DO m=1,3
!	       X(k,LU_ICOL(j)) = X(k,LU_ICOL(j)) - JVS(m,k,j)*X(m,i)
!            END DO
!          END DO
!	END DO
!      END DO
!
!      DO i=NVAR, 1, -1
!        DO j=LU_CROW(i),LU_DIAG(i)-1
!	  !X(1:3,LU_ICOL(j)) = X(1:3,LU_ICOL(j)) &
!          !   - MATMUL( TRANSPOSE(JVS(1:3,1:3,j)), X(1:3,i) )
!          DO k=1,3
!            DO m=1,3
!	       X(k,LU_ICOL(j)) = X(k,LU_ICOL(j)) - JVS(m,k,j)*X(m,i)
!            END DO
!          END DO
!	END DO
!      END DO
!      
!END SUBROUTINE KppSolveBigTR
!
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE FAC3(A,IPVT,INFO)
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!     FAC3 FACTORS THE MATRIX A (3,3) BY
!!           GAUSS ELIMINATION WITH PARTIAL PIVOTING
!!     LINPACK - LIKE 
!!
!!     Remove comments to perform pivoting
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!
!      REAL(kind=sp) :: A(3,3)
!      INTEGER       :: IPVT(3),INFO
!!      INTEGER       :: L
!!      REAL(kind=sp) :: t, dmax, da, TMP(3)
!      REAL(kind=sp), PARAMETER :: ZERO = 0.0, ONE = 1.0
!
!      info = 0
!!      t = TINY(da)
!!      
!!      da = ABS(A(1,1)); L = 1
!!      IF ( ABS(A(2,1))>da ) THEN
!!        da = ABS(A(2,1)); L = 2
!!        IF ( ABS(A(3,1))>da ) THEN
!!          L = 3
!!        END IF  
!!      END IF  
!!      IPVT(1)  = L
!!      IF (L /=1 ) THEN
!!         TMP(1:3) = A(L,1:3)
!!         A(L,1:3) = A(1,1:3)
!!         A(1,1:3) = TMP(1:3)
!!      END IF
!!      IF (ABS(A(1,1)) < t) THEN
!!         info = 1
!!         return
!!      END IF   
!!
!      A(2,1) = A(2,1)/A(1,1)
!      A(2,2) = A(2,2) - A(2,1)*A(1,2)
!      A(2,3) = A(2,3) - A(2,1)*A(1,3)
!      A(3,1) = A(3,1)/A(1,1)
!      A(3,2) = A(3,2) - A(3,1)*A(1,2)
!      A(3,3) = A(3,3) - A(3,1)*A(1,3)
!      
!!      IPVT(2)  = 2
!!      IF (ABS(A(3,2))>ABS(A(2,2))) THEN
!!         IPVT(2)  = 3
!!         TMP(2:3) = A(3,2:3)
!!         A(3,2:3) = A(2,2:3)
!!         A(2,2:3) = TMP(2:3)
!!      END IF
!!      IF (ABS(A(2,2)) < t) THEN
!!         info = 1
!!         return
!!      END IF   
!!      
!      A(3,2)   = A(3,2)/A(2,2)
!      A(3,3)   = A(3,3) - A(3,2)*A(2,3)
!      IPVT(3)  = 3
!      
!END SUBROUTINE FAC3
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE SOL3(Trans,A,IPVT,b)
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!     SOL3 solves the system 3x3
!!     A * x = b  or  trans(a) * x = b
!!     using the factors computed by WGEFA.
!!
!!     Trans      = 'N'   to solve  A*x = b ,
!!                = 'T'   to solve  transpose(A)*x = b
!!     LINPACK - LIKE 
!!
!!     Remove comments to use pivoting
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!      CHARACTER     :: Trans
!      REAL(kind=sp) :: a(3,3),b(3)
!      INTEGER       :: IPVT(3)
!!      INTEGER       :: L
!!      REAL(kind=sp) :: TMP
!      
!      SELECT CASE (Trans)
!
!      CASE ('n','N')  !  Solve  A * x = b
!
!!     Solve  L*y = b
!!         L = IPVT(1)
!!         IF (L /= 1) THEN
!!            TMP = B(1); B(1) = B(L); B(L) = TMP
!!         END IF
!         b(2) = b(2)-A(2,1)*b(1)
!         b(3) = b(3)-A(3,1)*b(1)
!         
!!         L = IPVT(2)
!!         IF (L /= 2) THEN
!!            TMP = B(2); B(2) = B(L); B(L) = TMP
!!         END IF
!         b(3) = b(3)-A(3,2)*b(2)
!
!!     Solve  U*x = y
!         b(3) = b(3)/A(3,3)
!         b(2) = (b(2)-A(2,3)*b(3))/A(2,2)
!         b(1) = (b(1)-A(1,3)*b(3)-A(1,2)*b(2))/A(1,1)
!      
!      
!      CASE ('t','T')  !  Solve transpose(A) * x = b
!
!!      Solve transpose(U)*y = b
!         b(1) = b(1)/A(1,1)
!         b(2) = (b(2)-A(1,2)*b(1))/A(2,2)
!         b(3) = (b(3)-A(1,3)*b(1)-A(2,3)*b(2))/A(3,3)
!
!!      Solve transpose(L)*x = y
!         b(2) = b(2)-A(3,2)*b(3)
!!         L = ipvt(2)
!!         IF (L /= 2) THEN
!!            TMP = B(2); B(2) = B(L); B(L) = TMP
!!         END IF
!         b(1) = b(1)-A(3,1)*b(3)-A(2,1)*b(2)
!!         L = ipvt(1)
!!         IF (L /= 1) THEN
!!            TMP = B(1); B(1) = B(L); B(L) = TMP
!!         END IF
!   
!      END SELECT
!
!END SUBROUTINE SOL3

! End of SPARSE_UTIL function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! KppSolve - sparse back substitution
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      X         - Vector for variables
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE KppSolve ( JVS, X )

! JVS - sparse Jacobian of variables
  REAL(kind=sp) :: JVS(LU_NONZERO)
! X - Vector for variables
  REAL(kind=sp) :: X(NVAR)

  X(9) = X(9)-JVS(16)*X(8)
  X(10) = X(10)-JVS(19)*X(9)
  X(19) = X(19)-JVS(55)*X(10)
  X(21) = X(21)-JVS(63)*X(6)
  X(32) = X(32)-JVS(117)*X(26)
  X(38) = X(38)-JVS(142)*X(13)
  X(53) = X(53)-JVS(207)*X(50)
  X(57) = X(57)-JVS(241)*X(48)
  X(58) = X(58)-JVS(249)*X(46)
  X(61) = X(61)-JVS(269)*X(43)-JVS(270)*X(52)
  X(62) = X(62)-JVS(279)*X(22)
  X(66) = X(66)-JVS(308)*X(41)-JVS(309)*X(62)-JVS(310)*X(65)
  X(67) = X(67)-JVS(320)*X(40)
  X(69) = X(69)-JVS(329)*X(64)-JVS(330)*X(68)
  X(70) = X(70)-JVS(341)*X(57)
  X(72) = X(72)-JVS(353)*X(13)-JVS(354)*X(35)-JVS(355)*X(50)-JVS(356)*X(58)-JVS(357)*X(68)-JVS(358)*X(71)
  X(74) = X(74)-JVS(395)*X(64)
  X(75) = X(75)-JVS(403)*X(47)-JVS(404)*X(54)-JVS(405)*X(56)
  X(77) = X(77)-JVS(418)*X(56)-JVS(419)*X(74)-JVS(420)*X(75)-JVS(421)*X(76)
  X(78) = X(78)-JVS(435)*X(20)-JVS(436)*X(59)
  X(79) = X(79)-JVS(444)*X(24)-JVS(445)*X(59)-JVS(446)*X(78)
  X(80) = X(80)-JVS(453)*X(25)-JVS(454)*X(59)-JVS(455)*X(78)-JVS(456)*X(79)
  X(81) = X(81)-JVS(462)*X(20)-JVS(463)*X(24)-JVS(464)*X(25)-JVS(465)*X(57)-JVS(466)*X(70)
  X(83) = X(83)-JVS(478)*X(23)-JVS(479)*X(48)-JVS(480)*X(53)-JVS(481)*X(54)-JVS(482)*X(64)-JVS(483)*X(68)-JVS(484)*X(70)&
            &-JVS(485)*X(74)-JVS(486)*X(75)-JVS(487)*X(76)-JVS(488)*X(78)-JVS(489)*X(79)-JVS(490)*X(80)-JVS(491)*X(81)&
            &-JVS(492)*X(82)
  X(84) = X(84)-JVS(515)*X(68)
  X(85) = X(85)-JVS(523)*X(21)-JVS(524)*X(67)-JVS(525)*X(76)-JVS(526)*X(84)
  X(87) = X(87)-JVS(542)*X(21)-JVS(543)*X(40)-JVS(544)*X(55)-JVS(545)*X(67)-JVS(546)*X(86)
  X(89) = X(89)-JVS(558)*X(35)-JVS(559)*X(47)-JVS(560)*X(54)-JVS(561)*X(56)-JVS(562)*X(64)-JVS(563)*X(68)-JVS(564)*X(74)&
            &-JVS(565)*X(75)-JVS(566)*X(76)-JVS(567)*X(82)-JVS(568)*X(84)-JVS(569)*X(88)
  X(90) = X(90)-JVS(580)*X(24)-JVS(581)*X(79)-JVS(582)*X(80)
  X(91) = X(91)-JVS(590)*X(13)-JVS(591)*X(50)-JVS(592)*X(75)-JVS(593)*X(78)-JVS(594)*X(79)-JVS(595)*X(80)-JVS(596)*X(81)&
            &-JVS(597)*X(82)-JVS(598)*X(86)-JVS(599)*X(90)
  X(92) = X(92)-JVS(614)*X(86)
  X(93) = X(93)-JVS(620)*X(31)-JVS(621)*X(56)-JVS(622)*X(75)-JVS(623)*X(79)-JVS(624)*X(80)-JVS(625)*X(81)-JVS(626)*X(82)&
            &-JVS(627)*X(86)-JVS(628)*X(88)-JVS(629)*X(89)-JVS(630)*X(90)-JVS(631)*X(92)
  X(94) = X(94)-JVS(644)*X(21)-JVS(645)*X(40)-JVS(646)*X(51)-JVS(647)*X(55)-JVS(648)*X(64)-JVS(649)*X(67)-JVS(650)*X(68)&
            &-JVS(651)*X(74)-JVS(652)*X(76)-JVS(653)*X(77)-JVS(654)*X(81)-JVS(655)*X(82)-JVS(656)*X(84)-JVS(657)*X(86)&
            &-JVS(658)*X(87)-JVS(659)*X(88)-JVS(660)*X(90)-JVS(661)*X(92)
  X(95) = X(95)-JVS(675)*X(20)-JVS(676)*X(25)-JVS(677)*X(70)-JVS(678)*X(78)-JVS(679)*X(79)-JVS(680)*X(80)-JVS(681)*X(81)&
            &-JVS(682)*X(90)
  X(96) = X(96)-JVS(691)*X(15)-JVS(692)*X(46)-JVS(693)*X(51)-JVS(694)*X(55)-JVS(695)*X(67)-JVS(696)*X(68)-JVS(697)*X(71)&
            &-JVS(698)*X(81)-JVS(699)*X(85)-JVS(700)*X(86)-JVS(701)*X(87)-JVS(702)*X(88)-JVS(703)*X(90)-JVS(704)*X(91)&
            &-JVS(705)*X(92)-JVS(706)*X(93)-JVS(707)*X(95)
  X(98) = X(98)-JVS(727)*X(21)-JVS(728)*X(24)-JVS(729)*X(25)-JVS(730)*X(40)-JVS(731)*X(49)-JVS(732)*X(51)-JVS(733)*X(67)&
            &-JVS(734)*X(71)-JVS(735)*X(77)-JVS(736)*X(81)-JVS(737)*X(82)-JVS(738)*X(84)-JVS(739)*X(86)-JVS(740)*X(87)&
            &-JVS(741)*X(88)-JVS(742)*X(90)-JVS(743)*X(92)-JVS(744)*X(94)-JVS(745)*X(95)-JVS(746)*X(96)-JVS(747)*X(97)
  X(99) = X(99)-JVS(762)*X(49)-JVS(763)*X(71)-JVS(764)*X(75)-JVS(765)*X(82)-JVS(766)*X(89)-JVS(767)*X(97)
  X(100) = X(100)-JVS(777)*X(46)-JVS(778)*X(49)-JVS(779)*X(51)-JVS(780)*X(60)-JVS(781)*X(69)-JVS(782)*X(86)-JVS(783)&
             &*X(87)-JVS(784)*X(88)-JVS(785)*X(92)-JVS(786)*X(97)-JVS(787)*X(99)
  X(102) = X(102)-JVS(813)*X(50)-JVS(814)*X(68)-JVS(815)*X(81)-JVS(816)*X(88)-JVS(817)*X(89)-JVS(818)*X(95)-JVS(819)&
             &*X(97)
  X(103) = X(103)-JVS(830)*X(38)-JVS(831)*X(71)-JVS(832)*X(73)-JVS(833)*X(88)-JVS(834)*X(92)-JVS(835)*X(97)-JVS(836)&
             &*X(100)
  X(104) = X(104)-JVS(855)*X(39)-JVS(856)*X(55)-JVS(857)*X(67)-JVS(858)*X(87)-JVS(859)*X(92)-JVS(860)*X(102)
  X(105) = X(105)-JVS(873)*X(34)-JVS(874)*X(36)-JVS(875)*X(55)-JVS(876)*X(67)-JVS(877)*X(85)-JVS(878)*X(87)-JVS(879)&
             &*X(88)-JVS(880)*X(89)-JVS(881)*X(90)-JVS(882)*X(92)-JVS(883)*X(93)-JVS(884)*X(95)-JVS(885)*X(97)-JVS(886)&
             &*X(99)-JVS(887)*X(102)-JVS(888)*X(104)
  X(106) = X(106)-JVS(904)*X(21)-JVS(905)*X(40)-JVS(906)*X(55)-JVS(907)*X(67)-JVS(908)*X(86)-JVS(909)*X(87)-JVS(910)&
             &*X(92)-JVS(911)*X(102)
  X(107) = X(107)-JVS(923)*X(39)-JVS(924)*X(49)-JVS(925)*X(51)-JVS(926)*X(55)-JVS(927)*X(67)-JVS(928)*X(86)-JVS(929)&
             &*X(87)-JVS(930)*X(90)-JVS(931)*X(92)-JVS(932)*X(95)-JVS(933)*X(104)-JVS(934)*X(106)
  X(108) = X(108)-JVS(946)*X(15)-JVS(947)*X(35)-JVS(948)*X(37)-JVS(949)*X(48)-JVS(950)*X(49)-JVS(951)*X(55)-JVS(952)&
             &*X(56)-JVS(953)*X(60)-JVS(954)*X(64)-JVS(955)*X(67)-JVS(956)*X(68)-JVS(957)*X(70)-JVS(958)*X(71)-JVS(959)&
             &*X(75)-JVS(960)*X(76)-JVS(961)*X(81)-JVS(962)*X(82)-JVS(963)*X(84)-JVS(964)*X(85)-JVS(965)*X(86)-JVS(966)&
             &*X(87)-JVS(967)*X(88)-JVS(968)*X(89)-JVS(969)*X(92)-JVS(970)*X(95)-JVS(971)*X(97)-JVS(972)*X(99)-JVS(973)&
             &*X(105)-JVS(974)*X(106)-JVS(975)*X(107)
  X(109) = X(109)-JVS(989)*X(32)-JVS(990)*X(62)-JVS(991)*X(65)-JVS(992)*X(66)-JVS(993)*X(73)-JVS(994)*X(100)-JVS(995)&
             &*X(101)-JVS(996)*X(106)-JVS(997)*X(107)-JVS(998)*X(108)
  X(110) = X(110)-JVS(1013)*X(22)-JVS(1014)*X(62)-JVS(1015)*X(65)-JVS(1016)*X(66)-JVS(1017)*X(100)-JVS(1018)*X(101)&
             &-JVS(1019)*X(106)-JVS(1020)*X(107)-JVS(1021)*X(108)-JVS(1022)*X(109)
  X(111) = X(111)-JVS(1036)*X(12)-JVS(1037)*X(23)-JVS(1038)*X(26)-JVS(1039)*X(33)-JVS(1040)*X(36)-JVS(1041)*X(39)&
             &-JVS(1042)*X(41)-JVS(1043)*X(44)-JVS(1044)*X(45)-JVS(1045)*X(50)-JVS(1046)*X(52)-JVS(1047)*X(54)-JVS(1048)&
             &*X(57)-JVS(1049)*X(64)-JVS(1050)*X(65)-JVS(1051)*X(68)-JVS(1052)*X(70)-JVS(1053)*X(71)-JVS(1054)*X(74)&
             &-JVS(1055)*X(75)-JVS(1056)*X(76)-JVS(1057)*X(78)-JVS(1058)*X(79)-JVS(1059)*X(80)-JVS(1060)*X(81)-JVS(1061)&
             &*X(82)-JVS(1062)*X(83)-JVS(1063)*X(84)-JVS(1064)*X(86)-JVS(1065)*X(88)-JVS(1066)*X(89)-JVS(1067)*X(90)&
             &-JVS(1068)*X(91)-JVS(1069)*X(92)-JVS(1070)*X(93)-JVS(1071)*X(94)-JVS(1072)*X(95)-JVS(1073)*X(96)-JVS(1074)&
             &*X(97)-JVS(1075)*X(98)-JVS(1076)*X(99)-JVS(1077)*X(101)-JVS(1078)*X(102)-JVS(1079)*X(103)-JVS(1080)*X(104)&
             &-JVS(1081)*X(105)-JVS(1082)*X(106)-JVS(1083)*X(107)-JVS(1084)*X(108)-JVS(1085)*X(109)-JVS(1086)*X(110)
  X(112) = X(112)-JVS(1099)*X(64)-JVS(1100)*X(68)-JVS(1101)*X(71)-JVS(1102)*X(86)-JVS(1103)*X(88)-JVS(1104)*X(90)&
             &-JVS(1105)*X(92)-JVS(1106)*X(95)-JVS(1107)*X(97)-JVS(1108)*X(101)-JVS(1109)*X(102)-JVS(1110)*X(103)-JVS(1111)&
             &*X(104)-JVS(1112)*X(105)-JVS(1113)*X(106)-JVS(1114)*X(107)-JVS(1115)*X(108)-JVS(1116)*X(109)-JVS(1117)*X(110)&
             &-JVS(1118)*X(111)
  X(113) = X(113)-JVS(1130)*X(11)-JVS(1131)*X(15)-JVS(1132)*X(36)-JVS(1133)*X(37)-JVS(1134)*X(46)-JVS(1135)*X(63)&
             &-JVS(1136)*X(67)-JVS(1137)*X(85)-JVS(1138)*X(86)-JVS(1139)*X(87)-JVS(1140)*X(88)-JVS(1141)*X(92)-JVS(1142)&
             &*X(97)-JVS(1143)*X(102)-JVS(1144)*X(104)-JVS(1145)*X(105)-JVS(1146)*X(106)-JVS(1147)*X(107)-JVS(1148)*X(109)&
             &-JVS(1149)*X(110)-JVS(1150)*X(111)-JVS(1151)*X(112)
  X(114) = X(114)-JVS(1162)*X(6)-JVS(1163)*X(7)-JVS(1164)*X(8)-JVS(1165)*X(9)-JVS(1166)*X(10)-JVS(1167)*X(11)-JVS(1168)&
             &*X(13)-JVS(1169)*X(15)-JVS(1170)*X(16)-JVS(1171)*X(17)-JVS(1172)*X(18)-JVS(1173)*X(19)-JVS(1174)*X(20)&
             &-JVS(1175)*X(24)-JVS(1176)*X(25)-JVS(1177)*X(27)-JVS(1178)*X(28)-JVS(1179)*X(29)-JVS(1180)*X(30)-JVS(1181)&
             &*X(31)-JVS(1182)*X(33)-JVS(1183)*X(34)-JVS(1184)*X(35)-JVS(1185)*X(37)-JVS(1186)*X(38)-JVS(1187)*X(39)&
             &-JVS(1188)*X(41)-JVS(1189)*X(43)-JVS(1190)*X(44)-JVS(1191)*X(45)-JVS(1192)*X(46)-JVS(1193)*X(47)-JVS(1194)&
             &*X(48)-JVS(1195)*X(49)-JVS(1196)*X(50)-JVS(1197)*X(51)-JVS(1198)*X(52)-JVS(1199)*X(54)-JVS(1200)*X(55)&
             &-JVS(1201)*X(56)-JVS(1202)*X(58)-JVS(1203)*X(59)-JVS(1204)*X(60)-JVS(1205)*X(61)-JVS(1206)*X(62)-JVS(1207)&
             &*X(63)-JVS(1208)*X(64)-JVS(1209)*X(65)-JVS(1210)*X(66)-JVS(1211)*X(67)-JVS(1212)*X(68)-JVS(1213)*X(69)&
             &-JVS(1214)*X(70)-JVS(1215)*X(71)-JVS(1216)*X(72)-JVS(1217)*X(73)-JVS(1218)*X(74)-JVS(1219)*X(75)-JVS(1220)&
             &*X(76)-JVS(1221)*X(77)-JVS(1222)*X(78)-JVS(1223)*X(79)-JVS(1224)*X(80)-JVS(1225)*X(81)-JVS(1226)*X(82)&
             &-JVS(1227)*X(83)-JVS(1228)*X(84)-JVS(1229)*X(85)-JVS(1230)*X(86)-JVS(1231)*X(87)-JVS(1232)*X(88)-JVS(1233)&
             &*X(89)-JVS(1234)*X(90)-JVS(1235)*X(91)-JVS(1236)*X(92)-JVS(1237)*X(93)-JVS(1238)*X(94)-JVS(1239)*X(95)&
             &-JVS(1240)*X(96)-JVS(1241)*X(97)-JVS(1242)*X(98)-JVS(1243)*X(99)-JVS(1244)*X(100)-JVS(1245)*X(101)-JVS(1246)&
             &*X(102)-JVS(1247)*X(103)-JVS(1248)*X(104)-JVS(1249)*X(105)-JVS(1250)*X(106)-JVS(1251)*X(107)-JVS(1252)*X(108)&
             &-JVS(1253)*X(109)-JVS(1254)*X(110)-JVS(1255)*X(111)-JVS(1256)*X(112)-JVS(1257)*X(113)
  X(115) = X(115)-JVS(1267)*X(26)-JVS(1268)*X(32)-JVS(1269)*X(42)-JVS(1270)*X(61)-JVS(1271)*X(65)-JVS(1272)*X(66)&
             &-JVS(1273)*X(69)-JVS(1274)*X(73)-JVS(1275)*X(86)-JVS(1276)*X(88)-JVS(1277)*X(92)-JVS(1278)*X(100)-JVS(1279)&
             &*X(101)-JVS(1280)*X(103)-JVS(1281)*X(106)-JVS(1282)*X(107)-JVS(1283)*X(108)-JVS(1284)*X(109)-JVS(1285)*X(110)&
             &-JVS(1286)*X(111)-JVS(1287)*X(112)-JVS(1288)*X(113)-JVS(1289)*X(114)
  X(116) = X(116)-JVS(1298)*X(12)-JVS(1299)*X(15)-JVS(1300)*X(42)-JVS(1301)*X(43)-JVS(1302)*X(52)-JVS(1303)*X(61)&
             &-JVS(1304)*X(73)-JVS(1305)*X(101)-JVS(1306)*X(105)-JVS(1307)*X(106)-JVS(1308)*X(107)-JVS(1309)*X(108)&
             &-JVS(1310)*X(109)-JVS(1311)*X(110)-JVS(1312)*X(111)-JVS(1313)*X(112)-JVS(1314)*X(113)-JVS(1315)*X(114)&
             &-JVS(1316)*X(115)
  X(117) = X(117)-JVS(1324)*X(23)-JVS(1325)*X(36)-JVS(1326)*X(44)-JVS(1327)*X(48)-JVS(1328)*X(52)-JVS(1329)*X(64)&
             &-JVS(1330)*X(65)-JVS(1331)*X(68)-JVS(1332)*X(70)-JVS(1333)*X(71)-JVS(1334)*X(81)-JVS(1335)*X(83)-JVS(1336)&
             &*X(84)-JVS(1337)*X(86)-JVS(1338)*X(88)-JVS(1339)*X(89)-JVS(1340)*X(90)-JVS(1341)*X(91)-JVS(1342)*X(92)&
             &-JVS(1343)*X(93)-JVS(1344)*X(94)-JVS(1345)*X(95)-JVS(1346)*X(96)-JVS(1347)*X(97)-JVS(1348)*X(98)-JVS(1349)&
             &*X(99)-JVS(1350)*X(102)-JVS(1351)*X(104)-JVS(1352)*X(105)-JVS(1353)*X(106)-JVS(1354)*X(107)-JVS(1355)*X(108)&
             &-JVS(1356)*X(110)-JVS(1357)*X(111)-JVS(1358)*X(112)-JVS(1359)*X(113)-JVS(1360)*X(114)-JVS(1361)*X(115)&
             &-JVS(1362)*X(116)
  X(118) = X(118)-JVS(1369)*X(26)-JVS(1370)*X(32)-JVS(1371)*X(33)-JVS(1372)*X(70)-JVS(1373)*X(74)-JVS(1374)*X(75)&
             &-JVS(1375)*X(76)-JVS(1376)*X(78)-JVS(1377)*X(79)-JVS(1378)*X(80)-JVS(1379)*X(81)-JVS(1380)*X(82)-JVS(1381)&
             &*X(84)-JVS(1382)*X(88)-JVS(1383)*X(94)-JVS(1384)*X(96)-JVS(1385)*X(97)-JVS(1386)*X(98)-JVS(1387)*X(99)&
             &-JVS(1388)*X(101)-JVS(1389)*X(102)-JVS(1390)*X(103)-JVS(1391)*X(104)-JVS(1392)*X(105)-JVS(1393)*X(106)&
             &-JVS(1394)*X(107)-JVS(1395)*X(108)-JVS(1396)*X(109)-JVS(1397)*X(110)-JVS(1398)*X(111)-JVS(1399)*X(112)&
             &-JVS(1400)*X(113)-JVS(1401)*X(114)-JVS(1402)*X(115)-JVS(1403)*X(116)-JVS(1404)*X(117)
  X(119) = X(119)-JVS(1410)*X(11)-JVS(1411)*X(20)-JVS(1412)*X(21)-JVS(1413)*X(24)-JVS(1414)*X(25)-JVS(1415)*X(36)&
             &-JVS(1416)*X(37)-JVS(1417)*X(40)-JVS(1418)*X(47)-JVS(1419)*X(49)-JVS(1420)*X(51)-JVS(1421)*X(54)-JVS(1422)&
             &*X(55)-JVS(1423)*X(56)-JVS(1424)*X(59)-JVS(1425)*X(63)-JVS(1426)*X(64)-JVS(1427)*X(67)-JVS(1428)*X(68)&
             &-JVS(1429)*X(71)-JVS(1430)*X(74)-JVS(1431)*X(76)-JVS(1432)*X(77)-JVS(1433)*X(78)-JVS(1434)*X(79)-JVS(1435)&
             &*X(80)-JVS(1436)*X(81)-JVS(1437)*X(82)-JVS(1438)*X(84)-JVS(1439)*X(85)-JVS(1440)*X(86)-JVS(1441)*X(87)&
             &-JVS(1442)*X(88)-JVS(1443)*X(90)-JVS(1444)*X(91)-JVS(1445)*X(92)-JVS(1446)*X(93)-JVS(1447)*X(94)-JVS(1448)&
             &*X(95)-JVS(1449)*X(96)-JVS(1450)*X(97)-JVS(1451)*X(98)-JVS(1452)*X(99)-JVS(1453)*X(102)-JVS(1454)*X(104)&
             &-JVS(1455)*X(105)-JVS(1456)*X(106)-JVS(1457)*X(107)-JVS(1458)*X(111)-JVS(1459)*X(112)-JVS(1460)*X(113)&
             &-JVS(1461)*X(114)-JVS(1462)*X(115)-JVS(1463)*X(116)-JVS(1464)*X(117)-JVS(1465)*X(118)
  X(120) = X(120)-JVS(1470)*X(42)-JVS(1471)*X(52)-JVS(1472)*X(61)-JVS(1473)*X(73)-JVS(1474)*X(101)-JVS(1475)*X(105)&
             &-JVS(1476)*X(106)-JVS(1477)*X(107)-JVS(1478)*X(108)-JVS(1479)*X(109)-JVS(1480)*X(110)-JVS(1481)*X(111)&
             &-JVS(1482)*X(112)-JVS(1483)*X(113)-JVS(1484)*X(114)-JVS(1485)*X(115)-JVS(1486)*X(116)-JVS(1487)*X(117)&
             &-JVS(1488)*X(118)-JVS(1489)*X(119)
  X(121) = X(121)-JVS(1493)*X(13)-JVS(1494)*X(20)-JVS(1495)*X(24)-JVS(1496)*X(25)-JVS(1497)*X(31)-JVS(1498)*X(35)&
             &-JVS(1499)*X(44)-JVS(1500)*X(46)-JVS(1501)*X(47)-JVS(1502)*X(48)-JVS(1503)*X(49)-JVS(1504)*X(51)-JVS(1505)&
             &*X(54)-JVS(1506)*X(55)-JVS(1507)*X(56)-JVS(1508)*X(57)-JVS(1509)*X(58)-JVS(1510)*X(60)-JVS(1511)*X(64)&
             &-JVS(1512)*X(67)-JVS(1513)*X(68)-JVS(1514)*X(69)-JVS(1515)*X(70)-JVS(1516)*X(71)-JVS(1517)*X(72)-JVS(1518)&
             &*X(74)-JVS(1519)*X(75)-JVS(1520)*X(76)-JVS(1521)*X(77)-JVS(1522)*X(78)-JVS(1523)*X(79)-JVS(1524)*X(80)&
             &-JVS(1525)*X(81)-JVS(1526)*X(82)-JVS(1527)*X(84)-JVS(1528)*X(85)-JVS(1529)*X(86)-JVS(1530)*X(87)-JVS(1531)&
             &*X(88)-JVS(1532)*X(89)-JVS(1533)*X(90)-JVS(1534)*X(91)-JVS(1535)*X(92)-JVS(1536)*X(93)-JVS(1537)*X(94)&
             &-JVS(1538)*X(95)-JVS(1539)*X(96)-JVS(1540)*X(97)-JVS(1541)*X(98)-JVS(1542)*X(99)-JVS(1543)*X(102)-JVS(1544)&
             &*X(103)-JVS(1545)*X(104)-JVS(1546)*X(105)-JVS(1547)*X(106)-JVS(1548)*X(107)-JVS(1549)*X(108)-JVS(1550)*X(109)&
             &-JVS(1551)*X(110)-JVS(1552)*X(111)-JVS(1553)*X(112)-JVS(1554)*X(113)-JVS(1555)*X(114)-JVS(1556)*X(115)&
             &-JVS(1557)*X(116)-JVS(1558)*X(117)-JVS(1559)*X(118)-JVS(1560)*X(119)-JVS(1561)*X(120)
  X(122) = X(122)-JVS(1564)*X(1)-JVS(1565)*X(2)-JVS(1566)*X(3)-JVS(1567)*X(7)-JVS(1568)*X(14)-JVS(1569)*X(22)-JVS(1570)&
             &*X(41)-JVS(1571)*X(42)-JVS(1572)*X(46)-JVS(1573)*X(49)-JVS(1574)*X(51)-JVS(1575)*X(58)-JVS(1576)*X(60)&
             &-JVS(1577)*X(62)-JVS(1578)*X(65)-JVS(1579)*X(66)-JVS(1580)*X(69)-JVS(1581)*X(71)-JVS(1582)*X(86)-JVS(1583)&
             &*X(87)-JVS(1584)*X(88)-JVS(1585)*X(92)-JVS(1586)*X(97)-JVS(1587)*X(99)-JVS(1588)*X(100)-JVS(1589)*X(101)&
             &-JVS(1590)*X(106)-JVS(1591)*X(107)-JVS(1592)*X(108)-JVS(1593)*X(109)-JVS(1594)*X(110)-JVS(1595)*X(111)&
             &-JVS(1596)*X(112)-JVS(1597)*X(113)-JVS(1598)*X(114)-JVS(1599)*X(115)-JVS(1600)*X(116)-JVS(1601)*X(117)&
             &-JVS(1602)*X(118)-JVS(1603)*X(119)-JVS(1604)*X(120)-JVS(1605)*X(121)
  X(122) = X(122)/JVS(1606)
  X(121) = (X(121)-JVS(1563)*X(122))/(JVS(1562))
  X(120) = (X(120)-JVS(1491)*X(121)-JVS(1492)*X(122))/(JVS(1490))
  X(119) = (X(119)-JVS(1467)*X(120)-JVS(1468)*X(121)-JVS(1469)*X(122))/(JVS(1466))
  X(118) = (X(118)-JVS(1406)*X(119)-JVS(1407)*X(120)-JVS(1408)*X(121)-JVS(1409)*X(122))/(JVS(1405))
  X(117) = (X(117)-JVS(1364)*X(118)-JVS(1365)*X(119)-JVS(1366)*X(120)-JVS(1367)*X(121)-JVS(1368)*X(122))/(JVS(1363))
  X(116) = (X(116)-JVS(1318)*X(117)-JVS(1319)*X(118)-JVS(1320)*X(119)-JVS(1321)*X(120)-JVS(1322)*X(121)-JVS(1323)&
             &*X(122))/(JVS(1317))
  X(115) = (X(115)-JVS(1291)*X(116)-JVS(1292)*X(117)-JVS(1293)*X(118)-JVS(1294)*X(119)-JVS(1295)*X(120)-JVS(1296)*X(121)&
             &-JVS(1297)*X(122))/(JVS(1290))
  X(114) = (X(114)-JVS(1259)*X(115)-JVS(1260)*X(116)-JVS(1261)*X(117)-JVS(1262)*X(118)-JVS(1263)*X(119)-JVS(1264)*X(120)&
             &-JVS(1265)*X(121)-JVS(1266)*X(122))/(JVS(1258))
  X(113) = (X(113)-JVS(1153)*X(114)-JVS(1154)*X(115)-JVS(1155)*X(116)-JVS(1156)*X(117)-JVS(1157)*X(118)-JVS(1158)*X(119)&
             &-JVS(1159)*X(120)-JVS(1160)*X(121)-JVS(1161)*X(122))/(JVS(1152))
  X(112) = (X(112)-JVS(1120)*X(113)-JVS(1121)*X(114)-JVS(1122)*X(115)-JVS(1123)*X(116)-JVS(1124)*X(117)-JVS(1125)*X(118)&
             &-JVS(1126)*X(119)-JVS(1127)*X(120)-JVS(1128)*X(121)-JVS(1129)*X(122))/(JVS(1119))
  X(111) = (X(111)-JVS(1088)*X(112)-JVS(1089)*X(113)-JVS(1090)*X(114)-JVS(1091)*X(115)-JVS(1092)*X(116)-JVS(1093)*X(117)&
             &-JVS(1094)*X(118)-JVS(1095)*X(119)-JVS(1096)*X(120)-JVS(1097)*X(121)-JVS(1098)*X(122))/(JVS(1087))
  X(110) = (X(110)-JVS(1024)*X(111)-JVS(1025)*X(112)-JVS(1026)*X(113)-JVS(1027)*X(114)-JVS(1028)*X(115)-JVS(1029)*X(116)&
             &-JVS(1030)*X(117)-JVS(1031)*X(118)-JVS(1032)*X(119)-JVS(1033)*X(120)-JVS(1034)*X(121)-JVS(1035)*X(122))&
             &/(JVS(1023))
  X(109) = (X(109)-JVS(1000)*X(110)-JVS(1001)*X(111)-JVS(1002)*X(112)-JVS(1003)*X(113)-JVS(1004)*X(114)-JVS(1005)*X(115)&
             &-JVS(1006)*X(116)-JVS(1007)*X(117)-JVS(1008)*X(118)-JVS(1009)*X(119)-JVS(1010)*X(120)-JVS(1011)*X(121)&
             &-JVS(1012)*X(122))/(JVS(999))
  X(108) = (X(108)-JVS(977)*X(111)-JVS(978)*X(112)-JVS(979)*X(113)-JVS(980)*X(114)-JVS(981)*X(115)-JVS(982)*X(116)&
             &-JVS(983)*X(117)-JVS(984)*X(118)-JVS(985)*X(119)-JVS(986)*X(120)-JVS(987)*X(121)-JVS(988)*X(122))/(JVS(976))
  X(107) = (X(107)-JVS(936)*X(111)-JVS(937)*X(112)-JVS(938)*X(114)-JVS(939)*X(115)-JVS(940)*X(116)-JVS(941)*X(117)&
             &-JVS(942)*X(118)-JVS(943)*X(119)-JVS(944)*X(121)-JVS(945)*X(122))/(JVS(935))
  X(106) = (X(106)-JVS(913)*X(111)-JVS(914)*X(112)-JVS(915)*X(114)-JVS(916)*X(115)-JVS(917)*X(116)-JVS(918)*X(117)&
             &-JVS(919)*X(118)-JVS(920)*X(119)-JVS(921)*X(121)-JVS(922)*X(122))/(JVS(912))
  X(105) = (X(105)-JVS(890)*X(106)-JVS(891)*X(107)-JVS(892)*X(111)-JVS(893)*X(112)-JVS(894)*X(113)-JVS(895)*X(114)&
             &-JVS(896)*X(115)-JVS(897)*X(116)-JVS(898)*X(117)-JVS(899)*X(118)-JVS(900)*X(119)-JVS(901)*X(120)-JVS(902)&
             &*X(121)-JVS(903)*X(122))/(JVS(889))
  X(104) = (X(104)-JVS(862)*X(106)-JVS(863)*X(111)-JVS(864)*X(112)-JVS(865)*X(114)-JVS(866)*X(115)-JVS(867)*X(116)&
             &-JVS(868)*X(117)-JVS(869)*X(118)-JVS(870)*X(119)-JVS(871)*X(121)-JVS(872)*X(122))/(JVS(861))
  X(103) = (X(103)-JVS(838)*X(106)-JVS(839)*X(107)-JVS(840)*X(108)-JVS(841)*X(109)-JVS(842)*X(110)-JVS(843)*X(111)&
             &-JVS(844)*X(112)-JVS(845)*X(113)-JVS(846)*X(114)-JVS(847)*X(115)-JVS(848)*X(116)-JVS(849)*X(117)-JVS(850)&
             &*X(118)-JVS(851)*X(119)-JVS(852)*X(120)-JVS(853)*X(121)-JVS(854)*X(122))/(JVS(837))
  X(102) = (X(102)-JVS(821)*X(111)-JVS(822)*X(112)-JVS(823)*X(114)-JVS(824)*X(115)-JVS(825)*X(117)-JVS(826)*X(118)&
             &-JVS(827)*X(119)-JVS(828)*X(121)-JVS(829)*X(122))/(JVS(820))
  X(101) = (X(101)-JVS(804)*X(110)-JVS(805)*X(112)-JVS(806)*X(114)-JVS(807)*X(115)-JVS(808)*X(116)-JVS(809)*X(117)&
             &-JVS(810)*X(118)-JVS(811)*X(120)-JVS(812)*X(122))/(JVS(803))
  X(100) = (X(100)-JVS(789)*X(106)-JVS(790)*X(107)-JVS(791)*X(108)-JVS(792)*X(109)-JVS(793)*X(110)-JVS(794)*X(112)&
             &-JVS(795)*X(113)-JVS(796)*X(114)-JVS(797)*X(115)-JVS(798)*X(117)-JVS(799)*X(118)-JVS(800)*X(119)-JVS(801)&
             &*X(121)-JVS(802)*X(122))/(JVS(788))
  X(99) = (X(99)-JVS(769)*X(112)-JVS(770)*X(114)-JVS(771)*X(115)-JVS(772)*X(117)-JVS(773)*X(118)-JVS(774)*X(119)&
            &-JVS(775)*X(121)-JVS(776)*X(122))/(JVS(768))
  X(98) = (X(98)-JVS(749)*X(99)-JVS(750)*X(102)-JVS(751)*X(104)-JVS(752)*X(106)-JVS(753)*X(111)-JVS(754)*X(112)-JVS(755)&
            &*X(114)-JVS(756)*X(115)-JVS(757)*X(117)-JVS(758)*X(118)-JVS(759)*X(119)-JVS(760)*X(121)-JVS(761)*X(122))&
            &/(JVS(748))
  X(97) = (X(97)-JVS(722)*X(112)-JVS(723)*X(114)-JVS(724)*X(115)-JVS(725)*X(117)-JVS(726)*X(122))/(JVS(721))
  X(96) = (X(96)-JVS(709)*X(97)-JVS(710)*X(99)-JVS(711)*X(102)-JVS(712)*X(111)-JVS(713)*X(112)-JVS(714)*X(114)-JVS(715)&
            &*X(115)-JVS(716)*X(117)-JVS(717)*X(118)-JVS(718)*X(119)-JVS(719)*X(121)-JVS(720)*X(122))/(JVS(708))
  X(95) = (X(95)-JVS(684)*X(111)-JVS(685)*X(112)-JVS(686)*X(114)-JVS(687)*X(117)-JVS(688)*X(118)-JVS(689)*X(119)&
            &-JVS(690)*X(121))/(JVS(683))
  X(94) = (X(94)-JVS(663)*X(96)-JVS(664)*X(97)-JVS(665)*X(98)-JVS(666)*X(111)-JVS(667)*X(112)-JVS(668)*X(114)-JVS(669)&
            &*X(115)-JVS(670)*X(117)-JVS(671)*X(118)-JVS(672)*X(119)-JVS(673)*X(121)-JVS(674)*X(122))/(JVS(662))
  X(93) = (X(93)-JVS(633)*X(95)-JVS(634)*X(97)-JVS(635)*X(111)-JVS(636)*X(112)-JVS(637)*X(114)-JVS(638)*X(115)-JVS(639)&
            &*X(117)-JVS(640)*X(118)-JVS(641)*X(119)-JVS(642)*X(121)-JVS(643)*X(122))/(JVS(632))
  X(92) = (X(92)-JVS(616)*X(112)-JVS(617)*X(114)-JVS(618)*X(117)-JVS(619)*X(122))/(JVS(615))
  X(91) = (X(91)-JVS(601)*X(92)-JVS(602)*X(95)-JVS(603)*X(97)-JVS(604)*X(99)-JVS(605)*X(102)-JVS(606)*X(111)-JVS(607)&
            &*X(112)-JVS(608)*X(114)-JVS(609)*X(117)-JVS(610)*X(118)-JVS(611)*X(119)-JVS(612)*X(121)-JVS(613)*X(122))&
            &/(JVS(600))
  X(90) = (X(90)-JVS(584)*X(112)-JVS(585)*X(114)-JVS(586)*X(117)-JVS(587)*X(118)-JVS(588)*X(119)-JVS(589)*X(121))&
            &/(JVS(583))
  X(89) = (X(89)-JVS(571)*X(97)-JVS(572)*X(112)-JVS(573)*X(114)-JVS(574)*X(115)-JVS(575)*X(117)-JVS(576)*X(118)-JVS(577)&
            &*X(119)-JVS(578)*X(121)-JVS(579)*X(122))/(JVS(570))
  X(88) = (X(88)-JVS(554)*X(112)-JVS(555)*X(114)-JVS(556)*X(115)-JVS(557)*X(117))/(JVS(553))
  X(87) = (X(87)-JVS(548)*X(92)-JVS(549)*X(112)-JVS(550)*X(114)-JVS(551)*X(117)-JVS(552)*X(122))/(JVS(547))
  X(86) = (X(86)-JVS(538)*X(112)-JVS(539)*X(114)-JVS(540)*X(117)-JVS(541)*X(122))/(JVS(537))
  X(85) = (X(85)-JVS(528)*X(87)-JVS(529)*X(88)-JVS(530)*X(112)-JVS(531)*X(114)-JVS(532)*X(117)-JVS(533)*X(118)-JVS(534)&
            &*X(119)-JVS(535)*X(121)-JVS(536)*X(122))/(JVS(527))
  X(84) = (X(84)-JVS(517)*X(112)-JVS(518)*X(114)-JVS(519)*X(117)-JVS(520)*X(118)-JVS(521)*X(119)-JVS(522)*X(121))&
            &/(JVS(516))
  X(83) = (X(83)-JVS(494)*X(84)-JVS(495)*X(88)-JVS(496)*X(89)-JVS(497)*X(90)-JVS(498)*X(91)-JVS(499)*X(93)-JVS(500)&
            &*X(94)-JVS(501)*X(95)-JVS(502)*X(97)-JVS(503)*X(99)-JVS(504)*X(102)-JVS(505)*X(106)-JVS(506)*X(107)-JVS(507)&
            &*X(108)-JVS(508)*X(111)-JVS(509)*X(112)-JVS(510)*X(114)-JVS(511)*X(117)-JVS(512)*X(118)-JVS(513)*X(119)&
            &-JVS(514)*X(121))/(JVS(493))
  X(82) = (X(82)-JVS(473)*X(97)-JVS(474)*X(114)-JVS(475)*X(118)-JVS(476)*X(119)-JVS(477)*X(121))/(JVS(472))
  X(81) = (X(81)-JVS(468)*X(111)-JVS(469)*X(114)-JVS(470)*X(117)-JVS(471)*X(121))/(JVS(467))
  X(80) = (X(80)-JVS(458)*X(114)-JVS(459)*X(118)-JVS(460)*X(119)-JVS(461)*X(121))/(JVS(457))
  X(79) = (X(79)-JVS(448)*X(80)-JVS(449)*X(114)-JVS(450)*X(118)-JVS(451)*X(119)-JVS(452)*X(121))/(JVS(447))
  X(78) = (X(78)-JVS(438)*X(79)-JVS(439)*X(80)-JVS(440)*X(114)-JVS(441)*X(118)-JVS(442)*X(119)-JVS(443)*X(121))&
            &/(JVS(437))
  X(77) = (X(77)-JVS(423)*X(82)-JVS(424)*X(84)-JVS(425)*X(88)-JVS(426)*X(94)-JVS(427)*X(96)-JVS(428)*X(98)-JVS(429)&
            &*X(112)-JVS(430)*X(114)-JVS(431)*X(117)-JVS(432)*X(118)-JVS(433)*X(119)-JVS(434)*X(121))/(JVS(422))
  X(76) = (X(76)-JVS(413)*X(88)-JVS(414)*X(114)-JVS(415)*X(118)-JVS(416)*X(119)-JVS(417)*X(121))/(JVS(412))
  X(75) = (X(75)-JVS(407)*X(82)-JVS(408)*X(114)-JVS(409)*X(118)-JVS(410)*X(119)-JVS(411)*X(121))/(JVS(406))
  X(74) = (X(74)-JVS(397)*X(112)-JVS(398)*X(114)-JVS(399)*X(117)-JVS(400)*X(118)-JVS(401)*X(119)-JVS(402)*X(121))&
            &/(JVS(396))
  X(73) = (X(73)-JVS(386)*X(106)-JVS(387)*X(107)-JVS(388)*X(108)-JVS(389)*X(109)-JVS(390)*X(114)-JVS(391)*X(115)&
            &-JVS(392)*X(116)-JVS(393)*X(120)-JVS(394)*X(121))/(JVS(385))
  X(72) = (X(72)-JVS(360)*X(75)-JVS(361)*X(82)-JVS(362)*X(85)-JVS(363)*X(86)-JVS(364)*X(89)-JVS(365)*X(90)-JVS(366)&
            &*X(91)-JVS(367)*X(92)-JVS(368)*X(93)-JVS(369)*X(95)-JVS(370)*X(97)-JVS(371)*X(99)-JVS(372)*X(102)-JVS(373)&
            &*X(106)-JVS(374)*X(107)-JVS(375)*X(108)-JVS(376)*X(111)-JVS(377)*X(112)-JVS(378)*X(114)-JVS(379)*X(116)&
            &-JVS(380)*X(117)-JVS(381)*X(118)-JVS(382)*X(119)-JVS(383)*X(121)-JVS(384)*X(122))/(JVS(359))
  X(71) = (X(71)-JVS(349)*X(112)-JVS(350)*X(114)-JVS(351)*X(117)-JVS(352)*X(122))/(JVS(348))
  X(70) = (X(70)-JVS(343)*X(81)-JVS(344)*X(111)-JVS(345)*X(114)-JVS(346)*X(117)-JVS(347)*X(121))/(JVS(342))
  X(69) = (X(69)-JVS(332)*X(86)-JVS(333)*X(88)-JVS(334)*X(92)-JVS(335)*X(112)-JVS(336)*X(114)-JVS(337)*X(115)-JVS(338)&
            &*X(117)-JVS(339)*X(121)-JVS(340)*X(122))/(JVS(331))
  X(68) = (X(68)-JVS(326)*X(112)-JVS(327)*X(114)-JVS(328)*X(117))/(JVS(325))
  X(67) = (X(67)-JVS(322)*X(87)-JVS(323)*X(114)-JVS(324)*X(122))/(JVS(321))
  X(66) = (X(66)-JVS(312)*X(101)-JVS(313)*X(109)-JVS(314)*X(110)-JVS(315)*X(111)-JVS(316)*X(114)-JVS(317)*X(115)&
            &-JVS(318)*X(121)-JVS(319)*X(122))/(JVS(311))
  X(65) = (X(65)-JVS(303)*X(110)-JVS(304)*X(111)-JVS(305)*X(114)-JVS(306)*X(115)-JVS(307)*X(122))/(JVS(302))
  X(64) = (X(64)-JVS(299)*X(112)-JVS(300)*X(114)-JVS(301)*X(117))/(JVS(298))
  X(63) = (X(63)-JVS(288)*X(86)-JVS(289)*X(92)-JVS(290)*X(102)-JVS(291)*X(104)-JVS(292)*X(105)-JVS(293)*X(112)-JVS(294)&
            &*X(113)-JVS(295)*X(114)-JVS(296)*X(119)-JVS(297)*X(121))/(JVS(287))
  X(62) = (X(62)-JVS(281)*X(65)-JVS(282)*X(66)-JVS(283)*X(109)-JVS(284)*X(110)-JVS(285)*X(114)-JVS(286)*X(122))&
            &/(JVS(280))
  X(61) = (X(61)-JVS(272)*X(111)-JVS(273)*X(113)-JVS(274)*X(114)-JVS(275)*X(115)-JVS(276)*X(116)-JVS(277)*X(120)&
            &-JVS(278)*X(121))/(JVS(271))
  X(60) = (X(60)-JVS(264)*X(99)-JVS(265)*X(113)-JVS(266)*X(114)-JVS(267)*X(119)-JVS(268)*X(122))/(JVS(263))
  X(59) = (X(59)-JVS(258)*X(78)-JVS(259)*X(79)-JVS(260)*X(80)-JVS(261)*X(114)-JVS(262)*X(121))/(JVS(257))
  X(58) = (X(58)-JVS(251)*X(71)-JVS(252)*X(86)-JVS(253)*X(92)-JVS(254)*X(97)-JVS(255)*X(114)-JVS(256)*X(122))/(JVS(250))
  X(57) = (X(57)-JVS(243)*X(70)-JVS(244)*X(81)-JVS(245)*X(111)-JVS(246)*X(114)-JVS(247)*X(117)-JVS(248)*X(121))&
            &/(JVS(242))
  X(56) = (X(56)-JVS(238)*X(82)-JVS(239)*X(114)-JVS(240)*X(121))/(JVS(237))
  X(55) = (X(55)-JVS(235)*X(67)-JVS(236)*X(114))/(JVS(234))
  X(54) = (X(54)-JVS(231)*X(82)-JVS(232)*X(114)-JVS(233)*X(118))/(JVS(230))
  X(53) = (X(53)-JVS(209)*X(54)-JVS(210)*X(64)-JVS(211)*X(68)-JVS(212)*X(70)-JVS(213)*X(74)-JVS(214)*X(75)-JVS(215)&
            &*X(76)-JVS(216)*X(78)-JVS(217)*X(79)-JVS(218)*X(80)-JVS(219)*X(84)-JVS(220)*X(88)-JVS(221)*X(89)-JVS(222)*X(90)&
            &-JVS(223)*X(94)-JVS(224)*X(97)-JVS(225)*X(102)-JVS(226)*X(111)-JVS(227)*X(114)-JVS(228)*X(117)-JVS(229)*X(118))&
            &/(JVS(208))
  X(52) = (X(52)-JVS(204)*X(111)-JVS(205)*X(116)-JVS(206)*X(120))/(JVS(203))
  X(51) = (X(51)-JVS(201)*X(114)-JVS(202)*X(122))/(JVS(200))
  X(50) = (X(50)-JVS(197)*X(102)-JVS(198)*X(111)-JVS(199)*X(114))/(JVS(196))
  X(49) = (X(49)-JVS(194)*X(114)-JVS(195)*X(122))/(JVS(193))
  X(48) = (X(48)-JVS(190)*X(81)-JVS(191)*X(114)-JVS(192)*X(117))/(JVS(189))
  X(47) = (X(47)-JVS(186)*X(54)-JVS(187)*X(56)-JVS(188)*X(114))/(JVS(185))
  X(46) = (X(46)-JVS(183)*X(114)-JVS(184)*X(122))/(JVS(182))
  X(45) = (X(45)-JVS(175)*X(71)-JVS(176)*X(86)-JVS(177)*X(92)-JVS(178)*X(94)-JVS(179)*X(114)-JVS(180)*X(117)-JVS(181)&
            &*X(118))/(JVS(174))
  X(44) = (X(44)-JVS(171)*X(111)-JVS(172)*X(114)-JVS(173)*X(121))/(JVS(170))
  X(43) = (X(43)-JVS(166)*X(52)-JVS(167)*X(114)-JVS(168)*X(116)-JVS(169)*X(120))/(JVS(165))
  X(42) = (X(42)-JVS(162)*X(110)-JVS(163)*X(115)-JVS(164)*X(120))/(JVS(161))
  X(41) = (X(41)-JVS(158)*X(111)-JVS(159)*X(114)-JVS(160)*X(122))/(JVS(157))
  X(40) = (X(40)-JVS(155)*X(87)-JVS(156)*X(114))/(JVS(154))
  X(39) = (X(39)-JVS(151)*X(104)-JVS(152)*X(111)-JVS(153)*X(114))/(JVS(150))
  X(38) = (X(38)-JVS(144)*X(71)-JVS(145)*X(88)-JVS(146)*X(92)-JVS(147)*X(97)-JVS(148)*X(112)-JVS(149)*X(114))/(JVS(143))
  X(37) = (X(37)-JVS(139)*X(113)-JVS(140)*X(114)-JVS(141)*X(121))/(JVS(138))
  X(36) = (X(36)-JVS(136)*X(105)-JVS(137)*X(111))/(JVS(135))
  X(35) = (X(35)-JVS(133)*X(82)-JVS(134)*X(114))/(JVS(132))
  X(34) = (X(34)-JVS(127)*X(102)-JVS(128)*X(104)-JVS(129)*X(105)-JVS(130)*X(114)-JVS(131)*X(121))/(JVS(126))
  X(33) = (X(33)-JVS(123)*X(70)-JVS(124)*X(114)-JVS(125)*X(118))/(JVS(122))
  X(32) = (X(32)-JVS(119)*X(109)-JVS(120)*X(111)-JVS(121)*X(118))/(JVS(118))
  X(31) = (X(31)-JVS(114)*X(88)-JVS(115)*X(112)-JVS(116)*X(114))/(JVS(113))
  X(30) = (X(30)-JVS(107)*X(64)-JVS(108)*X(88)-JVS(109)*X(112)-JVS(110)*X(114)-JVS(111)*X(115)-JVS(112)*X(117))&
            &/(JVS(106))
  X(29) = (X(29)-JVS(98)*X(30)-JVS(99)*X(64)-JVS(100)*X(88)-JVS(101)*X(97)-JVS(102)*X(112)-JVS(103)*X(114)-JVS(104)&
            &*X(115)-JVS(105)*X(117))/(JVS(97))
  X(28) = (X(28)-JVS(89)*X(29)-JVS(90)*X(64)-JVS(91)*X(88)-JVS(92)*X(97)-JVS(93)*X(112)-JVS(94)*X(114)-JVS(95)*X(115)&
            &-JVS(96)*X(117))/(JVS(88))
  X(27) = (X(27)-JVS(80)*X(28)-JVS(81)*X(64)-JVS(82)*X(88)-JVS(83)*X(97)-JVS(84)*X(112)-JVS(85)*X(114)-JVS(86)*X(115)&
            &-JVS(87)*X(117))/(JVS(79))
  X(26) = (X(26)-JVS(77)*X(111)-JVS(78)*X(118))/(JVS(76))
  X(25) = (X(25)-JVS(75)*X(114))/(JVS(74))
  X(24) = (X(24)-JVS(73)*X(114))/(JVS(72))
  X(23) = (X(23)-JVS(70)*X(111)-JVS(71)*X(117))/(JVS(69))
  X(22) = (X(22)-JVS(67)*X(110)-JVS(68)*X(122))/(JVS(66))
  X(21) = (X(21)-JVS(65)*X(114))/(JVS(64))
  X(20) = (X(20)-JVS(62)*X(114))/(JVS(61))
  X(19) = (X(19)-JVS(57)*X(20)-JVS(58)*X(24)-JVS(59)*X(25)-JVS(60)*X(114))/(JVS(56))
  X(18) = (X(18)-JVS(50)*X(19)-JVS(51)*X(20)-JVS(52)*X(24)-JVS(53)*X(25)-JVS(54)*X(114))/(JVS(49))
  X(17) = (X(17)-JVS(44)*X(18)-JVS(45)*X(20)-JVS(46)*X(24)-JVS(47)*X(25)-JVS(48)*X(114))/(JVS(43))
  X(16) = (X(16)-JVS(38)*X(17)-JVS(39)*X(20)-JVS(40)*X(24)-JVS(41)*X(25)-JVS(42)*X(114))/(JVS(37))
  X(15) = (X(15)-JVS(36)*X(114))/(JVS(35))
  X(14) = (X(14)-JVS(30)*X(22)-JVS(31)*X(110)-JVS(32)*X(117)-JVS(33)*X(120)-JVS(34)*X(122))/(JVS(29))
  X(13) = (X(13)-JVS(28)*X(114))/(JVS(27))
  X(12) = (X(12)-JVS(25)*X(111)-JVS(26)*X(116))/(JVS(24))
  X(11) = (X(11)-JVS(23)*X(114))/(JVS(22))
  X(10) = (X(10)-JVS(21)*X(114))/(JVS(20))
  X(9) = (X(9)-JVS(18)*X(114))/(JVS(17))
  X(8) = (X(8)-JVS(15)*X(114))/(JVS(14))
  X(7) = (X(7)-JVS(13)*X(114))/(JVS(12))
  X(6) = (X(6)-JVS(11)*X(114))/(JVS(10))
  X(5) = (X(5)-JVS(8)*X(27)-JVS(9)*X(114))/(JVS(7))
  X(4) = (X(4)-JVS(5)*X(16)-JVS(6)*X(114))/(JVS(4))
  X(3) = X(3)/JVS(3)
  X(2) = X(2)/JVS(2)
  X(1) = X(1)/JVS(1)
      
END SUBROUTINE KppSolve

! End of KppSolve function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! KppSolveTR - sparse, transposed back substitution
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      X         - Vector for variables
!      XX        - Vector for output variables
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE KppSolveTR ( JVS, X, XX )

! JVS - sparse Jacobian of variables
  REAL(kind=sp) :: JVS(LU_NONZERO)
! X - Vector for variables
  REAL(kind=sp) :: X(NVAR)
! XX - Vector for output variables
  REAL(kind=sp) :: XX(NVAR)

  XX(1) = X(1)/JVS(1)
  XX(2) = X(2)/JVS(2)
  XX(3) = X(3)/JVS(3)
  XX(4) = X(4)/JVS(4)
  XX(5) = X(5)/JVS(7)
  XX(6) = X(6)/JVS(10)
  XX(7) = X(7)/JVS(12)
  XX(8) = X(8)/JVS(14)
  XX(9) = X(9)/JVS(17)
  XX(10) = X(10)/JVS(20)
  XX(11) = X(11)/JVS(22)
  XX(12) = X(12)/JVS(24)
  XX(13) = X(13)/JVS(27)
  XX(14) = X(14)/JVS(29)
  XX(15) = X(15)/JVS(35)
  XX(16) = (X(16)-JVS(5)*XX(4))/(JVS(37))
  XX(17) = (X(17)-JVS(38)*XX(16))/(JVS(43))
  XX(18) = (X(18)-JVS(44)*XX(17))/(JVS(49))
  XX(19) = (X(19)-JVS(50)*XX(18))/(JVS(56))
  XX(20) = (X(20)-JVS(39)*XX(16)-JVS(45)*XX(17)-JVS(51)*XX(18)-JVS(57)*XX(19))/(JVS(61))
  XX(21) = X(21)/JVS(64)
  XX(22) = (X(22)-JVS(30)*XX(14))/(JVS(66))
  XX(23) = X(23)/JVS(69)
  XX(24) = (X(24)-JVS(40)*XX(16)-JVS(46)*XX(17)-JVS(52)*XX(18)-JVS(58)*XX(19))/(JVS(72))
  XX(25) = (X(25)-JVS(41)*XX(16)-JVS(47)*XX(17)-JVS(53)*XX(18)-JVS(59)*XX(19))/(JVS(74))
  XX(26) = X(26)/JVS(76)
  XX(27) = (X(27)-JVS(8)*XX(5))/(JVS(79))
  XX(28) = (X(28)-JVS(80)*XX(27))/(JVS(88))
  XX(29) = (X(29)-JVS(89)*XX(28))/(JVS(97))
  XX(30) = (X(30)-JVS(98)*XX(29))/(JVS(106))
  XX(31) = X(31)/JVS(113)
  XX(32) = X(32)/JVS(118)
  XX(33) = X(33)/JVS(122)
  XX(34) = X(34)/JVS(126)
  XX(35) = X(35)/JVS(132)
  XX(36) = X(36)/JVS(135)
  XX(37) = X(37)/JVS(138)
  XX(38) = X(38)/JVS(143)
  XX(39) = X(39)/JVS(150)
  XX(40) = X(40)/JVS(154)
  XX(41) = X(41)/JVS(157)
  XX(42) = X(42)/JVS(161)
  XX(43) = X(43)/JVS(165)
  XX(44) = X(44)/JVS(170)
  XX(45) = X(45)/JVS(174)
  XX(46) = X(46)/JVS(182)
  XX(47) = X(47)/JVS(185)
  XX(48) = X(48)/JVS(189)
  XX(49) = X(49)/JVS(193)
  XX(50) = X(50)/JVS(196)
  XX(51) = X(51)/JVS(200)
  XX(52) = (X(52)-JVS(166)*XX(43))/(JVS(203))
  XX(53) = X(53)/JVS(208)
  XX(54) = (X(54)-JVS(186)*XX(47)-JVS(209)*XX(53))/(JVS(230))
  XX(55) = X(55)/JVS(234)
  XX(56) = (X(56)-JVS(187)*XX(47))/(JVS(237))
  XX(57) = X(57)/JVS(242)
  XX(58) = X(58)/JVS(250)
  XX(59) = X(59)/JVS(257)
  XX(60) = X(60)/JVS(263)
  XX(61) = X(61)/JVS(271)
  XX(62) = X(62)/JVS(280)
  XX(63) = X(63)/JVS(287)
  XX(64) = (X(64)-JVS(81)*XX(27)-JVS(90)*XX(28)-JVS(99)*XX(29)-JVS(107)*XX(30)-JVS(210)*XX(53))/(JVS(298))
  XX(65) = (X(65)-JVS(281)*XX(62))/(JVS(302))
  XX(66) = (X(66)-JVS(282)*XX(62))/(JVS(311))
  XX(67) = (X(67)-JVS(235)*XX(55))/(JVS(321))
  XX(68) = (X(68)-JVS(211)*XX(53))/(JVS(325))
  XX(69) = X(69)/JVS(331)
  XX(70) = (X(70)-JVS(123)*XX(33)-JVS(212)*XX(53)-JVS(243)*XX(57))/(JVS(342))
  XX(71) = (X(71)-JVS(144)*XX(38)-JVS(175)*XX(45)-JVS(251)*XX(58))/(JVS(348))
  XX(72) = X(72)/JVS(359)
  XX(73) = X(73)/JVS(385)
  XX(74) = (X(74)-JVS(213)*XX(53))/(JVS(396))
  XX(75) = (X(75)-JVS(214)*XX(53)-JVS(360)*XX(72))/(JVS(406))
  XX(76) = (X(76)-JVS(215)*XX(53))/(JVS(412))
  XX(77) = X(77)/JVS(422)
  XX(78) = (X(78)-JVS(216)*XX(53)-JVS(258)*XX(59))/(JVS(437))
  XX(79) = (X(79)-JVS(217)*XX(53)-JVS(259)*XX(59)-JVS(438)*XX(78))/(JVS(447))
  XX(80) = (X(80)-JVS(218)*XX(53)-JVS(260)*XX(59)-JVS(439)*XX(78)-JVS(448)*XX(79))/(JVS(457))
  XX(81) = (X(81)-JVS(190)*XX(48)-JVS(244)*XX(57)-JVS(343)*XX(70))/(JVS(467))
  XX(82) = (X(82)-JVS(133)*XX(35)-JVS(231)*XX(54)-JVS(238)*XX(56)-JVS(361)*XX(72)-JVS(407)*XX(75)-JVS(423)*XX(77))&
             &/(JVS(472))
  XX(83) = X(83)/JVS(493)
  XX(84) = (X(84)-JVS(219)*XX(53)-JVS(424)*XX(77)-JVS(494)*XX(83))/(JVS(516))
  XX(85) = (X(85)-JVS(362)*XX(72))/(JVS(527))
  XX(86) = (X(86)-JVS(176)*XX(45)-JVS(252)*XX(58)-JVS(288)*XX(63)-JVS(332)*XX(69)-JVS(363)*XX(72))/(JVS(537))
  XX(87) = (X(87)-JVS(155)*XX(40)-JVS(322)*XX(67)-JVS(528)*XX(85))/(JVS(547))
  XX(88) = (X(88)-JVS(82)*XX(27)-JVS(91)*XX(28)-JVS(100)*XX(29)-JVS(108)*XX(30)-JVS(114)*XX(31)-JVS(145)*XX(38)-JVS(220)&
             &*XX(53)-JVS(333)*XX(69)-JVS(413)*XX(76)-JVS(425)*XX(77)-JVS(495)*XX(83)-JVS(529)*XX(85))/(JVS(553))
  XX(89) = (X(89)-JVS(221)*XX(53)-JVS(364)*XX(72)-JVS(496)*XX(83))/(JVS(570))
  XX(90) = (X(90)-JVS(222)*XX(53)-JVS(365)*XX(72)-JVS(497)*XX(83))/(JVS(583))
  XX(91) = (X(91)-JVS(366)*XX(72)-JVS(498)*XX(83))/(JVS(600))
  XX(92) = (X(92)-JVS(146)*XX(38)-JVS(177)*XX(45)-JVS(253)*XX(58)-JVS(289)*XX(63)-JVS(334)*XX(69)-JVS(367)*XX(72)&
             &-JVS(548)*XX(87)-JVS(601)*XX(91))/(JVS(615))
  XX(93) = (X(93)-JVS(368)*XX(72)-JVS(499)*XX(83))/(JVS(632))
  XX(94) = (X(94)-JVS(178)*XX(45)-JVS(223)*XX(53)-JVS(426)*XX(77)-JVS(500)*XX(83))/(JVS(662))
  XX(95) = (X(95)-JVS(369)*XX(72)-JVS(501)*XX(83)-JVS(602)*XX(91)-JVS(633)*XX(93))/(JVS(683))
  XX(96) = (X(96)-JVS(427)*XX(77)-JVS(663)*XX(94))/(JVS(708))
  XX(97) = (X(97)-JVS(83)*XX(27)-JVS(92)*XX(28)-JVS(101)*XX(29)-JVS(147)*XX(38)-JVS(224)*XX(53)-JVS(254)*XX(58)-JVS(370)&
             &*XX(72)-JVS(473)*XX(82)-JVS(502)*XX(83)-JVS(571)*XX(89)-JVS(603)*XX(91)-JVS(634)*XX(93)-JVS(664)*XX(94)&
             &-JVS(709)*XX(96))/(JVS(721))
  XX(98) = (X(98)-JVS(428)*XX(77)-JVS(665)*XX(94))/(JVS(748))
  XX(99) = (X(99)-JVS(264)*XX(60)-JVS(371)*XX(72)-JVS(503)*XX(83)-JVS(604)*XX(91)-JVS(710)*XX(96)-JVS(749)*XX(98))&
             &/(JVS(768))
  XX(100) = X(100)/JVS(788)
  XX(101) = (X(101)-JVS(312)*XX(66))/(JVS(803))
  XX(102) = (X(102)-JVS(127)*XX(34)-JVS(197)*XX(50)-JVS(225)*XX(53)-JVS(290)*XX(63)-JVS(372)*XX(72)-JVS(504)*XX(83)&
              &-JVS(605)*XX(91)-JVS(711)*XX(96)-JVS(750)*XX(98))/(JVS(820))
  XX(103) = X(103)/JVS(837)
  XX(104) = (X(104)-JVS(128)*XX(34)-JVS(151)*XX(39)-JVS(291)*XX(63)-JVS(751)*XX(98))/(JVS(861))
  XX(105) = (X(105)-JVS(129)*XX(34)-JVS(136)*XX(36)-JVS(292)*XX(63))/(JVS(889))
  XX(106) = (X(106)-JVS(373)*XX(72)-JVS(386)*XX(73)-JVS(505)*XX(83)-JVS(752)*XX(98)-JVS(789)*XX(100)-JVS(838)*XX(103)&
              &-JVS(862)*XX(104)-JVS(890)*XX(105))/(JVS(912))
  XX(107) = (X(107)-JVS(374)*XX(72)-JVS(387)*XX(73)-JVS(506)*XX(83)-JVS(790)*XX(100)-JVS(839)*XX(103)-JVS(891)*XX(105))&
              &/(JVS(935))
  XX(108) = (X(108)-JVS(375)*XX(72)-JVS(388)*XX(73)-JVS(507)*XX(83)-JVS(791)*XX(100)-JVS(840)*XX(103))/(JVS(976))
  XX(109) = (X(109)-JVS(119)*XX(32)-JVS(283)*XX(62)-JVS(313)*XX(66)-JVS(389)*XX(73)-JVS(792)*XX(100)-JVS(841)*XX(103))&
              &/(JVS(999))
  XX(110) = (X(110)-JVS(31)*XX(14)-JVS(67)*XX(22)-JVS(162)*XX(42)-JVS(284)*XX(62)-JVS(303)*XX(65)-JVS(314)*XX(66)&
              &-JVS(793)*XX(100)-JVS(804)*XX(101)-JVS(842)*XX(103)-JVS(1000)*XX(109))/(JVS(1023))
  XX(111) = (X(111)-JVS(25)*XX(12)-JVS(70)*XX(23)-JVS(77)*XX(26)-JVS(120)*XX(32)-JVS(137)*XX(36)-JVS(152)*XX(39)&
              &-JVS(158)*XX(41)-JVS(171)*XX(44)-JVS(198)*XX(50)-JVS(204)*XX(52)-JVS(226)*XX(53)-JVS(245)*XX(57)-JVS(272)&
              &*XX(61)-JVS(304)*XX(65)-JVS(315)*XX(66)-JVS(344)*XX(70)-JVS(376)*XX(72)-JVS(468)*XX(81)-JVS(508)*XX(83)&
              &-JVS(606)*XX(91)-JVS(635)*XX(93)-JVS(666)*XX(94)-JVS(684)*XX(95)-JVS(712)*XX(96)-JVS(753)*XX(98)-JVS(821)&
              &*XX(102)-JVS(843)*XX(103)-JVS(863)*XX(104)-JVS(892)*XX(105)-JVS(913)*XX(106)-JVS(936)*XX(107)-JVS(977)&
              &*XX(108)-JVS(1001)*XX(109)-JVS(1024)*XX(110))/(JVS(1087))
  XX(112) = (X(112)-JVS(84)*XX(27)-JVS(93)*XX(28)-JVS(102)*XX(29)-JVS(109)*XX(30)-JVS(115)*XX(31)-JVS(148)*XX(38)&
              &-JVS(293)*XX(63)-JVS(299)*XX(64)-JVS(326)*XX(68)-JVS(335)*XX(69)-JVS(349)*XX(71)-JVS(377)*XX(72)-JVS(397)&
              &*XX(74)-JVS(429)*XX(77)-JVS(509)*XX(83)-JVS(517)*XX(84)-JVS(530)*XX(85)-JVS(538)*XX(86)-JVS(549)*XX(87)&
              &-JVS(554)*XX(88)-JVS(572)*XX(89)-JVS(584)*XX(90)-JVS(607)*XX(91)-JVS(616)*XX(92)-JVS(636)*XX(93)-JVS(667)&
              &*XX(94)-JVS(685)*XX(95)-JVS(713)*XX(96)-JVS(722)*XX(97)-JVS(754)*XX(98)-JVS(769)*XX(99)-JVS(794)*XX(100)&
              &-JVS(805)*XX(101)-JVS(822)*XX(102)-JVS(844)*XX(103)-JVS(864)*XX(104)-JVS(893)*XX(105)-JVS(914)*XX(106)&
              &-JVS(937)*XX(107)-JVS(978)*XX(108)-JVS(1002)*XX(109)-JVS(1025)*XX(110)-JVS(1088)*XX(111))/(JVS(1119))
  XX(113) = (X(113)-JVS(139)*XX(37)-JVS(265)*XX(60)-JVS(273)*XX(61)-JVS(294)*XX(63)-JVS(795)*XX(100)-JVS(845)*XX(103)&
              &-JVS(894)*XX(105)-JVS(979)*XX(108)-JVS(1003)*XX(109)-JVS(1026)*XX(110)-JVS(1089)*XX(111)-JVS(1120)*XX(112))&
              &/(JVS(1152))
  XX(114) = (X(114)-JVS(6)*XX(4)-JVS(9)*XX(5)-JVS(11)*XX(6)-JVS(13)*XX(7)-JVS(15)*XX(8)-JVS(18)*XX(9)-JVS(21)*XX(10)&
              &-JVS(23)*XX(11)-JVS(28)*XX(13)-JVS(36)*XX(15)-JVS(42)*XX(16)-JVS(48)*XX(17)-JVS(54)*XX(18)-JVS(60)*XX(19)&
              &-JVS(62)*XX(20)-JVS(65)*XX(21)-JVS(73)*XX(24)-JVS(75)*XX(25)-JVS(85)*XX(27)-JVS(94)*XX(28)-JVS(103)*XX(29)&
              &-JVS(110)*XX(30)-JVS(116)*XX(31)-JVS(124)*XX(33)-JVS(130)*XX(34)-JVS(134)*XX(35)-JVS(140)*XX(37)-JVS(149)&
              &*XX(38)-JVS(153)*XX(39)-JVS(156)*XX(40)-JVS(159)*XX(41)-JVS(167)*XX(43)-JVS(172)*XX(44)-JVS(179)*XX(45)&
              &-JVS(183)*XX(46)-JVS(188)*XX(47)-JVS(191)*XX(48)-JVS(194)*XX(49)-JVS(199)*XX(50)-JVS(201)*XX(51)-JVS(227)&
              &*XX(53)-JVS(232)*XX(54)-JVS(236)*XX(55)-JVS(239)*XX(56)-JVS(246)*XX(57)-JVS(255)*XX(58)-JVS(261)*XX(59)&
              &-JVS(266)*XX(60)-JVS(274)*XX(61)-JVS(285)*XX(62)-JVS(295)*XX(63)-JVS(300)*XX(64)-JVS(305)*XX(65)-JVS(316)&
              &*XX(66)-JVS(323)*XX(67)-JVS(327)*XX(68)-JVS(336)*XX(69)-JVS(345)*XX(70)-JVS(350)*XX(71)-JVS(378)*XX(72)&
              &-JVS(390)*XX(73)-JVS(398)*XX(74)-JVS(408)*XX(75)-JVS(414)*XX(76)-JVS(430)*XX(77)-JVS(440)*XX(78)-JVS(449)&
              &*XX(79)-JVS(458)*XX(80)-JVS(469)*XX(81)-JVS(474)*XX(82)-JVS(510)*XX(83)-JVS(518)*XX(84)-JVS(531)*XX(85)&
              &-JVS(539)*XX(86)-JVS(550)*XX(87)-JVS(555)*XX(88)-JVS(573)*XX(89)-JVS(585)*XX(90)-JVS(608)*XX(91)-JVS(617)&
              &*XX(92)-JVS(637)*XX(93)-JVS(668)*XX(94)-JVS(686)*XX(95)-JVS(714)*XX(96)-JVS(723)*XX(97)-JVS(755)*XX(98)&
              &-JVS(770)*XX(99)-JVS(796)*XX(100)-JVS(806)*XX(101)-JVS(823)*XX(102)-JVS(846)*XX(103)-JVS(865)*XX(104)&
              &-JVS(895)*XX(105)-JVS(915)*XX(106)-JVS(938)*XX(107)-JVS(980)*XX(108)-JVS(1004)*XX(109)-JVS(1027)*XX(110)&
              &-JVS(1090)*XX(111)-JVS(1121)*XX(112)-JVS(1153)*XX(113))/(JVS(1258))
  XX(115) = (X(115)-JVS(86)*XX(27)-JVS(95)*XX(28)-JVS(104)*XX(29)-JVS(111)*XX(30)-JVS(163)*XX(42)-JVS(275)*XX(61)&
              &-JVS(306)*XX(65)-JVS(317)*XX(66)-JVS(337)*XX(69)-JVS(391)*XX(73)-JVS(556)*XX(88)-JVS(574)*XX(89)-JVS(638)&
              &*XX(93)-JVS(669)*XX(94)-JVS(715)*XX(96)-JVS(724)*XX(97)-JVS(756)*XX(98)-JVS(771)*XX(99)-JVS(797)*XX(100)&
              &-JVS(807)*XX(101)-JVS(824)*XX(102)-JVS(847)*XX(103)-JVS(866)*XX(104)-JVS(896)*XX(105)-JVS(916)*XX(106)&
              &-JVS(939)*XX(107)-JVS(981)*XX(108)-JVS(1005)*XX(109)-JVS(1028)*XX(110)-JVS(1091)*XX(111)-JVS(1122)*XX(112)&
              &-JVS(1154)*XX(113)-JVS(1259)*XX(114))/(JVS(1290))
  XX(116) = (X(116)-JVS(26)*XX(12)-JVS(168)*XX(43)-JVS(205)*XX(52)-JVS(276)*XX(61)-JVS(379)*XX(72)-JVS(392)*XX(73)&
              &-JVS(808)*XX(101)-JVS(848)*XX(103)-JVS(867)*XX(104)-JVS(897)*XX(105)-JVS(917)*XX(106)-JVS(940)*XX(107)&
              &-JVS(982)*XX(108)-JVS(1006)*XX(109)-JVS(1029)*XX(110)-JVS(1092)*XX(111)-JVS(1123)*XX(112)-JVS(1155)*XX(113)&
              &-JVS(1260)*XX(114)-JVS(1291)*XX(115))/(JVS(1317))
  XX(117) = (X(117)-JVS(32)*XX(14)-JVS(71)*XX(23)-JVS(87)*XX(27)-JVS(96)*XX(28)-JVS(105)*XX(29)-JVS(112)*XX(30)-JVS(180)&
              &*XX(45)-JVS(192)*XX(48)-JVS(228)*XX(53)-JVS(247)*XX(57)-JVS(301)*XX(64)-JVS(328)*XX(68)-JVS(338)*XX(69)&
              &-JVS(346)*XX(70)-JVS(351)*XX(71)-JVS(380)*XX(72)-JVS(399)*XX(74)-JVS(431)*XX(77)-JVS(470)*XX(81)-JVS(511)&
              &*XX(83)-JVS(519)*XX(84)-JVS(532)*XX(85)-JVS(540)*XX(86)-JVS(551)*XX(87)-JVS(557)*XX(88)-JVS(575)*XX(89)&
              &-JVS(586)*XX(90)-JVS(609)*XX(91)-JVS(618)*XX(92)-JVS(639)*XX(93)-JVS(670)*XX(94)-JVS(687)*XX(95)-JVS(716)&
              &*XX(96)-JVS(725)*XX(97)-JVS(757)*XX(98)-JVS(772)*XX(99)-JVS(798)*XX(100)-JVS(809)*XX(101)-JVS(825)*XX(102)&
              &-JVS(849)*XX(103)-JVS(868)*XX(104)-JVS(898)*XX(105)-JVS(918)*XX(106)-JVS(941)*XX(107)-JVS(983)*XX(108)&
              &-JVS(1007)*XX(109)-JVS(1030)*XX(110)-JVS(1093)*XX(111)-JVS(1124)*XX(112)-JVS(1156)*XX(113)-JVS(1261)*XX(114)&
              &-JVS(1292)*XX(115)-JVS(1318)*XX(116))/(JVS(1363))
  XX(118) = (X(118)-JVS(78)*XX(26)-JVS(121)*XX(32)-JVS(125)*XX(33)-JVS(181)*XX(45)-JVS(229)*XX(53)-JVS(233)*XX(54)&
              &-JVS(381)*XX(72)-JVS(400)*XX(74)-JVS(409)*XX(75)-JVS(415)*XX(76)-JVS(432)*XX(77)-JVS(441)*XX(78)-JVS(450)&
              &*XX(79)-JVS(459)*XX(80)-JVS(475)*XX(82)-JVS(512)*XX(83)-JVS(520)*XX(84)-JVS(533)*XX(85)-JVS(576)*XX(89)&
              &-JVS(587)*XX(90)-JVS(610)*XX(91)-JVS(640)*XX(93)-JVS(671)*XX(94)-JVS(688)*XX(95)-JVS(717)*XX(96)-JVS(758)&
              &*XX(98)-JVS(773)*XX(99)-JVS(799)*XX(100)-JVS(810)*XX(101)-JVS(826)*XX(102)-JVS(850)*XX(103)-JVS(869)*XX(104)&
              &-JVS(899)*XX(105)-JVS(919)*XX(106)-JVS(942)*XX(107)-JVS(984)*XX(108)-JVS(1008)*XX(109)-JVS(1031)*XX(110)&
              &-JVS(1094)*XX(111)-JVS(1125)*XX(112)-JVS(1157)*XX(113)-JVS(1262)*XX(114)-JVS(1293)*XX(115)-JVS(1319)*XX(116)&
              &-JVS(1364)*XX(117))/(JVS(1405))
  XX(119) = (X(119)-JVS(267)*XX(60)-JVS(296)*XX(63)-JVS(382)*XX(72)-JVS(401)*XX(74)-JVS(410)*XX(75)-JVS(416)*XX(76)&
              &-JVS(433)*XX(77)-JVS(442)*XX(78)-JVS(451)*XX(79)-JVS(460)*XX(80)-JVS(476)*XX(82)-JVS(513)*XX(83)-JVS(521)&
              &*XX(84)-JVS(534)*XX(85)-JVS(577)*XX(89)-JVS(588)*XX(90)-JVS(611)*XX(91)-JVS(641)*XX(93)-JVS(672)*XX(94)&
              &-JVS(689)*XX(95)-JVS(718)*XX(96)-JVS(759)*XX(98)-JVS(774)*XX(99)-JVS(800)*XX(100)-JVS(827)*XX(102)-JVS(851)&
              &*XX(103)-JVS(870)*XX(104)-JVS(900)*XX(105)-JVS(920)*XX(106)-JVS(943)*XX(107)-JVS(985)*XX(108)-JVS(1009)&
              &*XX(109)-JVS(1032)*XX(110)-JVS(1095)*XX(111)-JVS(1126)*XX(112)-JVS(1158)*XX(113)-JVS(1263)*XX(114)-JVS(1294)&
              &*XX(115)-JVS(1320)*XX(116)-JVS(1365)*XX(117)-JVS(1406)*XX(118))/(JVS(1466))
  XX(120) = (X(120)-JVS(33)*XX(14)-JVS(164)*XX(42)-JVS(169)*XX(43)-JVS(206)*XX(52)-JVS(277)*XX(61)-JVS(393)*XX(73)&
              &-JVS(811)*XX(101)-JVS(852)*XX(103)-JVS(901)*XX(105)-JVS(986)*XX(108)-JVS(1010)*XX(109)-JVS(1033)*XX(110)&
              &-JVS(1096)*XX(111)-JVS(1127)*XX(112)-JVS(1159)*XX(113)-JVS(1264)*XX(114)-JVS(1295)*XX(115)-JVS(1321)*XX(116)&
              &-JVS(1366)*XX(117)-JVS(1407)*XX(118)-JVS(1467)*XX(119))/(JVS(1490))
  XX(121) = (X(121)-JVS(131)*XX(34)-JVS(141)*XX(37)-JVS(173)*XX(44)-JVS(240)*XX(56)-JVS(248)*XX(57)-JVS(262)*XX(59)&
              &-JVS(278)*XX(61)-JVS(297)*XX(63)-JVS(318)*XX(66)-JVS(339)*XX(69)-JVS(347)*XX(70)-JVS(383)*XX(72)-JVS(394)&
              &*XX(73)-JVS(402)*XX(74)-JVS(411)*XX(75)-JVS(417)*XX(76)-JVS(434)*XX(77)-JVS(443)*XX(78)-JVS(452)*XX(79)&
              &-JVS(461)*XX(80)-JVS(471)*XX(81)-JVS(477)*XX(82)-JVS(514)*XX(83)-JVS(522)*XX(84)-JVS(535)*XX(85)-JVS(578)&
              &*XX(89)-JVS(589)*XX(90)-JVS(612)*XX(91)-JVS(642)*XX(93)-JVS(673)*XX(94)-JVS(690)*XX(95)-JVS(719)*XX(96)&
              &-JVS(760)*XX(98)-JVS(775)*XX(99)-JVS(801)*XX(100)-JVS(828)*XX(102)-JVS(853)*XX(103)-JVS(871)*XX(104)-JVS(902)&
              &*XX(105)-JVS(921)*XX(106)-JVS(944)*XX(107)-JVS(987)*XX(108)-JVS(1011)*XX(109)-JVS(1034)*XX(110)-JVS(1097)&
              &*XX(111)-JVS(1128)*XX(112)-JVS(1160)*XX(113)-JVS(1265)*XX(114)-JVS(1296)*XX(115)-JVS(1322)*XX(116)-JVS(1367)&
              &*XX(117)-JVS(1408)*XX(118)-JVS(1468)*XX(119)-JVS(1491)*XX(120))/(JVS(1562))
  XX(122) = (X(122)-JVS(34)*XX(14)-JVS(68)*XX(22)-JVS(160)*XX(41)-JVS(184)*XX(46)-JVS(195)*XX(49)-JVS(202)*XX(51)&
              &-JVS(256)*XX(58)-JVS(268)*XX(60)-JVS(286)*XX(62)-JVS(307)*XX(65)-JVS(319)*XX(66)-JVS(324)*XX(67)-JVS(340)&
              &*XX(69)-JVS(352)*XX(71)-JVS(384)*XX(72)-JVS(536)*XX(85)-JVS(541)*XX(86)-JVS(552)*XX(87)-JVS(579)*XX(89)&
              &-JVS(613)*XX(91)-JVS(619)*XX(92)-JVS(643)*XX(93)-JVS(674)*XX(94)-JVS(720)*XX(96)-JVS(726)*XX(97)-JVS(761)&
              &*XX(98)-JVS(776)*XX(99)-JVS(802)*XX(100)-JVS(812)*XX(101)-JVS(829)*XX(102)-JVS(854)*XX(103)-JVS(872)*XX(104)&
              &-JVS(903)*XX(105)-JVS(922)*XX(106)-JVS(945)*XX(107)-JVS(988)*XX(108)-JVS(1012)*XX(109)-JVS(1035)*XX(110)&
              &-JVS(1098)*XX(111)-JVS(1129)*XX(112)-JVS(1161)*XX(113)-JVS(1266)*XX(114)-JVS(1297)*XX(115)-JVS(1323)*XX(116)&
              &-JVS(1368)*XX(117)-JVS(1409)*XX(118)-JVS(1469)*XX(119)-JVS(1492)*XX(120)-JVS(1563)*XX(121))/(JVS(1606))
  XX(122) = XX(122)
  XX(121) = XX(121)-JVS(1605)*XX(122)
  XX(120) = XX(120)-JVS(1561)*XX(121)-JVS(1604)*XX(122)
  XX(119) = XX(119)-JVS(1489)*XX(120)-JVS(1560)*XX(121)-JVS(1603)*XX(122)
  XX(118) = XX(118)-JVS(1465)*XX(119)-JVS(1488)*XX(120)-JVS(1559)*XX(121)-JVS(1602)*XX(122)
  XX(117) = XX(117)-JVS(1404)*XX(118)-JVS(1464)*XX(119)-JVS(1487)*XX(120)-JVS(1558)*XX(121)-JVS(1601)*XX(122)
  XX(116) = XX(116)-JVS(1362)*XX(117)-JVS(1403)*XX(118)-JVS(1463)*XX(119)-JVS(1486)*XX(120)-JVS(1557)*XX(121)-JVS(1600)&
              &*XX(122)
  XX(115) = XX(115)-JVS(1316)*XX(116)-JVS(1361)*XX(117)-JVS(1402)*XX(118)-JVS(1462)*XX(119)-JVS(1485)*XX(120)-JVS(1556)&
              &*XX(121)-JVS(1599)*XX(122)
  XX(114) = XX(114)-JVS(1289)*XX(115)-JVS(1315)*XX(116)-JVS(1360)*XX(117)-JVS(1401)*XX(118)-JVS(1461)*XX(119)-JVS(1484)&
              &*XX(120)-JVS(1555)*XX(121)-JVS(1598)*XX(122)
  XX(113) = XX(113)-JVS(1257)*XX(114)-JVS(1288)*XX(115)-JVS(1314)*XX(116)-JVS(1359)*XX(117)-JVS(1400)*XX(118)-JVS(1460)&
              &*XX(119)-JVS(1483)*XX(120)-JVS(1554)*XX(121)-JVS(1597)*XX(122)
  XX(112) = XX(112)-JVS(1151)*XX(113)-JVS(1256)*XX(114)-JVS(1287)*XX(115)-JVS(1313)*XX(116)-JVS(1358)*XX(117)-JVS(1399)&
              &*XX(118)-JVS(1459)*XX(119)-JVS(1482)*XX(120)-JVS(1553)*XX(121)-JVS(1596)*XX(122)
  XX(111) = XX(111)-JVS(1118)*XX(112)-JVS(1150)*XX(113)-JVS(1255)*XX(114)-JVS(1286)*XX(115)-JVS(1312)*XX(116)-JVS(1357)&
              &*XX(117)-JVS(1398)*XX(118)-JVS(1458)*XX(119)-JVS(1481)*XX(120)-JVS(1552)*XX(121)-JVS(1595)*XX(122)
  XX(110) = XX(110)-JVS(1086)*XX(111)-JVS(1117)*XX(112)-JVS(1149)*XX(113)-JVS(1254)*XX(114)-JVS(1285)*XX(115)-JVS(1311)&
              &*XX(116)-JVS(1356)*XX(117)-JVS(1397)*XX(118)-JVS(1480)*XX(120)-JVS(1551)*XX(121)-JVS(1594)*XX(122)
  XX(109) = XX(109)-JVS(1022)*XX(110)-JVS(1085)*XX(111)-JVS(1116)*XX(112)-JVS(1148)*XX(113)-JVS(1253)*XX(114)-JVS(1284)&
              &*XX(115)-JVS(1310)*XX(116)-JVS(1396)*XX(118)-JVS(1479)*XX(120)-JVS(1550)*XX(121)-JVS(1593)*XX(122)
  XX(108) = XX(108)-JVS(998)*XX(109)-JVS(1021)*XX(110)-JVS(1084)*XX(111)-JVS(1115)*XX(112)-JVS(1252)*XX(114)-JVS(1283)&
              &*XX(115)-JVS(1309)*XX(116)-JVS(1355)*XX(117)-JVS(1395)*XX(118)-JVS(1478)*XX(120)-JVS(1549)*XX(121)-JVS(1592)&
              &*XX(122)
  XX(107) = XX(107)-JVS(975)*XX(108)-JVS(997)*XX(109)-JVS(1020)*XX(110)-JVS(1083)*XX(111)-JVS(1114)*XX(112)-JVS(1147)&
              &*XX(113)-JVS(1251)*XX(114)-JVS(1282)*XX(115)-JVS(1308)*XX(116)-JVS(1354)*XX(117)-JVS(1394)*XX(118)-JVS(1457)&
              &*XX(119)-JVS(1477)*XX(120)-JVS(1548)*XX(121)-JVS(1591)*XX(122)
  XX(106) = XX(106)-JVS(934)*XX(107)-JVS(974)*XX(108)-JVS(996)*XX(109)-JVS(1019)*XX(110)-JVS(1082)*XX(111)-JVS(1113)&
              &*XX(112)-JVS(1146)*XX(113)-JVS(1250)*XX(114)-JVS(1281)*XX(115)-JVS(1307)*XX(116)-JVS(1353)*XX(117)-JVS(1393)&
              &*XX(118)-JVS(1456)*XX(119)-JVS(1476)*XX(120)-JVS(1547)*XX(121)-JVS(1590)*XX(122)
  XX(105) = XX(105)-JVS(973)*XX(108)-JVS(1081)*XX(111)-JVS(1112)*XX(112)-JVS(1145)*XX(113)-JVS(1249)*XX(114)-JVS(1306)&
              &*XX(116)-JVS(1352)*XX(117)-JVS(1392)*XX(118)-JVS(1455)*XX(119)-JVS(1475)*XX(120)-JVS(1546)*XX(121)
  XX(104) = XX(104)-JVS(888)*XX(105)-JVS(933)*XX(107)-JVS(1080)*XX(111)-JVS(1111)*XX(112)-JVS(1144)*XX(113)-JVS(1248)&
              &*XX(114)-JVS(1351)*XX(117)-JVS(1391)*XX(118)-JVS(1454)*XX(119)-JVS(1545)*XX(121)
  XX(103) = XX(103)-JVS(1079)*XX(111)-JVS(1110)*XX(112)-JVS(1247)*XX(114)-JVS(1280)*XX(115)-JVS(1390)*XX(118)-JVS(1544)&
              &*XX(121)
  XX(102) = XX(102)-JVS(860)*XX(104)-JVS(887)*XX(105)-JVS(911)*XX(106)-JVS(1078)*XX(111)-JVS(1109)*XX(112)-JVS(1143)&
              &*XX(113)-JVS(1246)*XX(114)-JVS(1350)*XX(117)-JVS(1389)*XX(118)-JVS(1453)*XX(119)-JVS(1543)*XX(121)
  XX(101) = XX(101)-JVS(995)*XX(109)-JVS(1018)*XX(110)-JVS(1077)*XX(111)-JVS(1108)*XX(112)-JVS(1245)*XX(114)-JVS(1279)&
              &*XX(115)-JVS(1305)*XX(116)-JVS(1388)*XX(118)-JVS(1474)*XX(120)-JVS(1589)*XX(122)
  XX(100) = XX(100)-JVS(836)*XX(103)-JVS(994)*XX(109)-JVS(1017)*XX(110)-JVS(1244)*XX(114)-JVS(1278)*XX(115)-JVS(1588)&
              &*XX(122)
  XX(99) = XX(99)-JVS(787)*XX(100)-JVS(886)*XX(105)-JVS(972)*XX(108)-JVS(1076)*XX(111)-JVS(1243)*XX(114)-JVS(1349)&
             &*XX(117)-JVS(1387)*XX(118)-JVS(1452)*XX(119)-JVS(1542)*XX(121)-JVS(1587)*XX(122)
  XX(98) = XX(98)-JVS(1075)*XX(111)-JVS(1242)*XX(114)-JVS(1348)*XX(117)-JVS(1386)*XX(118)-JVS(1451)*XX(119)-JVS(1541)&
             &*XX(121)
  XX(97) = XX(97)-JVS(747)*XX(98)-JVS(767)*XX(99)-JVS(786)*XX(100)-JVS(819)*XX(102)-JVS(835)*XX(103)-JVS(885)*XX(105)&
             &-JVS(971)*XX(108)-JVS(1074)*XX(111)-JVS(1107)*XX(112)-JVS(1142)*XX(113)-JVS(1241)*XX(114)-JVS(1347)*XX(117)&
             &-JVS(1385)*XX(118)-JVS(1450)*XX(119)-JVS(1540)*XX(121)-JVS(1586)*XX(122)
  XX(96) = XX(96)-JVS(746)*XX(98)-JVS(1073)*XX(111)-JVS(1240)*XX(114)-JVS(1346)*XX(117)-JVS(1384)*XX(118)-JVS(1449)&
             &*XX(119)-JVS(1539)*XX(121)
  XX(95) = XX(95)-JVS(707)*XX(96)-JVS(745)*XX(98)-JVS(818)*XX(102)-JVS(884)*XX(105)-JVS(932)*XX(107)-JVS(970)*XX(108)&
             &-JVS(1072)*XX(111)-JVS(1106)*XX(112)-JVS(1239)*XX(114)-JVS(1345)*XX(117)-JVS(1448)*XX(119)-JVS(1538)*XX(121)
  XX(94) = XX(94)-JVS(744)*XX(98)-JVS(1071)*XX(111)-JVS(1238)*XX(114)-JVS(1344)*XX(117)-JVS(1383)*XX(118)-JVS(1447)&
             &*XX(119)-JVS(1537)*XX(121)
  XX(93) = XX(93)-JVS(706)*XX(96)-JVS(883)*XX(105)-JVS(1070)*XX(111)-JVS(1237)*XX(114)-JVS(1343)*XX(117)-JVS(1446)&
             &*XX(119)-JVS(1536)*XX(121)
  XX(92) = XX(92)-JVS(631)*XX(93)-JVS(661)*XX(94)-JVS(705)*XX(96)-JVS(743)*XX(98)-JVS(785)*XX(100)-JVS(834)*XX(103)&
             &-JVS(859)*XX(104)-JVS(882)*XX(105)-JVS(910)*XX(106)-JVS(931)*XX(107)-JVS(969)*XX(108)-JVS(1069)*XX(111)&
             &-JVS(1105)*XX(112)-JVS(1141)*XX(113)-JVS(1236)*XX(114)-JVS(1277)*XX(115)-JVS(1342)*XX(117)-JVS(1445)*XX(119)&
             &-JVS(1535)*XX(121)-JVS(1585)*XX(122)
  XX(91) = XX(91)-JVS(704)*XX(96)-JVS(1068)*XX(111)-JVS(1235)*XX(114)-JVS(1341)*XX(117)-JVS(1444)*XX(119)-JVS(1534)&
             &*XX(121)
  XX(90) = XX(90)-JVS(599)*XX(91)-JVS(630)*XX(93)-JVS(660)*XX(94)-JVS(682)*XX(95)-JVS(703)*XX(96)-JVS(742)*XX(98)&
             &-JVS(881)*XX(105)-JVS(930)*XX(107)-JVS(1067)*XX(111)-JVS(1104)*XX(112)-JVS(1234)*XX(114)-JVS(1340)*XX(117)&
             &-JVS(1443)*XX(119)-JVS(1533)*XX(121)
  XX(89) = XX(89)-JVS(629)*XX(93)-JVS(766)*XX(99)-JVS(817)*XX(102)-JVS(880)*XX(105)-JVS(968)*XX(108)-JVS(1066)*XX(111)&
             &-JVS(1233)*XX(114)-JVS(1339)*XX(117)-JVS(1532)*XX(121)
  XX(88) = XX(88)-JVS(569)*XX(89)-JVS(628)*XX(93)-JVS(659)*XX(94)-JVS(702)*XX(96)-JVS(741)*XX(98)-JVS(784)*XX(100)&
             &-JVS(816)*XX(102)-JVS(833)*XX(103)-JVS(879)*XX(105)-JVS(967)*XX(108)-JVS(1065)*XX(111)-JVS(1103)*XX(112)&
             &-JVS(1140)*XX(113)-JVS(1232)*XX(114)-JVS(1276)*XX(115)-JVS(1338)*XX(117)-JVS(1382)*XX(118)-JVS(1442)*XX(119)&
             &-JVS(1531)*XX(121)-JVS(1584)*XX(122)
  XX(87) = XX(87)-JVS(658)*XX(94)-JVS(701)*XX(96)-JVS(740)*XX(98)-JVS(783)*XX(100)-JVS(858)*XX(104)-JVS(878)*XX(105)&
             &-JVS(909)*XX(106)-JVS(929)*XX(107)-JVS(966)*XX(108)-JVS(1139)*XX(113)-JVS(1231)*XX(114)-JVS(1441)*XX(119)&
             &-JVS(1530)*XX(121)-JVS(1583)*XX(122)
  XX(86) = XX(86)-JVS(546)*XX(87)-JVS(598)*XX(91)-JVS(614)*XX(92)-JVS(627)*XX(93)-JVS(657)*XX(94)-JVS(700)*XX(96)&
             &-JVS(739)*XX(98)-JVS(782)*XX(100)-JVS(908)*XX(106)-JVS(928)*XX(107)-JVS(965)*XX(108)-JVS(1064)*XX(111)&
             &-JVS(1102)*XX(112)-JVS(1138)*XX(113)-JVS(1230)*XX(114)-JVS(1275)*XX(115)-JVS(1337)*XX(117)-JVS(1440)*XX(119)&
             &-JVS(1529)*XX(121)-JVS(1582)*XX(122)
  XX(85) = XX(85)-JVS(699)*XX(96)-JVS(877)*XX(105)-JVS(964)*XX(108)-JVS(1137)*XX(113)-JVS(1229)*XX(114)-JVS(1439)&
             &*XX(119)-JVS(1528)*XX(121)
  XX(84) = XX(84)-JVS(526)*XX(85)-JVS(568)*XX(89)-JVS(656)*XX(94)-JVS(738)*XX(98)-JVS(963)*XX(108)-JVS(1063)*XX(111)&
             &-JVS(1228)*XX(114)-JVS(1336)*XX(117)-JVS(1381)*XX(118)-JVS(1438)*XX(119)-JVS(1527)*XX(121)
  XX(83) = XX(83)-JVS(1062)*XX(111)-JVS(1227)*XX(114)-JVS(1335)*XX(117)
  XX(82) = XX(82)-JVS(492)*XX(83)-JVS(567)*XX(89)-JVS(597)*XX(91)-JVS(626)*XX(93)-JVS(655)*XX(94)-JVS(737)*XX(98)&
             &-JVS(765)*XX(99)-JVS(962)*XX(108)-JVS(1061)*XX(111)-JVS(1226)*XX(114)-JVS(1380)*XX(118)-JVS(1437)*XX(119)&
             &-JVS(1526)*XX(121)
  XX(81) = XX(81)-JVS(491)*XX(83)-JVS(596)*XX(91)-JVS(625)*XX(93)-JVS(654)*XX(94)-JVS(681)*XX(95)-JVS(698)*XX(96)&
             &-JVS(736)*XX(98)-JVS(815)*XX(102)-JVS(961)*XX(108)-JVS(1060)*XX(111)-JVS(1225)*XX(114)-JVS(1334)*XX(117)&
             &-JVS(1379)*XX(118)-JVS(1436)*XX(119)-JVS(1525)*XX(121)
  XX(80) = XX(80)-JVS(490)*XX(83)-JVS(582)*XX(90)-JVS(595)*XX(91)-JVS(624)*XX(93)-JVS(680)*XX(95)-JVS(1059)*XX(111)&
             &-JVS(1224)*XX(114)-JVS(1378)*XX(118)-JVS(1435)*XX(119)-JVS(1524)*XX(121)
  XX(79) = XX(79)-JVS(456)*XX(80)-JVS(489)*XX(83)-JVS(581)*XX(90)-JVS(594)*XX(91)-JVS(623)*XX(93)-JVS(679)*XX(95)&
             &-JVS(1058)*XX(111)-JVS(1223)*XX(114)-JVS(1377)*XX(118)-JVS(1434)*XX(119)-JVS(1523)*XX(121)
  XX(78) = XX(78)-JVS(446)*XX(79)-JVS(455)*XX(80)-JVS(488)*XX(83)-JVS(593)*XX(91)-JVS(678)*XX(95)-JVS(1057)*XX(111)&
             &-JVS(1222)*XX(114)-JVS(1376)*XX(118)-JVS(1433)*XX(119)-JVS(1522)*XX(121)
  XX(77) = XX(77)-JVS(653)*XX(94)-JVS(735)*XX(98)-JVS(1221)*XX(114)-JVS(1432)*XX(119)-JVS(1521)*XX(121)
  XX(76) = XX(76)-JVS(421)*XX(77)-JVS(487)*XX(83)-JVS(525)*XX(85)-JVS(566)*XX(89)-JVS(652)*XX(94)-JVS(960)*XX(108)&
             &-JVS(1056)*XX(111)-JVS(1220)*XX(114)-JVS(1375)*XX(118)-JVS(1431)*XX(119)-JVS(1520)*XX(121)
  XX(75) = XX(75)-JVS(420)*XX(77)-JVS(486)*XX(83)-JVS(565)*XX(89)-JVS(592)*XX(91)-JVS(622)*XX(93)-JVS(764)*XX(99)&
             &-JVS(959)*XX(108)-JVS(1055)*XX(111)-JVS(1219)*XX(114)-JVS(1374)*XX(118)-JVS(1519)*XX(121)
  XX(74) = XX(74)-JVS(419)*XX(77)-JVS(485)*XX(83)-JVS(564)*XX(89)-JVS(651)*XX(94)-JVS(1054)*XX(111)-JVS(1218)*XX(114)&
             &-JVS(1373)*XX(118)-JVS(1430)*XX(119)-JVS(1518)*XX(121)
  XX(73) = XX(73)-JVS(832)*XX(103)-JVS(993)*XX(109)-JVS(1217)*XX(114)-JVS(1274)*XX(115)-JVS(1304)*XX(116)-JVS(1473)&
             &*XX(120)
  XX(72) = XX(72)-JVS(1216)*XX(114)-JVS(1517)*XX(121)
  XX(71) = XX(71)-JVS(358)*XX(72)-JVS(697)*XX(96)-JVS(734)*XX(98)-JVS(763)*XX(99)-JVS(831)*XX(103)-JVS(958)*XX(108)&
             &-JVS(1053)*XX(111)-JVS(1101)*XX(112)-JVS(1215)*XX(114)-JVS(1333)*XX(117)-JVS(1429)*XX(119)-JVS(1516)*XX(121)&
             &-JVS(1581)*XX(122)
  XX(70) = XX(70)-JVS(466)*XX(81)-JVS(484)*XX(83)-JVS(677)*XX(95)-JVS(957)*XX(108)-JVS(1052)*XX(111)-JVS(1214)*XX(114)&
             &-JVS(1332)*XX(117)-JVS(1372)*XX(118)-JVS(1515)*XX(121)
  XX(69) = XX(69)-JVS(781)*XX(100)-JVS(1213)*XX(114)-JVS(1273)*XX(115)-JVS(1514)*XX(121)-JVS(1580)*XX(122)
  XX(68) = XX(68)-JVS(330)*XX(69)-JVS(357)*XX(72)-JVS(483)*XX(83)-JVS(515)*XX(84)-JVS(563)*XX(89)-JVS(650)*XX(94)&
             &-JVS(696)*XX(96)-JVS(814)*XX(102)-JVS(956)*XX(108)-JVS(1051)*XX(111)-JVS(1100)*XX(112)-JVS(1212)*XX(114)&
             &-JVS(1331)*XX(117)-JVS(1428)*XX(119)-JVS(1513)*XX(121)
  XX(67) = XX(67)-JVS(524)*XX(85)-JVS(545)*XX(87)-JVS(649)*XX(94)-JVS(695)*XX(96)-JVS(733)*XX(98)-JVS(857)*XX(104)&
             &-JVS(876)*XX(105)-JVS(907)*XX(106)-JVS(927)*XX(107)-JVS(955)*XX(108)-JVS(1136)*XX(113)-JVS(1211)*XX(114)&
             &-JVS(1427)*XX(119)-JVS(1512)*XX(121)
  XX(66) = XX(66)-JVS(992)*XX(109)-JVS(1016)*XX(110)-JVS(1210)*XX(114)-JVS(1272)*XX(115)-JVS(1579)*XX(122)
  XX(65) = XX(65)-JVS(310)*XX(66)-JVS(991)*XX(109)-JVS(1015)*XX(110)-JVS(1050)*XX(111)-JVS(1209)*XX(114)-JVS(1271)&
             &*XX(115)-JVS(1330)*XX(117)-JVS(1578)*XX(122)
  XX(64) = XX(64)-JVS(329)*XX(69)-JVS(395)*XX(74)-JVS(482)*XX(83)-JVS(562)*XX(89)-JVS(648)*XX(94)-JVS(954)*XX(108)&
             &-JVS(1049)*XX(111)-JVS(1099)*XX(112)-JVS(1208)*XX(114)-JVS(1329)*XX(117)-JVS(1426)*XX(119)-JVS(1511)*XX(121)
  XX(63) = XX(63)-JVS(1135)*XX(113)-JVS(1207)*XX(114)-JVS(1425)*XX(119)
  XX(62) = XX(62)-JVS(309)*XX(66)-JVS(990)*XX(109)-JVS(1014)*XX(110)-JVS(1206)*XX(114)-JVS(1577)*XX(122)
  XX(61) = XX(61)-JVS(1205)*XX(114)-JVS(1270)*XX(115)-JVS(1303)*XX(116)-JVS(1472)*XX(120)
  XX(60) = XX(60)-JVS(780)*XX(100)-JVS(953)*XX(108)-JVS(1204)*XX(114)-JVS(1510)*XX(121)-JVS(1576)*XX(122)
  XX(59) = XX(59)-JVS(436)*XX(78)-JVS(445)*XX(79)-JVS(454)*XX(80)-JVS(1203)*XX(114)-JVS(1424)*XX(119)
  XX(58) = XX(58)-JVS(356)*XX(72)-JVS(1202)*XX(114)-JVS(1509)*XX(121)-JVS(1575)*XX(122)
  XX(57) = XX(57)-JVS(341)*XX(70)-JVS(465)*XX(81)-JVS(1048)*XX(111)-JVS(1508)*XX(121)
  XX(56) = XX(56)-JVS(405)*XX(75)-JVS(418)*XX(77)-JVS(561)*XX(89)-JVS(621)*XX(93)-JVS(952)*XX(108)-JVS(1201)*XX(114)&
             &-JVS(1423)*XX(119)-JVS(1507)*XX(121)
  XX(55) = XX(55)-JVS(544)*XX(87)-JVS(647)*XX(94)-JVS(694)*XX(96)-JVS(856)*XX(104)-JVS(875)*XX(105)-JVS(906)*XX(106)&
             &-JVS(926)*XX(107)-JVS(951)*XX(108)-JVS(1200)*XX(114)-JVS(1422)*XX(119)-JVS(1506)*XX(121)
  XX(54) = XX(54)-JVS(404)*XX(75)-JVS(481)*XX(83)-JVS(560)*XX(89)-JVS(1047)*XX(111)-JVS(1199)*XX(114)-JVS(1421)*XX(119)&
             &-JVS(1505)*XX(121)
  XX(53) = XX(53)-JVS(480)*XX(83)
  XX(52) = XX(52)-JVS(270)*XX(61)-JVS(1046)*XX(111)-JVS(1198)*XX(114)-JVS(1302)*XX(116)-JVS(1328)*XX(117)-JVS(1471)&
             &*XX(120)
  XX(51) = XX(51)-JVS(646)*XX(94)-JVS(693)*XX(96)-JVS(732)*XX(98)-JVS(779)*XX(100)-JVS(925)*XX(107)-JVS(1197)*XX(114)&
             &-JVS(1420)*XX(119)-JVS(1504)*XX(121)-JVS(1574)*XX(122)
  XX(50) = XX(50)-JVS(207)*XX(53)-JVS(355)*XX(72)-JVS(591)*XX(91)-JVS(813)*XX(102)-JVS(1045)*XX(111)-JVS(1196)*XX(114)
  XX(49) = XX(49)-JVS(731)*XX(98)-JVS(762)*XX(99)-JVS(778)*XX(100)-JVS(924)*XX(107)-JVS(950)*XX(108)-JVS(1195)*XX(114)&
             &-JVS(1419)*XX(119)-JVS(1503)*XX(121)-JVS(1573)*XX(122)
  XX(48) = XX(48)-JVS(241)*XX(57)-JVS(479)*XX(83)-JVS(949)*XX(108)-JVS(1194)*XX(114)-JVS(1327)*XX(117)-JVS(1502)*XX(121)
  XX(47) = XX(47)-JVS(403)*XX(75)-JVS(559)*XX(89)-JVS(1193)*XX(114)-JVS(1418)*XX(119)-JVS(1501)*XX(121)
  XX(46) = XX(46)-JVS(249)*XX(58)-JVS(692)*XX(96)-JVS(777)*XX(100)-JVS(1134)*XX(113)-JVS(1192)*XX(114)-JVS(1500)*XX(121)&
             &-JVS(1572)*XX(122)
  XX(45) = XX(45)-JVS(1044)*XX(111)-JVS(1191)*XX(114)
  XX(44) = XX(44)-JVS(1043)*XX(111)-JVS(1190)*XX(114)-JVS(1326)*XX(117)-JVS(1499)*XX(121)
  XX(43) = XX(43)-JVS(269)*XX(61)-JVS(1189)*XX(114)-JVS(1301)*XX(116)
  XX(42) = XX(42)-JVS(1269)*XX(115)-JVS(1300)*XX(116)-JVS(1470)*XX(120)-JVS(1571)*XX(122)
  XX(41) = XX(41)-JVS(308)*XX(66)-JVS(1042)*XX(111)-JVS(1188)*XX(114)-JVS(1570)*XX(122)
  XX(40) = XX(40)-JVS(320)*XX(67)-JVS(543)*XX(87)-JVS(645)*XX(94)-JVS(730)*XX(98)-JVS(905)*XX(106)-JVS(1417)*XX(119)
  XX(39) = XX(39)-JVS(855)*XX(104)-JVS(923)*XX(107)-JVS(1041)*XX(111)-JVS(1187)*XX(114)
  XX(38) = XX(38)-JVS(830)*XX(103)-JVS(1186)*XX(114)
  XX(37) = XX(37)-JVS(948)*XX(108)-JVS(1133)*XX(113)-JVS(1185)*XX(114)-JVS(1416)*XX(119)
  XX(36) = XX(36)-JVS(874)*XX(105)-JVS(1040)*XX(111)-JVS(1132)*XX(113)-JVS(1325)*XX(117)-JVS(1415)*XX(119)
  XX(35) = XX(35)-JVS(354)*XX(72)-JVS(558)*XX(89)-JVS(947)*XX(108)-JVS(1184)*XX(114)-JVS(1498)*XX(121)
  XX(34) = XX(34)-JVS(873)*XX(105)-JVS(1183)*XX(114)
  XX(33) = XX(33)-JVS(1039)*XX(111)-JVS(1182)*XX(114)-JVS(1371)*XX(118)
  XX(32) = XX(32)-JVS(989)*XX(109)-JVS(1268)*XX(115)-JVS(1370)*XX(118)
  XX(31) = XX(31)-JVS(620)*XX(93)-JVS(1181)*XX(114)-JVS(1497)*XX(121)
  XX(30) = XX(30)-JVS(1180)*XX(114)
  XX(29) = XX(29)-JVS(1179)*XX(114)
  XX(28) = XX(28)-JVS(1178)*XX(114)
  XX(27) = XX(27)-JVS(1177)*XX(114)
  XX(26) = XX(26)-JVS(117)*XX(32)-JVS(1038)*XX(111)-JVS(1267)*XX(115)-JVS(1369)*XX(118)
  XX(25) = XX(25)-JVS(453)*XX(80)-JVS(464)*XX(81)-JVS(676)*XX(95)-JVS(729)*XX(98)-JVS(1176)*XX(114)-JVS(1414)*XX(119)&
             &-JVS(1496)*XX(121)
  XX(24) = XX(24)-JVS(444)*XX(79)-JVS(463)*XX(81)-JVS(580)*XX(90)-JVS(728)*XX(98)-JVS(1175)*XX(114)-JVS(1413)*XX(119)&
             &-JVS(1495)*XX(121)
  XX(23) = XX(23)-JVS(478)*XX(83)-JVS(1037)*XX(111)-JVS(1324)*XX(117)
  XX(22) = XX(22)-JVS(279)*XX(62)-JVS(1013)*XX(110)-JVS(1569)*XX(122)
  XX(21) = XX(21)-JVS(523)*XX(85)-JVS(542)*XX(87)-JVS(644)*XX(94)-JVS(727)*XX(98)-JVS(904)*XX(106)-JVS(1412)*XX(119)
  XX(20) = XX(20)-JVS(435)*XX(78)-JVS(462)*XX(81)-JVS(675)*XX(95)-JVS(1174)*XX(114)-JVS(1411)*XX(119)-JVS(1494)*XX(121)
  XX(19) = XX(19)-JVS(1173)*XX(114)
  XX(18) = XX(18)-JVS(1172)*XX(114)
  XX(17) = XX(17)-JVS(1171)*XX(114)
  XX(16) = XX(16)-JVS(1170)*XX(114)
  XX(15) = XX(15)-JVS(691)*XX(96)-JVS(946)*XX(108)-JVS(1131)*XX(113)-JVS(1169)*XX(114)-JVS(1299)*XX(116)
  XX(14) = XX(14)-JVS(1568)*XX(122)
  XX(13) = XX(13)-JVS(142)*XX(38)-JVS(353)*XX(72)-JVS(590)*XX(91)-JVS(1168)*XX(114)-JVS(1493)*XX(121)
  XX(12) = XX(12)-JVS(1036)*XX(111)-JVS(1298)*XX(116)
  XX(11) = XX(11)-JVS(1130)*XX(113)-JVS(1167)*XX(114)-JVS(1410)*XX(119)
  XX(10) = XX(10)-JVS(55)*XX(19)-JVS(1166)*XX(114)
  XX(9) = XX(9)-JVS(19)*XX(10)-JVS(1165)*XX(114)
  XX(8) = XX(8)-JVS(16)*XX(9)-JVS(1164)*XX(114)
  XX(7) = XX(7)-JVS(1163)*XX(114)-JVS(1567)*XX(122)
  XX(6) = XX(6)-JVS(63)*XX(21)-JVS(1162)*XX(114)
  XX(5) = XX(5)
  XX(4) = XX(4)
  XX(3) = XX(3)-JVS(1566)*XX(122)
  XX(2) = XX(2)-JVS(1565)*XX(122)
  XX(1) = XX(1)-JVS(1564)*XX(122)
      
END SUBROUTINE KppSolveTR

! End of KppSolveTR function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE cbm7_strato_SOA_LinearAlgebra

