! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : cbm7_SOA_Parameters.f90
! Time                 : Mon Nov 11 16:36:37 2024
! Working directory    : /fmi/scratch/project_2001411/risto/puhtiruns/testCB7/silam_dev-testCB7-maxiter/kpp/cbm7_SOA
! Equation file        : cbm7_SOA.kpp
! Output root filename : cbm7_SOA
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE cbm7_SOA_Parameters

  USE cbm7_SOA_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 99 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 94 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 92 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 5 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 246 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 95 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 991 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 1160 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 95 
! NHESS - Length of Sparse Hessian
  INTEGER, PARAMETER :: NHESS = 917 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 99 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 1 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_AVB0 = 1 
  INTEGER, PARAMETER :: ind_BVB0 = 2 
  INTEGER, PARAMETER :: ind_O1D = 3 
  INTEGER, PARAMETER :: ind_PRPA = 4 
  INTEGER, PARAMETER :: ind_AVB1e6 = 5 
  INTEGER, PARAMETER :: ind_AVB1e5 = 6 
  INTEGER, PARAMETER :: ind_AVB1e4 = 7 
  INTEGER, PARAMETER :: ind_ECH4 = 8 
  INTEGER, PARAMETER :: ind_ETHA = 9 
  INTEGER, PARAMETER :: ind_ETHY = 10 
  INTEGER, PARAMETER :: ind_AVB1e0 = 11 
  INTEGER, PARAMETER :: ind_AVB1e1 = 12 
  INTEGER, PARAMETER :: ind_AVB1e2 = 13 
  INTEGER, PARAMETER :: ind_AVB1e3 = 14 
  INTEGER, PARAMETER :: ind_BENZENE = 15 
  INTEGER, PARAMETER :: ind_N2O5 = 16 
  INTEGER, PARAMETER :: ind_XPRP = 17 
  INTEGER, PARAMETER :: ind_TOL = 18 
  INTEGER, PARAMETER :: ind_XYL = 19 
  INTEGER, PARAMETER :: ind_ETOH = 20 
  INTEGER, PARAMETER :: ind_BVB1e0 = 21 
  INTEGER, PARAMETER :: ind_BVB1e1 = 22 
  INTEGER, PARAMETER :: ind_BVB1e2 = 23 
  INTEGER, PARAMETER :: ind_BVB1e3 = 24 
  INTEGER, PARAMETER :: ind_HACT = 25 
  INTEGER, PARAMETER :: ind_HONO = 26 
  INTEGER, PARAMETER :: ind_PACD = 27 
  INTEGER, PARAMETER :: ind_HPLD = 28 
  INTEGER, PARAMETER :: ind_PAN = 29 
  INTEGER, PARAMETER :: ind_MEOH = 30 
  INTEGER, PARAMETER :: ind_MEPX = 31 
  INTEGER, PARAMETER :: ind_FACD = 32 
  INTEGER, PARAMETER :: ind_ROR7 = 33 
  INTEGER, PARAMETER :: ind_PANX = 34 
  INTEGER, PARAMETER :: ind_PNA = 35 
  INTEGER, PARAMETER :: ind_NTR1 = 36 
  INTEGER, PARAMETER :: ind_PAR7 = 37 
  INTEGER, PARAMETER :: ind_EPOX = 38 
  INTEGER, PARAMETER :: ind_CAT1 = 39 
  INTEGER, PARAMETER :: ind_OPAN = 40 
  INTEGER, PARAMETER :: ind_NTR2 = 41 
  INTEGER, PARAMETER :: ind_INTR = 42 
  INTEGER, PARAMETER :: ind_KET7 = 43 
  INTEGER, PARAMETER :: ind_CRO = 44 
  INTEGER, PARAMETER :: ind_ISPX = 45 
  INTEGER, PARAMETER :: ind_ARPX = 46 
  INTEGER, PARAMETER :: ind_H2O2 = 47 
  INTEGER, PARAMETER :: ind_AACD = 48 
  INTEGER, PARAMETER :: ind_ETH = 49 
  INTEGER, PARAMETER :: ind_SESQ = 50 
  INTEGER, PARAMETER :: ind_APIN = 51 
  INTEGER, PARAMETER :: ind_CRON = 52 
  INTEGER, PARAMETER :: ind_CO = 53 
  INTEGER, PARAMETER :: ind_C5H8 = 54 
  INTEGER, PARAMETER :: ind_OLE7 = 55 
  INTEGER, PARAMETER :: ind_IOLE = 56 
  INTEGER, PARAMETER :: ind_XPAR7 = 57 
  INTEGER, PARAMETER :: ind_ALDX = 58 
  INTEGER, PARAMETER :: ind_XO2H = 59 
  INTEGER, PARAMETER :: ind_XO2 = 60 
  INTEGER, PARAMETER :: ind_SQO2 = 61 
  INTEGER, PARAMETER :: ind_EPX2 = 62 
  INTEGER, PARAMETER :: ind_TPO2 = 63 
  INTEGER, PARAMETER :: ind_CRES = 64 
  INTEGER, PARAMETER :: ind_BZO2 = 65 
  INTEGER, PARAMETER :: ind_XLO2 = 66 
  INTEGER, PARAMETER :: ind_TO2 = 67 
  INTEGER, PARAMETER :: ind_HNO3 = 68 
  INTEGER, PARAMETER :: ind_C5H8_2 = 69 
  INTEGER, PARAMETER :: ind_HCHO = 70 
  INTEGER, PARAMETER :: ind_APO2 = 71 
  INTEGER, PARAMETER :: ind_XO2N = 72 
  INTEGER, PARAMETER :: ind_ACET = 73 
  INTEGER, PARAMETER :: ind_ISPD = 74 
  INTEGER, PARAMETER :: ind_GLYD = 75 
  INTEGER, PARAMETER :: ind_ALD2 = 76 
  INTEGER, PARAMETER :: ind_ISO2 = 77 
  INTEGER, PARAMETER :: ind_GLY = 78 
  INTEGER, PARAMETER :: ind_O = 79 
  INTEGER, PARAMETER :: ind_MGLY = 80 
  INTEGER, PARAMETER :: ind_ROOH = 81 
  INTEGER, PARAMETER :: ind_XOPN = 82 
  INTEGER, PARAMETER :: ind_OPEN = 83 
  INTEGER, PARAMETER :: ind_MEO2 = 84 
  INTEGER, PARAMETER :: ind_C2O3 = 85 
  INTEGER, PARAMETER :: ind_CXO3 = 86 
  INTEGER, PARAMETER :: ind_RO2 = 87 
  INTEGER, PARAMETER :: ind_HO2 = 88 
  INTEGER, PARAMETER :: ind_OH = 89 
  INTEGER, PARAMETER :: ind_NO3 = 90 
  INTEGER, PARAMETER :: ind_OPO3 = 91 
  INTEGER, PARAMETER :: ind_O3 = 92 
  INTEGER, PARAMETER :: ind_NO = 93 
  INTEGER, PARAMETER :: ind_NO2 = 94 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_H2O = 95 
  INTEGER, PARAMETER :: ind_H2 = 96 
  INTEGER, PARAMETER :: ind_O2 = 97 
  INTEGER, PARAMETER :: ind_CH4 = 98 
  INTEGER, PARAMETER :: ind_M = 99 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_H2O = 1 
  INTEGER, PARAMETER :: indf_H2 = 2 
  INTEGER, PARAMETER :: indf_O2 = 3 
  INTEGER, PARAMETER :: indf_CH4 = 4 
  INTEGER, PARAMETER :: indf_M = 5 

END MODULE cbm7_SOA_Parameters

